### ISSUE TITLE
[Feature Request] Allow theHarvester to run in a shell script

### ISSUE THREAD

**Issue by bwyyoung** [laramies/theHarvester#1006]
**Feature Request or Bug or Other**
Feature Request
Allow theHarvester to run in a shell script

**Describe the feature request or bug or other**
Currently, running theHarvester in a shell script produces no emails or results.
How is it possible to make it run in a shell script?

**To Reproduce**
Steps to reproduce the behaviour:
create a shell script like this (myharvester.sh):
```
#!/bin/bash
input="./urls_harvestertest.csv"
while IFS= read -r line
do
  echo "processing $line"
  python theHarvester.py -d "$line" -b all
done < "$input"
```
urls_harvestertest.csv has urls, separated by newline.
No emails or hosts are returned. Instead there are some cryptic errors:
An exception has occurred: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url=URL('https://api.n45ht.or.id/v1/subdomain-enumeration?domain=http://website.com')

**Expected behaviour**
When running theHarvester normally outside of shell script, in plain bash, it works normally.

**System Information (System that tool is running on):**
Ubuntu Linux, Bash

**Comment by bwyyoung** [comment]
It is OK. theHarvester works in shell script, issue was with google searches and how they are blocked.

**Comment by NotoriousRebel** [comment]
You can also do `-f` and that will create an output json and xml file, the json one can be easily parsed using tools like jq.
