### ISSUE TITLE
Works, but returns a bunch of errors on Parrot OS

### ISSUE THREAD

**Issue by pawstar-lag** [laramies/theHarvester#1049]
So when I use theHarvester, I get the thing I want, but I also get a bunch of errors. Here is a screenshot:
![image](https://user-images.githubusercontent.com/69009801/157778420-4948e766-0cd5-44c0-a65c-089ec9e1eb60.png)
theHarvester comes with Parrot OS so I am kind of suprised as to why there is an error. Please help.

**Comment by ResistOrRegret** [comment]
It's not working for me at all. (Parrot OS)

(https://user-images.githubusercontent.com/79291759/158284191-d6417ade-0e98-4bb0-8234-37e280cff249.png)

**Comment by L1ghtn1ng** [comment]
Does it work correctly for you if you used kali? Just trying to understand if it’s specific to parrot?

On 15 Mar 2022, at 00:47, Revy ***@***.***> wrote:

﻿

It's not working for me at all. (Parrot OS)

(https://user-images.githubusercontent.com/79291759/158284191-d6417ade-0e98-4bb0-8234-37e280cff249.png)

**Comment by NotoriousRebel** [comment]
This appers to be an issue related with uvloop, if you comment out the [following two lines](https://github.com/laramies/theHarvester/blob/master/theHarvester.py#L20-L21). Does the error still persist? If it doesn't that would confirm it's a uvloop error and you should create a new issue within [uvloop's repo](https://github.com/MagicStack/uvloop/issues).

**Comment by L1ghtn1ng** [comment]
Timeout

**Comment by pawstar-lag** [comment]
I'll try that!

**Comment by pawstar-lag** [comment]
> This appers to be an issue pertaining to uvloop, if you comment out the [following two lines](https://github.com/laramies/theHarvester/blob/master/theHarvester.py#L20-L21). Does the error still persist? If it doesn't that would confirm it's a uvloop error and you should create a new issue within [uvloop's repo](https://github.com/MagicStack/uvloop/issues).

I tried commenting the 2 lines and it doesn't even print anything, so I believe that the error is present in something else.
