### ISSUE TITLE
Google CSE

### ISSUE THREAD

**Issue by leebaird** [laramies/theHarvester#105]
./theHarvester.py -d target.com -b googleCSE

Traceback (most recent call last):
  File "/root/theharvester/theHarvester.py", line 676, in <module>
    start(sys.argv[1:])
  File "/root/theharvester/theHarvester.py", line 200, in start
    db.store_all(word,all_hosts,'email','googleCSE')
UnboundLocalError: local variable 'all_hosts' referenced before assignment

**Comment by NotoriousRebel** [comment]
Here is the solution: 
```db=stash.stash_manager()
                        all_hosts = search.get_hostnames()
                        db.store_all(word,all_hosts,'email','googleCSE')
                        db=stash.stash_manager()
                        db.store_all(word,all_hosts,'host','googleCSE')```

**Comment by NotoriousRebel** [comment]
The problem was just the order in which things occurred, that must've slipped through in development thank you for pointing it out!

**Comment by leebaird** [comment]
Thanks for the quick resolution! Hopefully Chris will commit soon.

**Comment by laramies** [comment]
Fixed now
