### ISSUE TITLE
[Bug] n45ht module broken

### ISSUE THREAD

**Issue by leebaird** [laramies/theHarvester#1082]
**Bug**

**Describe the feature request or bug or other**
An exception has occurred: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.n45ht.or.id/v1/subdomain-enumeration?domain=apple.com')

**To Reproduce**
./theHarvester.py -d apple.com -b n45ht

**Expected behaviour**
Show results.

**System Information (System that tool is running on):**
 - OS: Kali Linux 2022.2

**Comment by L1ghtn1ng** [comment]
This has been removed in my branch due to the api not working anymore
