### ISSUE TITLE
Results from 2 sources are not merged

### ISSUE THREAD

**Issue by Faeris95** [laramies/theHarvester#110]
Hi,
When I specify two sources to search from : google,bing
theHarvester searches with bing, then google but only the results from Google are showed and saved.

Best regards

**Comment by Faeris95** [comment]
In the case of automated scripts, that's not the better way. The functionality does exist, it should work ! :)

**Comment by NotoriousRebel** [comment]
Here is a quick workaround in the meantime : 
python3 theHarvester.py -d cornell.edu -b google -l 500 | cat > /filepath/ && python3 theHarvester.py -d cornell.edu -b bing -l 500 | cat >> /filepath/

**Comment by NotoriousRebel** [comment]
This could be something implemented down the line, I believe the reason is the tool was primarily built for one search engine at a time or all. Although, it shouldn't be too hard to change.

**Comment by laramies** [comment]
I will look into that, as it should work as @Faeris95 is expecting.

**Comment by Faeris95** [comment]
Thanks :+1:

**Comment by laramies** [comment]
Should be fixed now @Faeris95
