### ISSUE TITLE
[Bug] bufferoverun error

### ISSUE THREAD

**Issue by 1979139113** [laramies/theHarvester#1107]
## Note we do not support installing theHarvester on andriod

**Feature Request or Bug or Other**
Bug

bufferoverun interface error, intercepted by man-machine identification

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tool like this: `python3 theHarvester.py -d gm7.org -b bufferoverun`
2. See error `An exception has occurred: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://dns.bufferover.run/dns?q=gm7.org')`

**Debug Analysis**
return result is not json
<img width="1920" alt="图片" src="https://user-images.githubusercontent.com/24983597/170396455-b0bfb494-b9ff-4310-a40a-878944d36792.png">

**Screenshots**
If possible please add screenshots to help explain your problem.
<img width="1671" alt="图片" src="https://user-images.githubusercontent.com/24983597/170396557-6a2e86d6-9bba-475e-95f8-2ef002f649dd.png">

**System Information (System that tool is running on):**
 - OS: mac
 - Version:3.8

**Additional context**

**Comment by L1ghtn1ng** [comment]
I cannot reproduce this error as it works for me, I am however using python 3.10 and a virtualenv which I highly recommend you do as well as it does remove any issues that are system related etc as well as being best practice when it comes to python apps
