### ISSUE TITLE
GoogleCSE is broken

### ISSUE THREAD

**Issue by leebaird** [laramies/theHarvester#111]
Using my API key in googleCSE.py

Traceback (most recent call last):
   File "/usr/share/theharvester/theHarvester.py", line 678, in <module>
      start(sys.argv[1:])
   File "/usr/share/theharvester/theHarvester.py", line 202, in start
      db.store_all(word,all_hosts,'email','googleCSE')

**Comment by NotoriousRebel** [comment]
Thank you for the heads up this is getting looked at.

**Comment by NotoriousRebel** [comment]
I notice one problem immediately in which it should be 
```db.store_all(word,all_emails,'email','googleCSE')``` on line 201 not
```db.store_all(word,all_hosts,'email','googleCSE')```

**Comment by leebaird** [comment]
No more stack track. Just no results.

**Comment by leebaird** [comment]
Spoke with Chris and have decided to remove.
