### ISSUE TITLE
[Bug] Cannot install - 404 on L1ghtn1ng/spyse-python dependency

### ISSUE THREAD

**Issue by mcnamee** [laramies/theHarvester#1164]
**Feature Request or Bug or Other**
Bug

**Describe the feature request or bug or other**
Cannot install due to missing dependency (https://github.com/L1ghtn1ng/spyse-python from [the requirements](https://github.com/laramies/theHarvester/blob/master/requirements/base.txt#L21) returns a 404).

**To Reproduce**
Steps to reproduce the behaviour:

I run:

```bash
git clone --depth 1 https://github.com/laramies/theHarvester
cd theHarvester
python3 -m pip install -r requirements/base.txt
```

Error received:

```bash
Obtaining spyse-python from git+https://github.com/L1ghtn1ng/spyse-python@main#egg=spyse-python (from -r requirements/base.txt (line 21))
  Cloning https://github.com/L1ghtn1ng/spyse-python (to revision main) to ./src/spyse-python
  Running command git clone --filter=blob:none --quiet https://github.com/L1ghtn1ng/spyse-python /etc/theHarvester/src/spyse-python
  fatal: could not read Username for 'https://github.com/': No such device or address
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/L1ghtn1ng/spyse-python /etc/theHarvester/src/spyse-python did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/L1ghtn1ng/spyse-python /etc/theHarvester/src/spyse-python did not run successfully.
│ exit code: 128
```

**Expected behaviour**
I expect that running `python3 -m pip install -r requirements/base.txt` will install theHarvester.

**Comment by simillo01** [comment]
Agree on your post and i solved by doing this: (i use pycharm)
- go to the bottom of the ide and click on the "Python Packages" tab
- search for that package and install (it will install version 2.2.3)
- after that you will see that the ide suggests you that the installed version does not match the required version (i remember 2.2.8 i think), so click on that warning and it will update the lib and install the required version.

Enjoy

**Comment by mcnamee** [comment]
Thanks @simillo01

Unfortunately in my case, the installation of theHarvester is scripted and run by a CI tool.

**Comment by L1ghtn1ng** [comment]
Will have a look at this later today, it was me removing my fork of the repo due to spyse shutting down etc

On 3 Aug 2022, at 11:05, Matt McNamee ***@***.***> wrote:

﻿

Thanks @simillo01<https://github.com/simillo01>

Unfortunately in my case, the installation of theHarvester is scripted and run by a CI tool.

**Comment by Kamikaze798** [comment]
hello i try this repo and work for me https://github.com/spyse-com/spyse-python and it work just fine

**Comment by L1ghtn1ng** [comment]
This is fixed in master
