### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by byposeidon** [laramies/theHarvester#1175]
theHarvester 4.2.0dev
python3 theHarvester.py -d microsoft.com -l 500 -b google

[!] Invalid source.

**Comment by byposeidon** [comment]
python3 theHarvester.py -d microsoft.com -l 500 -b google

**Comment by L1ghtn1ng** [comment]
Please see here for why https://github.com/laramies/theHarvester/releases

**Comment by L1ghtn1ng** [comment]
You have not picked a source to run so what you are getting is correct. You can see what sources are available with -h switch and you will want to look under -b switch in the output

On 9 Aug 2022, at 15:16, Poseidon ***@***.***> wrote:

﻿

python3 theHarvester.py -d google.com

________________________________

  *   _ _ _ *
  *   | || |__ ___ /\ /_ _ _ ____ _____ __| | ___ _ __ *
  *   | | _ \ / _ \ / /_/ / _` | '\ \ / / _ / __| / _ \ '| *
  *   | || | | | __/ / __ / (| | | \ V / _/_ \ || __/ | *
  *   _|| ||___| / // _,|| _/ _||/____|| *
  *

                                                            *


  *   theHarvester 4.2.0dev *
  *   Coded by Christian Martorella *
  *   Edge-Security Research *
  *   ***@***.******@***.***> *
  *

                                                            *


________________________________

[*] No IPs found.

[*] No emails found.

[*] No hosts found.

**Comment by georgiprogramira** [comment]
> Please see here for why https://github.com/laramies/theHarvester/releases

so we cannot use google as a source?

**Comment by L1ghtn1ng** [comment]
Correct

On 23 Oct 2022, at 13:39, georgi_atanasowww ***@***.***> wrote:

﻿

Please see here for why https://github.com/laramies/theHarvester/releases

so we cannot use google as a source?
