### ISSUE TITLE
Getting No Results From theHarvester

### ISSUE THREAD

**Issue by babucarr32** [laramies/theHarvester#1190]
Please help.
When I run a search in theharvester I get no results i.e. 
Mycommand--> theHarvester -d target.org -l 500 -b bing 

[*] Target: target.org 
substring not found
        Searching 0 results.
substring not found
        Searching 100 results.
substring not found
        Searching 200 results.
substring not found
        Searching 300 results.
substring not found
        Searching 400 results.
substring not found
        Searching 500 results.
[*] Searching Google. 

[*] No IPs found.

[*] No emails found.

[*] No hosts found

**Comment by L1ghtn1ng** [comment]
What version of theHarvester are you using and on what OS?

**Comment by Irsantal** [comment]
Hello, 
I've got the same issue after upgrading theHarvester to 4.02 on my kali linux 2022.3.

**Comment by L1ghtn1ng** [comment]
Bing module is currently broken if you pick another source to use does it work correctly?

**Comment by Irsantal** [comment]
Seems like any other source is invalid. I tried many and I've got the following output every time:
`[!] Invalid source.`

**Comment by L1ghtn1ng** [comment]
Can you show me what you are doing?

**Comment by Irsantal** [comment]
Sure. Here is a screenshot for instance
![image](https://user-images.githubusercontent.com/45181559/192503192-dd40309a-6f11-4ccf-9c86-89a0c1daf50f.png)

And when I type the same command without specifying source, I have no results.

**Comment by L1ghtn1ng** [comment]
Okay so 2 things.

1.) you always need to put the fqdn so in this case Microsoft.com that will fix your -d issue.
2.) getting invalid source is correct as everything that used Google has been removed.  Check what sources are available with -h so theHarvester -h also you do not need to run it with sudo either

On 27 Sep 2022, at 11:35, Irvinn R. ***@***.***> wrote:

﻿

Sure. Here is a screenshot for instance
[image]<https://user-images.githubusercontent.com/45181559/192503192-dd40309a-6f11-4ccf-9c86-89a0c1daf50f.png>

And when I type the same command without specifying source, I have no results.

**Comment by Irsantal** [comment]
Got it for sources, thanks.
But since -b option is not required, I'm assuming that if I type 
`theHarvester -d microsoft.com`
I should have results right ? I have no results for now.

**Comment by L1ghtn1ng** [comment]
The -b is required and sorry for the late reply

**Comment by L1ghtn1ng** [comment]
No without actually having a source you will not get any results, if I recall correctly there is a reason why -b is not set to required as well but I cannot for the life of me remember why

On 27 Sep 2022, at 12:18, Irvinn R. ***@***.***> wrote:

﻿

Got it for sources, thanks.
But since -b option is not required, I'm assuming that if I type
theHarvester -d microsoft.com
I should have results right ? I have no results for now.

**Comment by yalattas** [comment]
based on my observation of the tool.
Source is indeed required and you can find available sources in API -> GET `http://localhost:8080/sources/`

LinkedIn was available before and thanks to @jay_townsend1 for confirming that LinkedIn was removed.

Hopefully, people can contribute and bring LinkedIn back again

I recommend closing this issue as long as it's not a real bug
