### ISSUE TITLE
theHarvester showing [!] Invalid source.

### ISSUE THREAD

**Issue by rahulsrstudy** [laramies/theHarvester#1205]
While executing the command, showing, [!] Invalid source.

theHarvester -d "domain/company" -l 200 -b source

Can You please guide?

**Comment by L1ghtn1ng** [comment]
Look at theHarvester -h

On 10 Sep 2022, at 13:46, rahulsrstudy ***@***.***> wrote:

﻿

While executing the command, showing, [!] Invalid source.

theHarvester -d "domain/company" -l 200 -b source

Can You please guide?

**Comment by L1ghtn1ng** [comment]
Please see issue #1224
