### ISSUE TITLE
Harvester invalid source issue 

### ISSUE THREAD

**Issue by akash7118** [laramies/theHarvester#1224]
When I execute theHarvester with the following parameters:

theHarvester -d microsoft -l 500 -b linkedin

I get the following output:
[!] Invalid source.

From the code doesn't look like accepting 'all' parameter.

Pls help

**Comment by L1ghtn1ng** [comment]
You need need to be using Microsoft.com with the -d switch but if using 4.2.0 then that module has been removed see the sources that are available with -h

**Comment by ZerkerEOD** [comment]
@L1ghtn1ng can I ask why Linkedin was removed as a source?

**Comment by L1ghtn1ng** [comment]
@ZerkerEOD It was removed as it used Google and was getting blocked. A good alternative is rocketreach module. If LinkedIn has an actual api that can be used    then it could come back in that form but for now everything that used google was removed as it was just creating to my issue tickets with no way of fixing it with how those modules where set. Hope that makes sense?

**Comment by swipe000** [comment]
the problem is the source linkedin is no more working so use yahoo instead

**Comment by ENG-ELDEFEY** [comment]
When even I use it in : 
theHarvester -d davidbombal.com -b edge 
Or any other browser it shows me the same issue ("invalid source ") 
How to fix ..?

**Comment by L1ghtn1ng** [comment]
There is no source edge, you need to look at the help output for the source section which shows you the api’s you can use which you can see doing theHarvester -h

On 14 Aug 2024, at 13:03, ENG-ELDEFEY ***@***.***> wrote:

﻿

When even I use it in :
theHarvester -d davidbombal.com -b edge
Or any other browser it shows me the same issue ("invalid source ")
How to fix ..?

**Comment by Loop213** [comment]
change the -b linkedin to -baidu or any other
