### ISSUE TITLE
Other invalid source linkedin

### ISSUE THREAD

**Issue by DayNja** [laramies/theHarvester#1242]
when using theharvester against my own domain. and to get a list from linkedin, i get an error saying invalid source.
ive tried installing, using the methods in this repo, ive tried using kali and still the same error

is linkedin not supported anymore? 
![image](https://user-images.githubusercontent.com/44928992/200614657-7507bae6-bb24-470d-b5ac-fa588337ce5d.png)

**Comment by L1ghtn1ng** [comment]
No, LinkedIn is not supported any more as it used Google to get the results and Google is blocking scripts, so it was removed and other modules that used Google. Not to say that they could not come back in the feature but would need to be done a completely different way than was done before. Always check the help switch to see new sources and ones that have been removed.
