### ISSUE TITLE
No Result Issue

### ISSUE THREAD

**Issue by mehmetozbakir** [laramies/theHarvester#125]
Hello Dear, 
I'm trying it on Ubuntu 16.04 LTS x86_64 (ISO) via VPS server, When I tried first time 2 domains it was work but after that doesn't work even same domain doesn't work. No Result... What should be the problem?

*******************************************************************
*                                                                 *
* | |_| |__   ___    /\  /\__ _ _ ____   _____  ___| |_ ___ _ __  *
* | __| '_ \ / _ \  / /_/ / _` | '__\ \ / / _ \/ __| __/ _ \ '__| *
* | |_| | | |  __/ / __  / (_| | |   \ V /  __/\__ \ ||  __/ |    *
*  \__|_| |_|\___| \/ /_/ \__,_|_|    \_/ \___||___/\__\___|_|    *
*                                                                 *
* theHarvester Ver. 3.0.5                                         *
* Coded by Christian Martorella                                   *
* Edge-Security Research                                          *
* cmartorella@edge-security.com                                   *
*******************************************************************

found supported engines
[-] Starting harvesting process for domain: rigafoods.com

[-] Searching in Google:
        Searching 0 results...
        Searching 100 results...
        Searching 200 results...
        Searching 300 results...
        Searching 400 results...
        Searching 500 results...

Harvesting results
No IP addresses found

[+] Emails found:
------------------
No emails found

[+] Hosts found in search engines:
------------------------------------
No hosts found

**Comment by NotoriousRebel** [comment]
It may be google blocking your requests, try now and see if that still happens. 
Google should be blocking your requests less once my PR gets merged.

**Comment by laramies** [comment]
Highly likely that's the case, try with the latest version please and let us know. I am closing it due to being an external cause :(

**Comment by mehmetozbakir** [comment]
> Highly likely that's the case, try with the latest version please and let us know. I am closing it due to being an external cause :(

Brother, already it's latest version 3.0.5?

**Comment by Jsimpki** [comment]
Still doing it in the current version of Kali

**Comment by L1ghtn1ng** [comment]
This is due to Kali having an old version, this will be fixed when we tag a new realse
________________________________
