### ISSUE TITLE
improvements on running with -b all

### ISSUE THREAD

**Issue by PlasmaHH** [laramies/theHarvester#126]
Hi, there are a couple of points that might running with -b all easier/ more maintainable

- replace the if(engineitem == "all") with a previous check of if it contains all, if yes replace engines by supportedengines and let the if/elif tree mechanism handle it. No duplciation of the call and output later on

- wrap the whole if/elif thing in a try/except and let the modules throw errors instead of calling sys.exit when something went wrong so the rest can go on. Also some call unconditionally sys.exit that might not be the best choice.

**Comment by leebaird** [comment]
One of the problems with this option is the 'all' option is missing 11 data sources. Those include:
baidu, cymon, dogpile, googleplus, google-certificates, google-profiles, linkedin, trello, twitter, ghost, and yahoo. You will see placeholders that I have added if my PR gets added.
