### ISSUE TITLE
hunter api issue

### ISSUE THREAD

**Issue by BlAd373** [laramies/theHarvester#127]
You need an API key in order to use the Hunter search engine. You can get one here: https://hunter.io
I put the api key on /usr/share/theharvester/discovery/huntersearch.py
self.database = "https://api.hunter.io/v2/domain-search?domain=" + word + "&api_key=xxxxxxxxxxxxxxxxxxxxxxxx" + self.key +"&limit=" + str(self.limit)
but same error

**Comment by NotoriousRebel** [comment]
What you want to do is:
self.key = *your_api_key*
I just tested it with my api key and it seems to be working is your key expired?
Do you have any requests left? I know hunter limits your requests depending on what plan you're on.

**Comment by tw4ds** [comment]
Another piece to remember on this for anyone updating the API is to remove the ""s as it needs to be formatted as an integer.
