### ISSUE TITLE
 File "<frozen importlib._bootstrap>", line 1007, in _find_and_load   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked   File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible   File "<frozen zipimport>", line 259, in load_module   File "/usr/local/lib/python3.9/dist-packages/theHarvester-4.3.0.dev0-py3.9.egg/theHarvester/lib/hostchecker.py", line 14, in <module>   File "/usr/local/lib/python3.9/dist-packages/theHarvester-4.3.0.dev0-py3.9.egg/theHarvester/lib/hostchecker.py", line 37, in Checker TypeError: unsupported operand type(s) for |: 'type' and '_SpecialForm'

### ISSUE THREAD

**Issue by likith-66** [laramies/theHarvester#1291]
## Note we do not support installing theHarvester on andriod

**Feature Request or Bug or Other**
Feature Request | Bug | Other

**Describe the feature request or bug or other**
A clear and concise description of what the bug, feature request,
or other request is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tool like this: '...'
2. See error

**Expected behaviour**

**Screenshots**
If possible please add screenshots to help explain your problem.

**System Information (System that tool is running on):**
 - OS: [e.g. Windows10]
 - Version [e.g. 2.7]

**Additional context**

**Comment by L1ghtn1ng** [comment]
You need to use python 3.10 theHarvester does not work under python 3.9

**Comment by mick-tesla** [comment]
why ? what's the main difference

**Comment by L1ghtn1ng** [comment]
Using certain features of python3.10 to make the code better  basically
