### ISSUE TITLE
[Bug| api-keys not reading properly!!

### ISSUE THREAD

**Issue by Guymosciski** [laramies/theHarvester#1308]
##   INFO   ##
Hi, i have installed theHarvester in my digital ocean droplet, through git clone, provided all the api keys in the root folder api-keys.yaml  
just missed projectdiscovery and pentesttool keys
it showed correctly both the keys are missing and got the results as expected. 
[the command i used ./theHarvester.py -b all -d example.com].
##     ISSUE    ##
An exception has occurred: Cannot connect to host www.threatcrowd.org:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.threatcrowd.org'. (_ssl.c:997)")]
string indices must be integers
[*] Searching Threatcrowd.
An exception has occurred: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.threatminer.org/v2/domain.php?q=example.com&rt=5')
[*] Searching Urlscan.
An exception has occurred: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.sublist3r.com/search.php?domain=example.com')
[*] Searching Sublist3r.
[*] Searching Virustotal.
[*] Searching Yahoo.
Your resp: {'code': 50005, 'error': 'exceed_result_page', 'message': 'This page does not exist', 'url': 'https://www.zoomeye.org/api'} 
could please someone help me 
Thanks.

**Comment by L1ghtn1ng** [comment]
if you create the api-keys file in /etc/theHarvester/ should work fine and will get around this issue
