### ISSUE TITLE
How can I use the command -b all?

### ISSUE THREAD

**Issue by AdalbChop759** [laramies/theHarvester#1310]

**Comment by Drew-Alleman** [comment]
theHarvester -d google.com -b all

**Comment by AdalbChop759** [comment]
> theHarvester -d google.com -b all
> 
> Is this what you want?

yes, but when i use this command i get the following message:

[!] Missing API key for binaryedge
...
[!] Missing API key for zoomeye

How do i put these keys?

**Comment by Drew-Alleman** [comment]
Yes, if you read the Docs you would understand some of the modules need API keys to function. The Wiki section contains information about where to add keys. The README is there for a reason. https://github.com/laramies/theHarvester/wiki/Installation#option-4---from-source here is a video https://youtu.be/-Px9xqafS9A?t=203

**Comment by AdalbChop759** [comment]
Thanks!
