### ISSUE TITLE
Cymon.io v2 API

### ISSUE THREAD

**Issue by L1ghtn1ng** [laramies/theHarvester#134]
V2 of the API is coming soon, so this will need to to be updated to support this

http://docs.cymon.io/#top

**Comment by jzold** [comment]
cymon is discontinued from April and not available.

**Comment by L1ghtn1ng** [comment]
Yeah I just tried going to the site and does not load at all, that is a shame

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
