### ISSUE TITLE
[Bug| Github - RuntimeWarning: coroutine 'start.<locals>.store' was never awaited

### ISSUE THREAD

**Issue by joaociocca** [laramies/theHarvester#1342]
**Feature Request or Bug or Other**

Bug

**Describe the feature request or bug or other**

I'm playing around with bash stuff, making an auto/manual with menu for choosing theHarvester sources to be used.

When I ran theHarvester with `-b baidu,bingapi,certspotter,crtsh,dnsdumpster,duckduckgo,hackertarget,omnisint,otx,qwant,rapiddns,sublist3r,threatcrowd,threatminer,urlscan,virustotal,yahoo,binaryedge,bing,bufferoverun,fullhunt,github-code,hunter,securityTrails,zoomeye -s`, I got the error below:

```
'github'
sys:1: RuntimeWarning: coroutine 'start.<locals>.store' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

Which I find most curious, because I'm not selecting a `github` source, but `github-code`, as is listed on 4.2.0's help:

```
-b SOURCE, --source SOURCE
                        anubis, baidu, bevigil, binaryedge, bing, bingapi, bufferoverun, censys, certspotter, crtsh,
                        dnsdumpster, duckduckgo, fullhunt, github-code, hackertarget, hunter, intelx, omnisint, otx,
                        pentesttools, projectdiscovery, qwant, rapiddns, rocketreach, securityTrails, sublist3r,
                        threatcrowd, threatminer, urlscan, virustotal, yahoo, zoomeye
```

If I remove the `github-code`, theHarvester is executed and the error is no longer shown... although I do get a couple of other errors, which I'm not sure I should bundle in this issue or open new ones:

```
[*] Searching Bing. 
An exception has occurred: Cannot connect to host dns.bufferover.run:443 ssl:<ssl.SSLContext object at 0x7f0503a42ec0> [Name or service not known]
[*] Searching Rapiddns. 
An exception has occurred: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://sonar.omnisint.io/all/<target>?page=1')
[*] Searching SecurityTrails. 
An exception has occurred: Cannot connect to host www.threatcrowd.org:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.threatcrowd.org'. (_ssl.c:997)")]
[*] Searching Urlscan. 
An exception has occurred: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.sublist3r.com/search.php?domain=<target>')
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tool like this: `theHarvester -b baidu,bingapi,certspotter,crtsh,dnsdumpster,duckduckgo,hackertarget,omnisint,otx,qwant,rapiddns,sublist3r,threatcrowd,threatminer,urlscan,virustotal,yahoo,binaryedge,bing,bufferoverun,fullhunt,hunter,securityTrails,zoomeye -s -d <target>`
2. See error

**Expected behaviour**
theHarvester should execute and return github results, or nothing if not found.

**Screenshots**
![image](https://user-images.githubusercontent.com/6473725/220890721-a7e9c897-6a88-4957-a4d4-354295165290.png)
![image](https://user-images.githubusercontent.com/6473725/220890808-f9a5840f-d87a-4cd1-9770-8ceb86782c1f.png)
![image](https://user-images.githubusercontent.com/6473725/220890934-3a8f9693-90df-4c72-b6cd-15136ff70581.png)

**System Information (System that tool is running on):**
 - OS: Kali 2022.3
 - Version 4.2.0

**Comment by joaociocca** [comment]
heh, I just noticed that "response payload is not completed" exception...
and... Zoomeye module seems stuck?

**Comment by xc0rv0** [comment]
This Issue appeard to me too I tried to break between the key and Its Value with a space and it worked fine but I still get the SSL Certificate error (Exceptional error) and don't know why  or how to fix it 
the command was :  theHarvester -d domain -b all

**Comment by L1ghtn1ng** [comment]
Will tag a new release as there has been a load of new fixes for modules etc, will look at doing that after work. It will take a little bit for it to get pulled into kali etc
