### ISSUE TITLE
theHarvester Give [!] invalid source.

### ISSUE THREAD

**Issue by Zazan-Developer** [laramies/theHarvester#1358]
python3 theHarvester.py -d iub.edu.pk -l 500 -b google
*******************************************************************
*  _   _                                            _             *
* | |_| |__   ___    /\  /\__ _ _ ____   _____  ___| |_ ___ _ __  *
* | __|  _ \ / _ \  / /_/ / _` | '__\ \ / / _ \/ __| __/ _ \ '__| *
* | |_| | | |  __/ / __  / (_| | |   \ V /  __/\__ \ ||  __/ |    *
*  \__|_| |_|\___| \/ /_/ \__,_|_|    \_/ \___||___/\__\___|_|    *
*                                                                 *
* theHarvester 4.3.0                                              *
* Coded by Christian Martorella                                   *
* Edge-Security Research                                          *
* cmartorella@edge-security.com                                   *
*                                                                 *
*******************************************************************

[!] Invalid source.

**Comment by mick-tesla** [comment]
Google is not a supported source anymore, according to issue #1202, have a lookat there

**Comment by L1ghtn1ng** [comment]
that is correct google is not a source anymore due to it always getting blocked by a captcha
