### ISSUE TITLE
[Bug|Feature Request|Other] Short Description of Issue

### ISSUE THREAD

**Issue by ahmadyounas78654** [laramies/theHarvester#1374]
## Note we  install  the Harvester but google as a source not working 
![44](https://user-images.githubusercontent.com/129259692/228449159-11d9a873-1428-42ab-b236-49dc70596583.JPG)

**Feature Request or Bug or Other**
Feature Request | Bug | Other

**Describe the feature request or bug or other**
I install the harvester and use it all the search engines are working but google cannot work. 

**Screenshots**
I attach the screenshot please help me and explain it.

**System Information (System that tool is running on):**
 - OS: [e.g. Windows10]
 - Version [e.g. 2.7]

**Additional context**

**Comment by L1ghtn1ng** [comment]
That is due to google being removed as it was getting blocked
