### ISSUE TITLE
error line 748 and 476

### ISSUE THREAD

**Issue by emce69** [laramies/theHarvester#139]
Traceback (most recent call last):
  File "theHarvester.py", **line 748,** in <module>
    start(sys.argv[1:])
  File "theHarvester.py", **line 476**, in start
    if (len(all_ip) == 0):
UnboundLocalError: local variable 'all_ip' referenced before assignment
None

**Comment by NotoriousRebel** [comment]
How did you run it? Also, is it up to date?

**Comment by emce69** [comment]
I run it in python3 in kali linux distro . And yes it is up to date.

**Comment by NotoriousRebel** [comment]
@emce69 how did you run the tool? 
For example did you do something like 
```python3 theHarvester.py -d acme.com -b all```

**Comment by emce69** [comment]
dude its working now, I have type error. Anyway thanks dude :)
