### ISSUE TITLE
Typographical Error in theHarvester code.

### ISSUE THREAD

**Issue by HrtfdJetpack06120** [laramies/theHarvester#1398]
I finally, as I am teaching myself linux and basic coding, was abl to get python to run setup.py. However, if finished with an module error and didnt work. I should have screen shot  it for you. I attached a shot of the follow up search for the module, and that ought to be explanatory enough to see why I think it's a typo in the code.
The module that's producing the error was called aiodus, I believe that it should be AIOBUS (emphasis mine). 
![Screenshot_20230425-230305-283](https://user-images.githubusercontent.com/64813587/234460798-b4bb6b3a-4106-433a-aa18-1adb00f31846.png)

**Comment by L1ghtn1ng** [comment]
Can you post a screenshot of the error message that you are getting please?

**Comment by L1ghtn1ng** [comment]
we have no module named that in our requirements, the closes thing to that is aiodns, not sure what is going on your side unfortunately
