### ISSUE TITLE
[Feature Request] Separate EMAIL and SUBDOMAIN of the theHarvester

### ISSUE THREAD

**Issue by TerickJojo** [laramies/theHarvester#1412]
As the title suggests, for example, the subdomain collection would cost a lot of time when I only need the function of email collection.

It would be better to leave the choice to us.

Thanks so much.

**Comment by L1ghtn1ng** [comment]
You do have that ability, already just pick the sources that do email only for example intelx and rocketreach you just create a comma sperated list of sources to use ☺️

On 6 May 2023, at 11:57, TerickJojo ***@***.***> wrote:

﻿

As the title suggests, for example, the subdomain collection would cost a lot of time when I only need the function of email collection.

It would be better to leave the choice to us.

Thanks so much.
