### ISSUE TITLE
Make the min py version 3.6

### ISSUE THREAD

**Issue by L1ghtn1ng** [laramies/theHarvester#142]
I would like to propose that we remove all python2 support and have python3.6 as the minimum supported python version due to having static type checking which will help improve the code base a lot and and f-string support. As python2 is EOL in 2020.

**Comment by NotoriousRebel** [comment]
That sounds great and would bring code readability to another level. 
However, people are stubborn and refuse to change, until python2 has reached EOL it
should be supported. As people still use it with python2 and introducing type checking
would break backwards compatibility.

**Comment by L1ghtn1ng** [comment]
I understand but I think if they really want to use this tool then they should be able to use a virtualenv to get it running ??

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by L1ghtn1ng** [comment]
I am just really a big fan of using newer features, and not wanting to wait around when it will make a massive difference. As I think using the requests html library would really help us out but that needs py3.6 minimum

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by L1ghtn1ng** [comment]
What would also help with readability of the code 8s not having ```for X in foo``` variables/classes/functions/methods should always be called what the are doing. I have just made sure from day one of me learning python to follow certain style peps and keep code clean.
________________________________

**Comment by L1ghtn1ng** [comment]
That is meant to be is not 8s, guess that happens when you type on a phone that likes to autocorrect you
________________________________

**Comment by leebaird** [comment]
Kali Linux is running Python 3.6.8rc1.

**Comment by NotoriousRebel** [comment]
As this has been implemented, closing!
