### ISSUE TITLE
Bug - No module names 'theHarvester

### ISSUE THREAD

**Issue by ZerkerEOD** [laramies/theHarvester#1424]
**Feature Request or Bug or Another**
 Bug 

**Describe the feature request or bug or other**
A clear and concise description of what the bug, feature request,
or other request is.

I am getting the following error when I try to run theHarvester:
```
theharvester -h                                                                                                           ✔  18s  
Traceback (most recent call last):
  File "/usr/bin/theharvester", line 5, in <module>
    from theHarvester import __main__
ModuleNotFoundError: No module named 'theHarvester'
```

If I run pip install theHarvester or pip3 install theHarvester I am told that the requirement is already met.

I am using pyenv and I have never had this type of issue but it appears that all dependencies are met. 

I am running on Manjaro and installed theHarvester through the Blackarch repo.

I also tried to reinstall theHarvester and it does the same.

**To Reproduce**
Steps to reproduce the behaviour:
No steps needed, running the tool at all causes the same error.

**Expected behaviour**
Expectation is that it runs like normal

**Screenshots**
If possible please add screenshots to help explain your problem.
![image](https://github.com/laramies/theHarvester/assets/26573385/abbe2d9f-8510-471b-b4a4-f3a1fcf809a1)

**System Information (System that tool is running on):**
 - OS: Manjaro - using Blackarch repo
 - Version 3231.caf21cb-1 - Build date Friday May 5 2023

**Additional context**
Nothing additional to say except I altered the script to use /usr/bin/env python but I was getting the error before and after.

**Comment by NotoriousRebel** [comment]
Did you have the same error if you installed the tool via a git clone?

**Comment by L1ghtn1ng** [comment]
timeout
