### ISSUE TITLE
[Bug] crtsh.py, bad "%25"

### ISSUE THREAD

**Issue by nfwprod** [laramies/theHarvester#1442]
**Feature Request or Bug or Another**
Bug

**Describe the feature request or bug or other**
"-b crtsh" got following error.

'''
An exception has occurred: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://crt.sh/?q=%25.example.net&output=json')
'''
I deleted the "%25" from crtsh.py, and theHarvester worked well.

Please check line 15 of crtsh.py.
https://github.com/laramies/theHarvester/blob/56b3b2de7dc080264766897124d6ebf548e09ad4/theHarvester/discovery/crtsh.py#L4

**Comment by nfwprod** [comment]
I'm sorry, I could get result with %25.
crt.sh often returns error page for ambiguous search with large returns, so I confused that the error was caused by %25.

**Comment by NotoriousRebel** [comment]
Do you have an example of crt.sh returning an error page for an ambigous search with large returns?

**Comment by nfwprod** [comment]
Sorry, the target domain is my companies domain, so I can't share it.
It returns about 1,000 lines. (The domain has many certs with many sub domains).

**Comment by NotoriousRebel** [comment]
You don't need to share anything I was able to trigger the error with a domain like `apple.com`, I am not happy with how limited the results have become so if this error occurs in the future may just end up crawling the site to get results.

**Comment by L1ghtn1ng** [comment]
Going to close this but was not apple to trigger the issue with my multiple runs, So not sure what as going on at the time, but will keep an eye out
