### ISSUE TITLE
Invalid Source [theHarvester Tool]

### ISSUE THREAD

**Issue by Sid-142** [laramies/theHarvester#1453]
Can we add a source in theHarvester tool? 
Coz when I want to search in the source twitter its throwing me "**Invalid Source**".
`theHarvester -d mas.bg.ac.rs. -b twitter` giving me **Invalid Source** error.
Please help...

**Comment by NotoriousRebel** [comment]
Twitter was removed a source a while ago but may be added in the future again, you can go to an older version of the codebase and see how it was implemented and try it out.  Twitter API is also not what it was once
