### ISSUE TITLE
[Bug] Censys needs porting to the new api version

### ISSUE THREAD

**Issue by L1ghtn1ng** [laramies/theHarvester#1468]
@thehappydinoa You able to please update censys to the new api in theHarvester please?

**Comment by L1ghtn1ng** [comment]
> Sounds good, I will have some more time in mid August. Hope that timeframe works for you. 

Yeah all good, thank you ☺️

**Comment by leebaird** [comment]
Much appreciated.

**Comment by sh3ll4rpw** [comment]
Censys module is giving results. It's because if this issues? When you'll be able to solve it?

**Comment by L1ghtn1ng** [comment]
Yeah it will be down to this issue

On 1 Oct 2023, at 20:06, sh3ll4rpw ***@***.***> wrote:

﻿

Censys module is giving results. It's because if this issues? When you'll be able to solve it?

**Comment by thehappydinoa** [comment]
Hey still on my todo list, sorry for the delay!

**Comment by thehappydinoa** [comment]
@L1ghtn1ng just put up a PR #1556 let me know if that works, thanks!

**Comment by L1ghtn1ng** [comment]
Will have a look later today
