### ISSUE TITLE
[Bug|Feature Request|Other] Short Description of Issue

### ISSUE THREAD

**Issue by SmolAgeDev** [laramies/theHarvester#1477]
Bug 

After installing TheHarvester everytime i run it its gives ModuleNotFoundError. The way i fix this is using the following command in terminal.

`sudo apt install python3-<modulename>`

It worked until i got to the aiomultiprocess module.

I tried multiple ways.
-python3-aiomultiprocess: 
> Unable to locate package python3-aiomultiproccess

When i used pip3 install aiomultiprocess it said it installed but it still gave me the same error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tool like this: sudo python3 ./theHarvester.py
2. Error: ModuleNotFoundError: No module named 'aiomultiprocess'

**Expected behaviour**
Normally, it should detect aiomultiprocess module. But it doesn't, i even used pip instead of pip3 and said the module was installed

**System Information (System that tool is running on):**
 - OS: [Pop!_Os]
 - Version [22.04 LTS x86_64]

**Comment by NotoriousRebel** [comment]
Are you able to provide a stacktrace? I have never tried apt installing it but if you create a virtualenv and then use that and do `python3 -m pip install -r requirements.txt` from within the virualenv should work.
