### ISSUE TITLE
[Other] Method `chunk_size` typing and usage mismatch.

### ISSUE THREAD

**Issue by yoonthegoon** [laramies/theHarvester#1486]
While addressing #1383, I came across this.

Typing on method [chunk_list](https://github.com/laramies/theHarvester/blob/master/theHarvester/screenshot/screenshot.py#L47) suggests parameter `items` is type `Sized`.
```py
@staticmethod
def chunk_list(items: Sized, chunk_size):
    # Based off of: https://github.com/apache/incubator-sdap-ingester
    return [items[i:i + chunk_size] for i in range(0, len(items), chunk_size)]
```
However, `Sized` is not indexable.
It's used in [\_\_main\_\_.py](https://github.com/laramies/theHarvester/blob/master/theHarvester/__main__.py#L898) where `items = unique_resolved_domains` where `unique_resolved_domains` is sometimes a `list` and sometimes a `set`.

In the case of `unique_resolved_domains` being a `set`, the method should fail as `'set' object is not subscriptable`.

I would imagine the appropriate type hinting for `chunk_size`'s `items` parameter would be `Sequence`.
I also imagine it's best to be consistent with the typing of `unique_resolved_domains` and make each instance of its declaration a `list` or `tuple`.

I will make the changes as I see fit in resolving #1383 but want to document this conflict.

**Comment by L1ghtn1ng** [comment]
Yeah it needs to be consistent so thanks for that, much appreciated for the work in you tackling this ☺️

On 24 Jul 2023, at 00:11, yoon ***@***.***> wrote:

﻿

While addressing #1383<https://github.com/laramies/theHarvester/issues/1383>, I came across this.

Typing on method chunk_list<https://github.com/laramies/theHarvester/blob/master/theHarvester/screenshot/screenshot.py#L47> suggests parameter items is type Sized.

@staticmethod
def chunk_list(items: Sized, chunk_size):
    # Based off of: https://github.com/apache/incubator-sdap-ingester
    return [items[i:i + chunk_size] for i in range(0, len(items), chunk_size)]

However, Sized is not indexable.
It's used in __main__.py<https://github.com/laramies/theHarvester/blob/master/theHarvester/__main__.py#L898> where items = unique_resolved_domains where unique_resolved_domains is sometimes a list and sometimes a set.

In the case of unique_resolved_domains being a set, the method should fail as 'set' object is not subscriptable.

I would imagine the appropriate type hinting for chunk_size's items parameter would be Sequence.
I also imagine it's best to be consistent with the typing of unique_resolved_domains and make each instance of its declaration a list or tuple.

I will make the changes as I see fit in resolving #1383<https://github.com/laramies/theHarvester/issues/1383> but want to document this conflict.

**Comment by yoonthegoon** [comment]
I think I could also make the type of `items` a `Collection` so that it would still be applicable to both `set` and `list`. 
I would just have to modify the method to perform the logic on `list(items)`.
