### ISSUE TITLE
Errors when building docker image 

### ISSUE THREAD

**Issue by ibmchas** [laramies/theHarvester#1491]
## Note we do not support installing theHarvester on android

**Describe the bug**
Using Docker CE
```
Client: Docker Engine - Community
 Version:           24.0.4
 API version:       1.43
 Go version:        go1.20.5
 Git commit:        3713ee1eea
 Built:             Fri Jun 30 17:55:44 2023
 OS/Arch:           darwin/arm64
```
Running `docker build -t theharvester .` throws the following error during the build process 
```
Failed to build cffi
ERROR: Could not build wheels for cffi, which is required to install pyproject.toml-based projects
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Following instructions - [installation](https://github.com/laramies/theHarvester/wiki/Installation#option-3---docker)
2. Docker build fails with the following error 
```
  Building wheel for cffi (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  × Building wheel for cffi (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      /usr/lib/gcc/aarch64-alpine-linux-musl/12.2.1/../../../../aarch64-alpine-linux-musl/bin/ld: cannot find Scrt1.o: No such file or directory
      /usr/lib/gcc/aarch64-alpine-linux-musl/12.2.1/../../../../aarch64-alpine-linux-musl/bin/ld: cannot find crti.o: No such file or directory
      /usr/lib/gcc/aarch64-alpine-linux-musl/12.2.1/../../../../aarch64-alpine-linux-musl/bin/ld: cannot find -lssp_nonshared: No such file or directory
      collect2: error: ld returned 1 exit status
      Note: will not use '__sync_synchronize()' in the C code
      ***** The above error message can be safely ignored.

      /tmp/pip-build-env-h6xkgiir/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
```

**Expected behaviour**
Produce a working image.

**Screenshots**
N/A

**System Information (System that tool is running on):**
 - OS: [macOS - Apple M1 Pro]
 - Version [13.4.1]

**Comment by L1ghtn1ng** [comment]
Can you do a git pull please and try again

**Comment by ibmchas** [comment]
I did and it still fails :(

**Comment by NotoriousRebel** [comment]
I will take a look sometime soon. After removing docker cache, try modifying the following line: `RUN apk update && apk upgrade --available && apk add git libffi-dev gcc python3-dev py-pip libxml2-dev libxslt-dev && python3 -m pip install --upgrade pip` replace `py-pip` with `py3-pip`.  And before that line put this in the Dockerfile: `apk add --no-cache musl-dev` As for the reason read [this](https://github.com/ocaml/opam-repository/issues/13718). If this still does not work provide the stacktrace as it should be a different error if it fails.

**Comment by ibmchas** [comment]
Awesome that did it 🥇 
```
Successfully built f321e482fbd4
Successfully tagged theharvester:latest
```
