### ISSUE TITLE
[Workflow] Add black and isort formatting to repo

### ISSUE THREAD

**Issue by yoonthegoon** [laramies/theHarvester#1492]
## Description

Add black and isort formatting to the repository.
Improves code quality, readability, and maintain consistent formatting.
In recently working to clear all MyPy issues, the code style was noticeably inconsistent among even separate methods. 
Problem with not having this from the start is this change will basically put all the git blame on the formatter.
So for transparency, the revisions made for this will be put in `.git-blame-ignore-revs`.

I can get started with this when I've got time this week, or this can be closed as not planned.

**Comment by yoonthegoon** [comment]
Or if anyone else wants to pick this up first, it's a good first issue.

**Comment by L1ghtn1ng** [comment]
Sounds good to me on this, the only thing that bugs me with how black works is it likes to change single quotes for double quotes but other than that all for it

On 25 Jul 2023, at 20:39, yoon ***@***.***> wrote:

﻿

Or if anyone else wants to pick this up first, it's a good first issue.

**Comment by yoonthegoon** [comment]
Yeah i feel you with the quotes. I've just gotten used to letting it change them for me; I'm still way more comfy writing with single but reading with double now.
