### ISSUE TITLE
Replace `import *` with explicit imports

### ISSUE THREAD

**Issue by yoonthegoon** [laramies/theHarvester#1497]
`import *` can:

1. litter the namespace with unused names,
2. bring in unseen namespace collisions,
3. cause confusion as to where classes and functions come from,
4. ruin your marriage,
5. and so much more

tasks:

- [x] replace all `import *` instances with explicit imports

that's it

Also on #1494 I added the commit from my fork to `.git-blame-ignore-revs`, so that file is currently ignoring nothing.
<img width="1512" alt="image" src="https://github.com/laramies/theHarvester/assets/71526721/efa8f49e-7cd1-483b-b6fe-9f304da5d864">

- [x] modify `.git-blame-ignore-revs` to include actual merged format commit

**Comment by yoonthegoon** [comment]
```
❯ black . && isort . && flake8 --config .flake8 theHarvester && mypy --pretty theHarvester/*/*.py
All done! ✨ 🍰 ✨
67 files left unchanged.
Skipped 3 files
Success: no issues found in 51 source files
```
🥲

**Comment by yoonthegoon** [comment]
[Externalize code repetition to method](https://github.com/yoonthegoon/theHarvester/commit/386399aaef412f7182d3ab9d66cbca4052bd378c#diff-e026ff479beedd53324b4e852f868c2a3ac337d2185a49c4346168cb0f472079R78)
I do not understand how these filters are supposed to work and how the tests and linters didn't catch this until now (unless I *really* don't understand).
`filter` takes two arguments, a callable and an iterable in that order.
It's only taking one argument here, and it's a method already being called.
Looking at the return type of many of the search engines' `get_hostnames` methods, they return lists.

**Comment by L1ghtn1ng** [comment]
The look at store() as that is what the filters are fore, as before it we had to do more than than a 1 liner for modules if that makes sense, I know before this pycharm would complain about duplicated code.

**Comment by yoonthegoon** [comment]
Yeah but I'm not too concerned about the repeated code. I just can't get home `filter` is only taking one argument. Even if the return type of the argument it's taking isn't just a `list` and is `tuple[callable, iterable]`, it's not being unpacked so it still shouldn't work. This is gonna be a big and boring process, but maybe coverage reports should be brought in and a goal to at least cover everything should be set.

**Comment by L1ghtn1ng** [comment]
Think it allows staging, but then it gets unpacked further down that is why it works, or the contributor stumbled on a undocumented way that it still behaves correctly that is all I can think of

On 28 Jul 2023, at 14:06, yoon ***@***.***> wrote:

﻿

Yeah but I'm not too concerned about the repeated code. I just can't get home filter is only taking one argument. Even if the return type of the argument it's taking isn't just a list and is tuple[callable, iterable], it's not being unpacked so it still shouldn't work. This is gonna be a big and boring process, but maybe coverage reports should be brought in and a goal to at least cover everything should be set.
