### ISSUE TITLE
Error in the execution of theHarvester 

### ISSUE THREAD

**Issue by ahadfarajpour** [laramies/theHarvester#1512]
When I run the theHarvester  tool, I get the following error. Please tell me where my problem is
```py
python3 theHarvester.py -h
```

**Screenshots**
![Screenshot from 2023-08-09 18-23-57](https://github.com/laramies/theHarvester/assets/86210481/10849212-3a38-4f7b-a061-f56f862162b1)

**System Information (System that tool is running on):**
 - OS: [ubuntu ]
 - Version [20.4]
 - Version pip [23.2.1]
 - Version python3 [3.8.10]

**Comment by L1ghtn1ng** [comment]
You need to use python 3.9 on Ubuntu 20.04 you can apt install it as it’s in the repository, also use a virtualenv as well to protect the OS python versions of the libraries that it uses and you will be good

On 9 Aug 2023, at 16:01, lostrobot ***@***.***> wrote:

﻿

When I run the theHarvester tool, I get the following error. Please tell me where my problem is

python3 theHarvester.py -h

Screenshots
[Screenshot from 2023-08-09 18-23-57]<https://user-images.githubusercontent.com/86210481/259451460-10849212-3a38-4f7b-a061-f56f862162b1.png>

System Information (System that tool is running on):

  *   OS: [ubuntu ]
  *   Version [20.4]
  *   Version pip [23.2.1]
  *   Version python3 [3.8.10]

**Comment by ahadfarajpour** [comment]
I installed Python 3.9 and after running the tool, I got the following error
```
python3.9 theHarvester.py -h       
Traceback (most recent call last):
File "/root/tools/theHarvester/theHarvester.py", line 6, in <module>
from theHarvester import __main__
File "/root/tools/theHarvester/theHarvester/__main__.py", line 12, in <module>
import netaddr
ModuleNotFoundError: No module named 'netaddr'
```

**Comment by L1ghtn1ng** [comment]
Apt install python3-netaddr

On 9 Aug 2023, at 22:28, lostrobot ***@***.***> wrote:

﻿

I installed Python 3.9 and after running the tool, I got the following error

python3.9 theHarvester.py -h
Traceback (most recent call last):
File "/root/tools/theHarvester/theHarvester.py", line 6, in <module>
from theHarvester import __main__
File "/root/tools/theHarvester/theHarvester/__main__.py", line 12, in <module>
import netaddr
ModuleNotFoundError: No module named 'netaddr'

**Comment by ahadfarajpour** [comment]
Thank you very much, the problem is solved
