### ISSUE TITLE
theharvester 4.4.2 build failure

### ISSUE THREAD

**Issue by chenrui333** [laramies/theHarvester#1516]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  ==> /home/linuxbrew/.linuxbrew/Cellar/theharvester/4.4.2/bin/theharvester -d brew.sh --limit 1 --source urlscan 2>&1
  Traceback (most recent call last):
    File "/home/linuxbrew/.linuxbrew/Cellar/theharvester/4.4.2/bin/theharvester", line 6, in <module>
      from theHarvester import __main__
    File "/home/linuxbrew/.linuxbrew/Cellar/theharvester/4.4.2/libexec/lib/python3.11/site-packages/theHarvester/__main__.py", line 60, in <module>
      from theHarvester.screenshot.screenshot import ScreenShotter
  ModuleNotFoundError: No module named 'theHarvester.screenshot'
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/5843843645/job/15846375092?pr=139394
relates to Homebrew/homebrew-core#139394

**Comment by branchvincent** [comment]
just need a `theHarvester/screenshot/__init__.py` file for [`setuptools.find_packages`](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#custom-discovery) to pick it up

**Comment by L1ghtn1ng** [comment]
added the fix in git, thanks for that :+1:
