### ISSUE TITLE
censys broke

### ISSUE THREAD

**Issue by leebaird** [laramies/theHarvester#154]
[*] Searching Censys.
Error occurred in the Censys module IP search: page parser: list index out of range
Error occurred in the main Censys module: '<=' not supported between instances of 'NoneType' and 'int'

**Comment by L1ghtn1ng** [comment]
I would say that we should just move to there python lib than role our own. This should stop issues like this as we have done that with shodan

**Comment by leebaird** [comment]
I totally agree.

**Comment by laramies** [comment]
Plugin working.
