### ISSUE TITLE
Stucked!!!

### ISSUE THREAD

**Issue by anony1234567890** [laramies/theHarvester#1546]
I am using theharvester but at the end like as mentioned in attached screenshot theharvester got stucked. 
![Screenshot 2023-09-25 133040](https://github.com/laramies/theHarvester/assets/145902869/9da8a354-cfd5-4128-8d5f-ef74f41d30e2)

**Comment by NotoriousRebel** [comment]
What version of the tool are you using? You are also not showing how it is being run, worse comes to worse you can always pull the results from the sqlite3 DB (#449) as that is written to as results are found vs the output files at the very end with the aggregated results.

**Comment by L1ghtn1ng** [comment]
TimeOut
