### ISSUE TITLE
duckduckgo broke

### ISSUE THREAD

**Issue by leebaird** [laramies/theHarvester#155]
python3 theHarvester.py -d cnn.com -l 100 -b duckduckgo

Exception occurred: list index out of range
Traceback (most recent call last):
  File "/theHarvester/discovery/duckduckgosearch.py", line 54, in crawl
    val = val[0]  # First value should be dict.
IndexError: list index out of range
None

**Comment by NotoriousRebel** [comment]
As this has been resolved, closing!
