### ISSUE TITLE
print(f'...') issue with possible substitution attempt

### ISSUE THREAD

**Issue by weaknetlabs** [laramies/theHarvester#158]
Hello, the code is a mess now. It looks like there was a  global substitution attempt withe the "print" statements and they turned out as "print(f'foo bar');" I can' seem to figure out a use case in which this would have happened. ?

For instance in discover/censys.py:

```
        except Exception as e:
            print(f'Error occurred in the Censys module downloading pages from Censys - IP search: + {e}')
```

I ran through the code and cleaned it all up (many files are like this) by just removing the "f" portion and it seems to be running OK. 

Just an FYI.

**Comment by NotoriousRebel** [comment]
@weaknetlabs Those are fstrings which is a new feature introduced in python3.6 they are faster than using  .format, % format, and concatenating with a +. Their purpose is to format strings better; however, that means that the tool does not support python 2 anymore. Which is fine as python2 is going EOL soon.

**Comment by weaknetlabs** [comment]
@NotoriousRebel Thank you for the help. I am a newbie Python user. I have a lot of infosec tools in my distros that use one or the other and unfortunately I have to keep both python2 and python3 to get the best (most useful at least) experience to my users. Next time, I'll know because of your advice and help. 

Thank you again.
~Douglas
