### ISSUE TITLE
Allow specifying custom wordlists directory

### ISSUE THREAD

**Issue by wzulfikar** [laramies/theHarvester#160]
I was running `theHarvester` from outside of repo directory and realized that it'll yield unexpected result because it couldn't find `wordlists/` directory. This is because theHarvester use `wordlists/` directory relative to where the repo is cloned (ie. `~/code/github/theHarvester/wordlists/`). 

What could possibly go wrong if we allow user to specify custom wordlists directory? 
For now, what I did for my case is i forked the repo and adjust the codes so that i can specify custom wordlists directory from environment variable `WORDLISTS_DIR` (commit diff: https://github.com/wzulfikar/theHarvester/commit/1e9438191f1bd0b68b7b8bad4fa52daafffca73e)

More context: I run `theHarvester` via a wrapper "[harvest](https://github.com/wzulfikar/lab/blob/master/bash/harvest)" that I put in my path. This way, i can run it from anywhere. Example:

```
$ ~ → cd ~/my-workspace
$ ~/my-workspace → harvest -d example.com -l 10 -g -b duckduckgo -f output.html
```

If this can be added as feature, I will send a PR. Thanks for this awesome tool btw :)

**Comment by NotoriousRebel** [comment]
We are currently making the switch from getopt to argparser to make arg parsing easier, this is something that could be implemented.

**Comment by wzulfikar** [comment]
I see. Guess I'll close the ticket and use the forked version for now, while waiting for the switch. Thanks!
