### ISSUE TITLE
Error & others

### ISSUE THREAD

**Issue by cidz-lab** [laramies/theHarvester#1633]
☆ error:
 Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]

☆ note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.

☆SetuptoolsWarning: `install_requires` overwritten in `pyproject.toml` (dependencies)

☆ note: This error originates from a subprocess, and is likely not a problem with pip.
~/theHarvester $ pip install --upgrade pip
ERROR: Installing pip is forbidden, this will break the python-pip package (termux).

I'm new on termux
Please help,
Thanks

**Comment by L1ghtn1ng** [comment]
You need to use pipx to setup theHarvester but we do not support termux officially.

On 12 Jan 2024, at 00:25, CidzZ ***@***.***> wrote:

﻿

☆ error:
Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> [60 lines of output]

☆ note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.

☆SetuptoolsWarning: install_requires overwritten in pyproject.toml (dependencies)

☆ note: This error originates from a subprocess, and is likely not a problem with pip.
~/theHarvester $ pip install --upgrade pip
ERROR: Installing pip is forbidden, this will break the python-pip package (termux).

I'm new on termux
Please help,
Thanks

**Comment by cidz-lab** [comment]
Ok

Thank you for the reply

Pada Jum, 12 Jan 2024 11:48, J.Townsend ***@***.***> menulis:

> You need to use pipx to setup theHarvester but we do not support termux
> officially.
>
