### ISSUE TITLE
Read proxies.yaml from /etc/theHarvester/proxies.yaml

### ISSUE THREAD

**Issue by Seedorf84** [laramies/theHarvester#1638]
I have a problem, when a try to launch the tool, he don't found any Ip, emails or hosts and i have a message "Read proxies.yaml from /etc/theHarvester/proxies.yaml".

When i open this file, i can see that.

![PrtScr capture_32](https://github.com/laramies/theHarvester/assets/141363956/ec52f75f-80c5-4757-952f-e47970695d66)

Could someone tell me if he ever had this problem and how he solved it? 

Thanks

**Comment by L1ghtn1ng** [comment]
Are you trying to use a proxy? if so you need to put the details in it. If not see the help output with the -h flag

**Comment by Seedorf84** [comment]
ok I found the problem we can no longer search with google, that’s what blocked me.

Thanks for your help

**Comment by L1ghtn1ng** [comment]
Yeah I newer versions Google has been removed so that does not happen, I recommend you upgrade for fixes and enhancements etc.

On 23 Jan 2024, at 15:54, Seedorf84 ***@***.***> wrote:

﻿

ok I found the problem we can no longer search with google, that’s what blocked me.

Thanks for your help

**Comment by Mrtknr** [comment]
I have the same problem. How did you do it?

**Comment by Mrtknr** [comment]
can you please explain

**Comment by L1ghtn1ng** [comment]
Make sure you are using the latest version of the tool and set the yaml syntax correctly

**Comment by Mrtknr** [comment]
How can I set yaml syntax?

**Comment by L1ghtn1ng** [comment]
Where it says ip change that and same goes for the port but leave everything else the same. Then you should be good, I recommend learning about yaml as lists of things these days are using yaml for configs etc. good to have that in your toolbox.

On 3 May 2024, at 07:28, Mrtknr ***@***.***> wrote:

﻿

How can I set yaml syntax?

**Comment by Mrtknr** [comment]
Thank you.I will try this
