### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by evantoday** [laramies/theHarvester#164]
python3 theHarvester.py -d acme.com -b all
  File "theHarvester.py", line 84
    print(f'\033[94m[*] Target: {word} \n \033[0m')
                                                 ^
SyntaxError: invalid syntax

**Comment by NotoriousRebel** [comment]
The reason why this is happening is that the print statement is using an fstring (new feature added in python3.5) to make string formatting easier and faster. However, this means that the tool no longer works with Python2. Try running with python3 and the tool should work.

**Comment by evantoday** [comment]
thanks brother i'll close this
