### ISSUE TITLE
how to do?

### ISSUE THREAD

**Issue by pzlee** [laramies/theHarvester#165]
![image](https://user-images.githubusercontent.com/17840800/51725143-ad3d3480-209b-11e9-8175-eeb887926592.png)

**Comment by leebaird** [comment]
What is your question?

**Comment by pzlee** [comment]
I can't find this config file.where

**Comment by NotoriousRebel** [comment]
when you clone the repo it should be in the directory theHarvester

**Comment by pzlee** [comment]
thanks!
![image](https://user-images.githubusercontent.com/17840800/51783462-10e76080-2175-11e9-9451-ce2e668bc398.png)

**Comment by L1ghtn1ng** [comment]
@pzlee This version is not in kali yet as we have not done a github tagged release yet, for the time being you will need to add your keys to constants.py

**Comment by L1ghtn1ng** [comment]
@pzlee or do a git clone
