### ISSUE TITLE
Shodan Module Not Found

### ISSUE THREAD

**Issue by Grey-Hat86** [laramies/theHarvester#166]
After cloning the latest version into Kali, I am faced with the following error when running theharvester.py without arguments.

Traceback (most recent call last):
  File "./theHarvester.py", line 3, in <module>
    from discovery import *
  File "/opt/theHarvester/discovery/shodansearch.py", line 3, in <module>
    from shodan import exception
ModuleNotFoundError: No module named 'shodan'

I've had a look around and I am unable to resolve it. Appreciate the help.

Cheers

**Comment by NotoriousRebel** [comment]
After you cloned the tool did you do ```python3 -m pip install -r requirements.txt```

**Comment by Grey-Hat86** [comment]
@NotoriousRebel Thanks very much Matt, completely missed that one. This has done the trick.
