### ISSUE TITLE
No email results

### ISSUE THREAD

**Issue by greenchili** [laramies/theHarvester#167]
Version: 3.0.6 v213
Python: 3.6.7

I have found that I regularly get no email results from pages that have emails in plain text. Here are a couple of random examples:

./theHarvester.py -d dorsethomechoice.org -l 100 -b google
./theHarvester.py -d pembrokefinearms.co.uk -l 100 -b google

However the following examples do work:

./theHarvester.py -d edge-security.com -l 100 -b google
./theHarvester.py -d kali.org -l 100 -b google

Could it be being blocked for some reason ie user-agent etc?

**Comment by L1ghtn1ng** [comment]
@greenchili Google will block your IP for a bit if you make to many requests in one go, try using duckduckgo as the source and see what you get and you will want to do a git pull as well
