### ISSUE TITLE
lease add screenshots to help explain your problem.  **System Information (System that tool is running on):**  - OS: [e.g. Windows10]  - Version [e.g. 2.7]  **Additional context** Add any other context about the problem here.[Bug|Feature Request|Other] Short Description of Issue

### ISSUE THREAD

**Issue by Dan231133** [laramies/theHarvester#1701]
got problem
traceback (most recent call list)
theHarvester.py line 4
__main__.py line 16
bevigil.py line 1
constants.py line 71
async def google workaround(visit_url: str) -> bool l str:
typeError:unsupoorted operand types(s) for l 'type' and 'type'

**Comment by L1ghtn1ng** [comment]
That looks to be an old version of the tool as I have not been able to reproduce the issue
