### ISSUE TITLE
[Bug|Feature Request|Other] I'm unable to run theHarvester on my parrot vm ,my main machine is Mac air m1. And everything goes fine until and unless I'm started doing cehv12 labs on it. Kindly help as I'm preparing my cel v12 practical cert without labs

### ISSUE THREAD

**Issue by techandro** [laramies/theHarvester#1732]
## Note we do not support installing theHarvester on android

**Feature Request or Bug or Another**
Feature Request | Bug | Other

**Describe the feature request or bug or other**
A clear and concise description of what the bug, feature request,
or other request is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tool like this: '...'
2. See error

**Expected behaviour**

**Screenshots**
If possible please add screenshots to help explain your problem.

**System Information (System that tool is running on):**
 - OS: [e.g. Windows10]
 - Version [e.g. 2.7]

**Additional context**

**Comment by techandro** [comment]
![Screenshot 2024-05-17 at 8 32 38 PM](https://github.com/laramies/theHarvester/assets/32603675/923e8a44-56d5-4357-9166-1f25fa4dd830)
![Screenshot 2024-05-17 at 8 32 38 PM](https://github.com/laramies/theHarvester/assets/32603675/e48d76eb-5c01-461b-85cc-ee28b0e7053d)

**Comment by techandro** [comment]
I'm attaching the screenshot of the error. Kindly suggest me how to solve this issue. @L1ghtn1ng ,I read a solution of yours to comment the 2 lines in harvester.py executable file but I'm not sure how to do that. Means that file is readable only. Can you help me in solving this this issue. I'm preparing for my CEH v12 labs .Below is the screenshot.                                                    
![Screenshot 2024-05-17 at 8 32 38 PM](https://github.com/laramies/theHarvester/assets/32603675/f0cfe415-ea25-409c-90be-6ea80a53ad8c)

**Comment by L1ghtn1ng** [comment]
That version of theHarvester is out of date and is missing a tone of bugfixes, if you do not have an up to date parrot vm, update the vm and that will fix it for you. Otherwise I suggest moving to a kali vm where it has the latest version of the tool and will run correctly.
