### ISSUE TITLE
[Bug] Brave module broken

### ISSUE THREAD

**Issue by leebaird** [laramies/theHarvester#1733]
## Note we do not support installing theHarvester on android

**Feature Request or Bug or Another**
Bug

**Describe the feature request or bug or other**
The Brave module is broken.

**To Reproduce**
Steps to reproduce the behaviour:
/opt/theHarvester/theHarvester.py -d target.com -b brave

```
An exception has occurred: 0, message='', url=URL('https://search.brave.com/search?q=%22target.com%22&offset=0&source=web&show_local=0&spellcheck=0')
```

**System Information (System that tool is running on):**
 - OS: Kali Linux
 - Version: rolling

**Additional context**
Have tried with multiple domains.

**Comment by Mengter8** [comment]
I also encountered this, and the loop output "An exception has occurred: 400, message:
Can not decode content-encoding: br"

**Comment by L1ghtn1ng** [comment]
Works fine for me

**Comment by mayi3d** [comment]
> I also encountered this, and the loop output "An exception has occurred: 400, message:我也遇到了这种情况，循环输出 “An exception has occurred： 400， message： Can not decode content-encoding: br"无法解码内容编码：br”

这个问题解决了吗?

**Comment by Mengter8** [comment]
> > I also encountered this, and the loop output "An exception has occurred: 400, message:我也遇到了这种情况，循环输出 “An exception has occurred： 400， message： Can not decode content-encoding: br"无法解码内容编码：br”我也遇到了这个，循环输出 “An exception has occurred： 400， message：我也遇到了这种情况，循环输出 ”An exception has occurred： 400， message： Can not decode content-encoding： br“无法解码内容编码：br”
> 
> 这个问题解决了吗?

subfinder维护的更好

**Comment by mayi3d** [comment]
虽然报错,但是吧,也能扫到,我试试另一个

Mengter8 ***@***.***> 于2024年10月31日周四 09:22写道：
