### ISSUE TITLE
Bing search with at symbol

### ISSUE THREAD

**Issue by YuriyPobezhymov** [laramies/theHarvester#177]
Hello.
I found that theHarvester tool uses such requests to retrieve domain info through bing: '@domain.com'.
It's doesn't find anything for my researches. But I found that for google search it uses such search: '@"domain.com"'. I tried to modify bing search - and yes it shows me much bigger search result.

What do you thinking about? May we can improve that.

**Comment by YuriyPobezhymov** [comment]
Ok.

**Comment by L1ghtn1ng** [comment]
This has been fixed in master
