### ISSUE TITLE
Incorrect Error Messages for API Keys

### ISSUE THREAD

**Issue by UncleRaymondo** [laramies/theHarvester#179]
Hi,

This is v3.0.6 running on Kali 2019.1

Seems like the error message from huntersearch.py is duplicated in googleCSE.py with respect to the API Key (self.key == "") so you can't really tell which one is causing an issue.

Not sure if this has been repeated in the other files :)

Cheers,
Ray

**Comment by UncleRaymondo** [comment]
Correction - it looks like the URL in the error is correct, it just says Hunter Search Engine, so only Minor :)

**Comment by NotoriousRebel** [comment]
If you are using the latest version the error messages should be correct.
