### ISSUE TITLE
Problem in windows !

### ISSUE THREAD

**Issue by OsirisOsil** [laramies/theHarvester#180]
theHarvester\theHarvester.py", line 84
    print(f'\033[94m[*] Target: {word} \n \033[0m')
                                                 ^
SyntaxError: invalid syntax

what the f after print( doing there ?

**Comment by L1ghtn1ng** [comment]
Hi, that f is a new feature in py3.6 that are called f-strings. You need to make sure you have python3.6 installed and this will resolve your issue
________________________________

**Comment by OsirisOsil** [comment]
Ooh thanks I thought it still working on py2 :D am old I know :p

**Comment by L1ghtn1ng** [comment]
If you look at the readme on our GitHub page you will see it is py3.6 or higher
________________________________
