### ISSUE TITLE
theharvester gives invalid source issue

### ISSUE THREAD

**Issue by Noor242424** [laramies/theHarvester#1805]
## Note we do not support installing theHarvester on android

**Feature Request or Bug or Another**
Feature Request | Bug | Other

**Describe the feature request or bug or other**
A clear and concise description of what the bug, feature request,
or other request is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tool like this: '...'
2. See error

**Expected behaviour**

**Screenshots**
If possible please add screenshots to help explain your problem.

**System Information (System that tool is running on):**
 - OS: [e.g. Windows10]
 - Version [e.g. 2.7]

**Additional context**

**Comment by L1ghtn1ng** [comment]
If you are trying to use google then it is an invalid source as it got removed a while ago due to it always getting blocked, do theHarvester -h to see all the sources you can use.

**Comment by eggshell-coder** [comment]
when i try find information it says inavalid source 
theHarvester -d microsoft.com -l  200 -b linkedin.
is there any update related to this or alternative

**Comment by L1ghtn1ng** [comment]
It is correct there is no LinkedIn module as it got removed as it was based on Google and Google was blocking it so I removed it ages ago please see sources with the -h output
