### ISSUE TITLE
Better install process

### ISSUE THREAD

**Issue by cybergazer** [laramies/theHarvester#1862]
I've tried every way to install theHarvester and none of them landed in a successful install. Below is my experience. The docs followed were these: https://github.com/laramies/theHarvester/wiki/Installation 

- Option 1: Kali. It probably works, but you shouldn't have to spin up an entire VM just to use one tool

- Option 2: Virtualenv. I followed the instructions simply didn't work, it wouldn't launch saying I'm not on Python 3.10, but the weird thing is I am. I tried removing the check and it didn't run due to ImportError: /home/sinistra/Documents/Software/theHarvester/e/lib/pypy3.10/site-packages/uvloop/loop.pypy310-pp73-x86_64-linux-gnu.so: undefined symbol: PyContext_CopyCurrent

- Option 3 Docker. The 2nd most bloated way to install this. This did end up working, but there's a major issue, you can't get output files without accessing the machine and getting them. 

Can we have a simple binary. It would be nice to just do "pipx install theHarvester" and boom, done, or have a compiled binary in the releases.

**Comment by L1ghtn1ng** [comment]
As you are using the git version of theHarvester that actually requires python3.11, I have fixed the places where I have missed updating the docs and comments in the code, but I will update the wiki but for now to get you up and running as just tried your situation on a fresh Ubuntu VM, all you need to do if you are Ubuntu is apt install python3.11-venv which will pull in everything that is needed then you can do pipx install --python python3.11 . in the theHarvester git clone folder and you will be good after you then do pipx ensurepath

**Comment by L1ghtn1ng** [comment]
Wiki updated also
