### ISSUE TITLE
use asynchronous DNS request with ANY rather than A queries in hostchecker.py

### ISSUE THREAD

**Issue by philpraxis** [laramies/theHarvester#2]
For async DNS, you may use dnspython or twisted.
Both can be run in asynchronous request.
I found adns and asyncore dns based examples to be lacking "ANY" requests, which is precisely what is needed here.

note that your current code misses any non "A" resource record, that is any NS, MX, AAAA (ipv6), etc...

**Comment by NotoriousRebel** [comment]
As this is seven years old and DNS works properly, closing!
