### ISSUE TITLE
Cannot run on Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by BlueMan2903** [laramies/theHarvester#207]
Hi! 
When i try to run theHarvester i get the error:
  File "theHarvester.py", line 86
    print(f'\033[94m[*] Target: {word} \n \033[0m')
                                                                         ^
(the arrow is pointing to the ' after 0m)
SyntaxError: invalid syntax

Why does this happen?

**Comment by L1ghtn1ng** [comment]
Are you using python3.6?
________________________________

**Comment by BlueMan2903** [comment]
i have both installed.  I use the "python" command to run python 2.7 and "python3" to run python 3.6

**Comment by L1ghtn1ng** [comment]
you will get that error under py2 as theHarvester does not work with python 2 only py3.6+ and make sure you have got up to date version from git
________________________________

**Comment by BlueMan2903** [comment]
when i run it with python3.6 it cannod find the 'yaml' module

**Comment by L1ghtn1ng** [comment]
pip3 install --user -r requirements.txt will fix your issue
________________________________

**Comment by BlueMan2903** [comment]
so when i run "pip3 install --user -r requirements.txt" i get:

pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting beautifulsoup4>=4.7.1 (from -r requirements.txt (line 1))
  Could not fetch URL https://pypi.python.org/simple/beautifulsoup4/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
  Could not find a version that satisfies the requirement beautifulsoup4>=4.7.1 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for beautifulsoup4>=4.7.1 (from -r requirements.txt (line 1))

which i guess means that i dont have the required beautifulsoup version.
But when i do: pip3 install beautifulsoup4, i get: 

pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting beautifulsoup4
  Could not fetch URL https://pypi.python.org/simple/beautifulsoup4/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
  Could not find a version that satisfies the requirement beautifulsoup4 (from versions: )
No matching distribution found for beautifulsoup4

After some research I understood that the ssl module issue is caused by the pip3 version (which is 9.0.1), so i updated the packages and when i did sudo apt install python3-pip it tells me that python3-pip is already the newest version (9.0.1-2.3~ubuntu1).

**Comment by L1ghtn1ng** [comment]
I would recommend that you use a virtualenv or our dockerfile and then you can update pip and have all the modules that are needed and then it will work
________________________________

**Comment by BlueMan2903** [comment]
Fixed by updating python 3.6 to 3.7.1
Apparently pip3 version 9.0 was the latest version for python 3.6, but on python 3.7.1 it can be updated up to pip3 19.0.3, which then allowed to download all the packages on requirements.txt and run theHarvester.py
Thanks!!
