### ISSUE TITLE
Error occured with Shodan

### ISSUE THREAD

**Issue by BlueMan2903** [laramies/theHarvester#208]
When running theHarvester with Shodan I get: 
[*] Searching Shodan. 
	Searching for 13.79.239.33
[!] An error occurred with Shodan: [Errno 2] No such file or directory: 'api-keys.yaml'

**Comment by L1ghtn1ng** [comment]
Can you give me the the output of sudo updatedb && locate api-keys.yaml please
________________________________

**Comment by BlueMan2903** [comment]
/opt/theHarvester/trunk/api-keys.yaml

**Comment by L1ghtn1ng** [comment]
Yeah I see the problem, try putting it in the root folder and not a sub folder
________________________________

**Comment by BlueMan2903** [comment]
You talking about the whole "theHarvester" folder or only the yaml file?

**Comment by L1ghtn1ng** [comment]
Just the yaml file but generally you just want to clone it as is from
github

**Comment by darxboy** [comment]
I ve got this error while i wanna compile the program, can you give me the solution

Traceback (most recent call last):
  File "theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "/home/dido/widev/theHarvester/theHarvester/__main__.py", line 96
    print(f'\033[94m[*] Target: {word} \n \033[0m')
                                                 ^

**Comment by L1ghtn1ng** [comment]
You need to make sure you are using py3.6 or higher
________________________________

**Comment by L1ghtn1ng** [comment]
Also how are you compling?
________________________________

**Comment by darxboy** [comment]
i compile like that
-----Lenovo-G470:/home/dido/widev/theHarvester# ./theHarvester.py 
Traceback (most recent call last):
  File "./theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "/home/dido/widev/theHarvester/theHarvester/__main__.py", line 96
    print(f'\033[94m[*] Target: {word} \n \033[0m')
