### ISSUE TITLE
Google Search Error - lines 929, 446, 76, 32

### ISSUE THREAD

**Issue by sq596** [laramies/theHarvester#211]
("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "./theHarvester.py", line 929, in <module>
    start()
  File "./theHarvester.py", line 446, in start
    search.process(google_dorking)
  File "/opt/theHarvester/discovery/googlesearch.py", line 76, in process
    self.do_search()
  File "/opt/theHarvester/discovery/googlesearch.py", line 32, in do_search
    self.results = r.text
UnboundLocalError: local variable 'r' referenced before assignment

Confirmed that network connection is sound. Running through argument '-b all', Baidu, Bing, Cymon, Dogpile, DuckDuckGo all work fine - when hits the Google Search/Google Dorks, fails out with above error.

Thanks for your help!

**Comment by NotoriousRebel** [comment]
What version of the tool are you running? Google dorks is currently being worked on, as Google will start blocking requests as there are too many.  We are working on getting around and this and lowering the amount of requests google dorks makes

**Comment by L1ghtn1ng** [comment]
Closing as lots of changes has been done
