### ISSUE TITLE
Error in search

### ISSUE THREAD

**Issue by Artook10** [laramies/theHarvester#212]
Have this issue when I attempt a search. Am I missing something or not doing this right?

python theHarvester.py -d onlytourisim -l 50 -b google 
  File "theHarvester.py", line 86
    print(f'\033[94m[*] Target: {word} \n \033[0m')

**Comment by L1ghtn1ng** [comment]
Are you running python 3.6? If not then that is your problem as that is the minimum version to run it
________________________________

**Comment by leebaird** [comment]
Is the domain a .com or .org?

**Comment by leebaird** [comment]
Works fine.

python3 theHarvester.py -d onlytourism.com -l 50 -b google

[*] Target: onlytourism.com

[*] Searching Google.
	Searching 0 results.

[*] No IPs found.

[*] Emails found: 2
----------------------
info@onlytourism.com
mahmood@onlytourism.com

[*] Hosts found: 2
---------------------
dubaivisa.onlytourism.com:192.99.243.181
www.onlytourism.com:192.99.243.181
