### ISSUE TITLE
Dogpile 'Connection aborted.', RemoteDisconnected

### ISSUE THREAD

**Issue by Diabinhodo69** [laramies/theHarvester#217]
Hello,
I've been getting this error when doing **_python3 theHarvester.py -d xxxxxxxxxx.com -l 50 -b dogpile_** (or **_all_**)

> 

[*] Searching Dogpile. 
Error Occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
	Searching 0 results.
Error Occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
	Searching 10 results.

<

Am I missing any dependency or is just the remote host refusing connections?

(using version 3.0.6 v364 on Kali GNU/Linux Rolling)
Thanks

**Comment by NotoriousRebel** [comment]
Try now, I just pushed a change to it, if dogpile still crashes for some reason when doing -b all it won't crash the whole program.

**Comment by Diabinhodo69** [comment]
@NotoriousRebel I'm sorry, please close this issue. I keep getting the same problem but I've done some troubleshooting and the problem seems to be in my firewall. I can't access www.dogpile.com from my network but from another one I have no issue. Once again, I'm sorry and thanks anyway.
Cheers.
