### ISSUE TITLE
Searching CRT.sh returns no results

### ISSUE THREAD

**Issue by Diabinhodo69** [laramies/theHarvester#218]
Hello,
Using theharvester for searching CRT.sh it doesn't return results, doing the same search manually at crt.sh, I have some results.

I am I doing anything wrong or is this a know issue?

Cheers

**Comment by leebaird** [comment]
The source works. Took about 3 minutes to complete.

python3 theHarvester.py -d yale.edu -l 50 -b crtsh

*******************************************************************
*  _   _                                            _             *
* | |_| |__   ___    /\  /\__ _ _ ____   _____  ___| |_ ___ _ __  *
* | __|  _ \ / _ \  / /_/ / _` | '__\ \ / / _ \/ __| __/ _ \ '__| *
* | |_| | | |  __/ / __  / (_| | |   \ V /  __/\__ \ ||  __/ |    *
*  \__|_| |_|\___| \/ /_/ \__,_|_|    \_/ \___||___/\__\___|_|    *
*                                                                 *
* theHarvester 3.0.6 v364                                         *
* Coded by Christian Martorella                                   *
* Edge-Security Research                                          *
* cmartorella@edge-security.com                                   *
*                                                                 *
******************************************************************* 

 
[*] Target: yale.edu 
 
[*] Searching CRT.sh. 
	Searching results.

[*] No IPs found.

[*] No emails found.

[*] Hosts found: 62
---------------------
academicstrategies.ctl.yale.edu:23.185.0.3
aims.cmes.yale.edu:23.185.0.3
applied.math.yale.edu:23.185.0.3
blavatnik.ocr.yale.edu:23.185.0.3
c2.cs.yale.edu:23.185.0.3
calculator.ibm.yale.edu:23.185.0.3
cie.research.yale.edu:23.185.0.3
citizens.collaborative.yale.edu:23.185.0.3
cpcr.ipch.yale.edu:23.185.0.3
ctmedadmin.nursing.yale.edu:23.185.0.3
david.nock.yale.edu:empty
dev.yale.edu:104.16.140.133
digitalmedia.architecture.yale.edu:23.185.0.3
drupalcamp.yalesites.yale.edu:54.87.190.240
echoesofegypt.peabody.yale.edu:23.185.0.3
egcenter.economics.yale.edu:23.185.0.3
emonet.biology.yale.edu:23.185.0.3
enroll16.itsyouryale.yale.edu:empty
epi.envirocenter.yale.edu:23.185.0.3
events.president.yale.edu:23.185.0.3
evolutions.peabody.yale.edu:23.185.0.3
faculty.studyabroad.yale.edu:23.185.0.3
francesco.iachello.yale.edu:23.185.0.3
fy14.itsannualreport.yale.edu:23.185.0.3
fy15.itsannualreport.yale.edu:23.185.0.3
fy16.itsannualreport.yale.edu:23.185.0.3
gradstudents.seas.yale.edu:23.185.0.3
grow.itsyouryale.yale.edu:empty
housing-tst.yalecollege.yale.edu:52.203.53.176
housing.yalecollege.yale.edu:104.16.244.46
interactive.britishart.yale.edu:23.185.0.3
lab.yalesites.yale.edu:34.198.119.207
library.medicine.yale.edu:23.185.0.3
library.yale.edu:130.132.35.109
members.scazlab.yale.edu:23.185.0.3
opnmr.physics.yale.edu:23.185.0.3
people.earth.yale.edu:23.185.0.3
policylab.isps.yale.edu:23.185.0.3
printedpicture.artgallery.yale.edu:23.185.0.3
printedpicture2.artgallery.yale.edu:34.227.240.248
research.computing.yale.edu:23.185.0.3
resources.message.yale.edu:empty
restoration.elti.yale.edu:23.185.0.3
rsvp.invest.yale.edu:empty
rsvp.investments.yale.edu:23.185.0.3
sites.yale.edu:empty
studentguides.britishart.yale.edu:23.185.0.3
trna.research.yale.edu:23.185.0.3
tst.yale.edu:104.16.141.133
tully-symposium.chemistry.yale.edu:23.185.0.3
udw.architecture.yale.edu:23.185.0.3
update.directory.yale.edu:23.185.0.3
volga.eng.yale.edu:23.185.0.3
wcme.salisbury175.yale.edu:23.185.0.3
welcome.itsyouryale.yale.edu:34.195.33.104
wide.yalesites.yale.edu:23.185.0.3
workday.training.yale.edu:23.185.0.3
www.cbb.yale.edu:23.185.0.3
www.greenchemistry.yale.edu:23.185.0.3
www.urban.yale.edu:23.185.0.3
www.yale.edu:104.16.141.133
yalehealth.internal.yale.edu:23.185.0.3
