### ISSUE TITLE
Unable to Install (Shodan Errors)

### ISSUE THREAD

**Issue by YashvirGit** [laramies/theHarvester#220]
Traceback (most recent call last):
  File "./theHarvester.py", line 3, in <module>
    from discovery import *
  File "/root/Desktop/theHarvester/discovery/shodansearch.py", line 3, in <module>
    from shodan import Shodan
ModuleNotFoundError: No module named 'shodan'

**Comment by NotoriousRebel** [comment]
Did you do ```python3 -m pip install -r requirements.txt```?

**Comment by YashvirGit** [comment]
I have Python 2.7 bro

**Comment by L1ghtn1ng** [comment]
Yeah theHarvester only works with python3.6+ that will be your issue
________________________________

**Comment by YashvirGit** [comment]
Alright thanks mate I'll update
