### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by YashvirGit** [laramies/theHarvester#221]
Help me please i have the latest python 3.7.2 installed now got another yaml issue

![Screenshot from 2019-03-13 15-47-09](https://user-images.githubusercontent.com/48529728/54309917-a7b79180-45ea-11e9-8bdb-e937cc2be930.png)

**Comment by L1ghtn1ng** [comment]
Do pip3 --user install -r requirements.txt and that will fix it
________________________________

**Comment by YashvirGit** [comment]
Hello bro it wont says command not found 
i already install pip3 using this command : sudo apt install python3-pip
then i did pip3 --version (version is 18,1)

Can you do it for me on Teamviewer please 

![Screenshot from 2019-03-13 16-51-09](https://user-images.githubusercontent.com/48529728/54313810-7f806080-45f3-11e9-9d71-2be8f3638707.png)

**Comment by NotoriousRebel** [comment]
Did you first do ```python3 -m pip install -r requirements.txt```?

**Comment by L1ghtn1ng** [comment]
Sorry my bad you need to flip it the other way around but do doing the above will also work
________________________________

**Comment by YashvirGit** [comment]
@L1ghtn1ng here's what I did
git clone https://github.com/laramies/theHarvester.git
cd theHarvester
ls
pip3 install -r requirements.txt
python theHarvester.py

I still get the Yaml error module line 4 Import thing not found

![Screenshot from 2019-03-13 22-02-57](https://user-images.githubusercontent.com/48529728/54326368-a785b900-461f-11e9-94ca-e7f9ad218dc4.png)

**Comment by YashvirGit** [comment]
> Did you first do `python3 -m pip install -r requirements.txt`?

root@kali:~/theHarvester# python3 -m pip install -r requirements.txt
/usr/local/bin/python3: No module named pip

**Comment by YashvirGit** [comment]
root@kali:~/Desktop/theHarvester# chmod +x theHarvester.py
root@kali:~/Desktop/theHarvester# ls
api-keys.yaml  discovery   LICENSES   requirements.txt  wordlists
changelog.txt  Dockerfile  parsers    tests
COPYING        lib         README.md  theHarvester.py
root@kali:~/Desktop/theHarvester# ./theHarvester.py
Traceback (most recent call last):
  File "./theHarvester.py", line 7, in <module>
    from lib import reportgraph
  File "/root/Desktop/theHarvester/lib/reportgraph.py", line 2, in <module>
    from lib import stash
  File "/root/Desktop/theHarvester/lib/stash.py", line 2, in <module>
    import sqlite3
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

**Comment by rohitcoder** [comment]
Still, no one posted the proper solution, and closed this thread.

**Comment by NotoriousRebel** [comment]
@YashvirGit or @rohitcoder are you getting this issue? If you do not have the module pip you will need to install it and then install the required dependencies and the tool should work just fine.

**Comment by L1ghtn1ng** [comment]
The other option you can do is sudo apt-get install python3-yaml which should fix this for you as well
