### ISSUE TITLE
Return 0 results

### ISSUE THREAD

**Issue by wowficcion** [laramies/theHarvester#224]
After some email harvests on multiple sites.

theHarvester giving 0 results.

Too, Im testing againts my own Host Web, where i have emails, and return 0 results too.

**Comment by NotoriousRebel** [comment]
Hmmm, this could be attributed to numerous problems. You have to remember this tool does passive scanning, not active scanning, using open source information. Did it return 0 results if you did -b all with securityTrails and hunter api keys?

**Comment by mrajweir** [comment]
I have downloaded a copy of the repo and I'm experiencing the same output. 
I cloned the repo, and then simply ran, 'theHarvester.py -d google.com' just to get _some_ output, but theHarvester tells me there are no results to be found.

Would this have something to do with the build failing lately?

**Comment by L1ghtn1ng** [comment]
No, you need to then have a -b all for example and you should get results
________________________________

**Comment by wowficcion** [comment]
I tested it on Kali linux and work, on Ubuntu 16 dont work for me
