### ISSUE TITLE
Attempt to write a readonly database

### ISSUE THREAD

**Issue by CuriosoCat** [laramies/theHarvester#227]
I've been trying to use theHarvester and when i performed a search, it comes up with
the error indicating `"attempt to write a readonly database"` as seen below:

![image](https://user-images.githubusercontent.com/46101882/54731037-0d95b180-4bc7-11e9-9773-383a1984a118.png)

It seems to be a SQL error. Does anyone understand why is this happening? What database is it trying to write to? This only happened when i performed subsequent searches.

Any help will be greatly appreciated!

**Comment by L1ghtn1ng** [comment]
It will be trying to write to the stash.db in the root directory of theHarvester directory. If you are running it from GitHub clone the delete the file and redo your search and to my knowledge it should redo the db and fingers crossed it works for you
________________________________

**Comment by L1ghtn1ng** [comment]
Timeout, if issue still persists can reopen
