### ISSUE TITLE
Error Message on Launch - Mac OSX Yosemite

### ISSUE THREAD

**Issue by ForceLightning228** [laramies/theHarvester#23]
Traceback (most recent call last):
  File "/Users/totallynotme/Downloads/theHarvester-master/theHarvester.py", line 10, in <module>
    from discovery import *
  File "/Users/totallynotme/Downloads/theHarvester-master/discovery/googlesearch.py", line 6, in <module>
    import requests
ImportError: No module named requests

**Comment by darker0n** [comment]
pip install discovery
    pip install requests

**Comment by duckspeaker** [comment]
I think `pip install requests` should suffice. Since that's the only package required, having a requirements.txt would be overkill, but it might make sense to include a mention of `pip install requests` in the README.

**Comment by laramies** [comment]
Yes, the only dependency is requests, I added a check to see if requests is installed, and if not will tell the user to install the library. Also I added in the README the dependency. Will upload later today.

**Comment by laramies** [comment]
Btw, latest version (2.6) has both things. Can't you see them?

**Comment by duckspeaker** [comment]
After doing a pip uninstall requests and running the latest version I see the same thing that @ForceLightning228 is reporting.

**Comment by laramies** [comment]
But requests should be installed, you need to have it in order to run theHarvester, if you do an uninstall (pip uninstall requests) it is normal that it wont work. Can you confirm that it works when requests is installed? thanks.

**Comment by duckspeaker** [comment]
Sorry maybe I misunderstood your comment. I thought you were saying you added a check to see if requests is installed and, if not, give a custom message instead of a Traceback.

**Comment by laramies** [comment]
You are right, that is how it is supposed to work. But I know what is the problem. I am importing first Discovery, which will import the discovery modules and those are using requests; so it fails there before the check i  added in the main file. I will fix this, thanks for raising it.
