### ISSUE TITLE
When exporting how can I get all the results for example trello, linkedin?

### ISSUE THREAD

**Issue by fbarriosCL** [laramies/theHarvester#233]
Hello, when I try to perform the following command
```python theHarvester.py -d url -b all -s -f file```, 
in the console get results from **linkedin** or **trello**, but they do not appear in my XML export.

help me ?

**Comment by NotoriousRebel** [comment]
Looking into the xml file now, does it appear in the html report?

**Comment by L1ghtn1ng** [comment]
@NotoriousRebel Did you find any issues with this?

**Comment by NotoriousRebel** [comment]
@fbarriosCL could you answer my question? Also,  @L1ghtn1ng I didn't try with xml I tried with html and it worked.

**Comment by L1ghtn1ng** [comment]
@NotoriousRebel Do you think it might be worth getting rid of the xml and having html only?

**Comment by fbarriosCL** [comment]
@NotoriousRebel In my case, it does not work for me in XML and HTML export, sorry for the delay.

**Comment by L1ghtn1ng** [comment]
What version are you using and on what OS?
________________________________

**Comment by fbarriosCL** [comment]
Ubuntu 18.04.2 LTS and Python 3.7.3.

**Comment by L1ghtn1ng** [comment]
What version of theHarvester are you running?
________________________________

**Comment by fbarriosCL** [comment]
version: theHarvester 3.1.0.dev0 and the command that I'm executing is 

```
deploy@ovi:~/theHarvester$ python theHarvester.py -d url -b all -s -f /report.html
```

**Comment by L1ghtn1ng** [comment]
You running in a virtualenv? If not try doing that as on Ubuntu just using the python command uses py2 not py3
________________________________

**Comment by L1ghtn1ng** [comment]
Timeout
