### ISSUE TITLE
Managing the user's API key and stash.sqlite file properly

### ISSUE THREAD

**Issue by ssolidus** [laramies/theHarvester#235]
This file is currently imported from directory that `theHarvester.py` is run in. As a module, it sould store it in the following locations, using the [`appdirs`](https://github.com/ActiveState/appdirs) Python module:
- `~/Library/Application Support/theHarvester`
- `~/.local/share/theHarvester`
- `C:\Documents and Settings\<User>\Application Data\laramies\theHarvester`

I am happy to make a merge request for this.

**Comment by NotoriousRebel** [comment]
You are more than welcome to make a PR for this issue :)

**Comment by L1ghtn1ng** [comment]
@ssolidus Any progress on this?

**Comment by ssolidus** [comment]
Sorry, I've been terribly busy with work. I will get to this when I can.

**Comment by L1ghtn1ng** [comment]
@ssolidus Just to make you aware, that a while ago I implemented a yaml file config for managing api keys but it is still in the root of the project

**Comment by ssolidus** [comment]
@L1ghtn1ng I'm aware, that was actually the reason I came up with this idea - as I manage the Arch Linux package for this app, it didn't make much sense for it to be dumping config files in the directory you run the command in.

Hoping to get this done over the weekend.

**Comment by L1ghtn1ng** [comment]
That would be awesome if you can get this done over the weekend
________________________________

**Comment by L1ghtn1ng** [comment]
@ssolidus Any progress on this or I will have a look at doing this?

**Comment by L1ghtn1ng** [comment]
As we also need to do this for the stash.sqlite

**Comment by L1ghtn1ng** [comment]
@ssolidus The api-key.yaml and stash.sqlite will need to end up in /etc/theHarvester as I have merged some code that reads the files from there and if using a cloned version from git will read it from the current dir if you look at the keys in core.py

**Comment by L1ghtn1ng** [comment]
To make this more clear. The code that I am on about is for the api-keys.yaml as that is what I have fixed. Also I have added it to the setup.py(api-keys.yaml) which now puts it in the correct location

**Comment by L1ghtn1ng** [comment]
@ssolidus Any update?

**Comment by L1ghtn1ng** [comment]
Closing this out as to me this is now taken care off
