### ISSUE TITLE
starting harvester

### ISSUE THREAD

**Issue by Compl3xion** [laramies/theHarvester#236]
Here is what happens when i type theharvester
~~~~~~~~~~~~~~~~~~~
> theharvester
Traceback (most recent call last):
  File "C:\Python\bin\InformationGathering\theHarvester\theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "C:\Python\bin\InformationGathering\theHarvester\theHarvester\__main__.py", line 94
    print(f'\033[94m[*] Target: {word} \n \033[0m')
                                                 ^
SyntaxError: invalid syntax
~~~~~~~~~~~~~~~~~~~~~~
i've never encountered this problem before when using it, but now i get this.
OS details
windows 7
using with pentestbox 

 Update:I reinstalled pentestbox, but with metasploit this time

it seems to work now. which is weird due to the fact that i've 

reinstalled it aboout 20 times. but yeah it works. I've uninstalled 

everythng related to pentestbox and some other tools,non-related to 

pentest box;  Many thanks to all of you for trying to help me.

**Comment by Compl3xion** [comment]
i also re installed everything but i still get this.

**Comment by NotoriousRebel** [comment]
Are you using python3?

**Comment by Compl3xion** [comment]
Seems like its pentestbox then. I just checked, and its using python 2.7.11. i most likely have to get 3.6 then. darn pentestbox :/ theharvester was working recently though, and i had just finished updating all my tools so i thought something was wrong.  Thank you for your help.
 ~Compl3xion

**Comment by ssolidus** [comment]
@Compl3xion have you tried `python3 theHarvester.py`?

**Comment by Compl3xion** [comment]
> @Compl3xion have you tried `python3 theHarvester.py`?

yes i then receive the following in pertest box 
![Capture](https://user-images.githubusercontent.com/47437082/56307215-2f685280-60f9-11e9-8bd0-84ab38fcd264.PNG)

**Comment by ssolidus** [comment]
You need to run it as 1 command, not inside the python shell.

I'd recommend you learn a bit more about how scripts and filesystems work before you proceed

**Comment by Compl3xion** [comment]
> You need to run it as 1 command, not inside the python shell.
> 
> I'd recommend you learn a bit more about how scripts and filesystems work before you proceed

Sir i already ran it without the python shell. and still receive the same error. any other suggestions than that :/

**Comment by L1ghtn1ng** [comment]
Can you please provide a screenshot of what you are doing and what OS
you are using please?

**Comment by Compl3xion** [comment]
i fixed it

**Comment by ssolidus** [comment]
His original problem is that he was running  Python 2.7.

His new problem was that he was running it like this
```
$ python
>>>theharvester

**Comment by L1ghtn1ng** [comment]
As this is now fixed closing
