### ISSUE TITLE
I GOT NOT FOUND

### ISSUE THREAD

**Issue by cov3rteam** [laramies/theHarvester#241]
~/theHarvester   master  python3 theHarvester.py --domain qq

*******************************************************************
*  _   _                                            _             *
* | |_| |__   ___    /\  /\__ _ _ ____   _____  ___| |_ ___ _ __  *
* | __|  _ \ / _ \  / /_/ / _` | '__\ \ / / _ \/ __| __/ _ \ '__| *
* | |_| | | |  __/ / __  / (_| | |   \ V /  __/\__ \ ||  __/ |    *
*  \__|_| |_|\___| \/ /_/ \__,_|_|    \_/ \___||___/\__\___|_|    *
*                                                                 *
* theHarvester 3.1.0.dev0                                          *
* Coded by Christian Martorella                                   *
* Edge-Security Research                                          *
* cmartorella@edge-security.com                                   *
*                                                                 *
*******************************************************************

[*] No IPs found.

[*] No emails found.

[*] No hosts found.

**Comment by NotoriousRebel** [comment]
You did not specifiy the search engine with the -b flag, try that.

**Comment by cov3rteam** [comment]
why aren't all the domains known?

**Comment by NotoriousRebel** [comment]
Do,  ```python3 theHarvester.py -h```

**Comment by cov3rteam** [comment]
im use it but 90%found domain

**Comment by L1ghtn1ng** [comment]
you need to use it as follows ython3 theHarvester.py -d qq -b all
