### ISSUE TITLE
Traceback (most recent call last):  SyntaxError: invalid syntax ( Debian 9 "Stretch" -> theHarveste ) 

### ISSUE THREAD

**Issue by Dhayllin** [laramies/theHarvester#243]
pentest/theHarvester$ python2 theHarvester.py
pentest/theHarvester$ python2 theHarvester.py
pentest/theHarvester$ python3 theHarvester.py
#######################################
Traceback (most recent call last):
  File "theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "/home/user/pentest/theHarvester/theHarvester/__main__.py", line 96
    print(f'\033[94m[*] Target: {word} \n \033[0m')
                                                 ^
SyntaxError: invalid syntax

**Comment by NotoriousRebel** [comment]
What version of python3 are you using? It needs to be python3.6+.

**Comment by Dhayllin** [comment]
> What version of python3 are you using? It needs to be python3.6+.

Yes👍

**Comment by NotoriousRebel** [comment]
Could you provide a screenshot of when you type python3 what version pops up?

**Comment by Dhayllin** [comment]
> Could you provide a screenshot of when you type python3 what version pops up?

python3
==================================
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.

**Comment by L1ghtn1ng** [comment]
That is your problem you need version 3.6+ of python

**Comment by L1ghtn1ng** [comment]
Debian 9 will not work as there is no way out of the box to have that
version of python, just checked my debian 9 system

**Comment by L1ghtn1ng** [comment]
@Dhayllin Download python from this link https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tar.xz and follow this guide https://idroot.us/install-python-3-7-debian-9-stretch/ hopefully that will solve your issue

**Comment by Dhayllin** [comment]
> @Dhayllin Download python from this link https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tar.xz and follow this guide https://idroot.us/install-python-3-7-debian-9-stretch/ hopefully that will solve your issue

thanks!

**Comment by L1ghtn1ng** [comment]
The other option would be to convert your system to debain testing should you want to do that
________________________________
