### ISSUE TITLE
ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by n3mpie** [laramies/theHarvester#245]
```
root@kali:~# theharvester
Traceback (most recent call last):
   File "/usr/bin/theharvester", line 9, in <module>
      import stash
   File "/usr/share/theharvester/stash.py", line 1, in <module>
      import sqlite3
   File "/usr/local/lib/python3.7/sqlite3/_init_.py", line 23, in <module>
      from sqlite3.dbapi2 import *
   File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
      from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

**Comment by BaRRaKudaRain** [comment]
pip install %modulename%
OR
pip3 install %modulename%

Where %modulename% is your needed module. Search for it.
--
---------------------------
An outsider, the BaRRaKudaRain

-----Original Message-----

**Comment by n3mpie** [comment]
Thank you for your reply.

```
root@kali:~# pip install sqlite3
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/sqlite3
```

**Comment by L1ghtn1ng** [comment]
Also that would be the wrong pip if you are not using a virtualenv, I recommend using a virtualenv and then install everything via that and then run it. But this sounds like a Kali packaging bug as this does not happen with the one from git
________________________________

**Comment by n3mpie** [comment]
Thank you for your reply.
I installed on virtual environment, then update and upgrade all the system. Finally run theharvester, there is no error and it's working very well. As you said it seems like a Kali packaging bug but it's not seen on virtual environment.

**Comment by L1ghtn1ng** [comment]
Closing this now as enough time has past
