### ISSUE TITLE
Errors from brew package

### ISSUE THREAD

**Issue by uhlhosting** [laramies/theHarvester#247]
I have deployed it under osx with brew and I receive:

```
[+] Hosts found in search engines:
------------------------------------
No hosts found
NEW REPORTING BEGINS:
Error in the reportgraph module: No module named 'plotly'
module 'lib.reportgraph' has no attribute 'graphgenerator'
Error creating the file
Files saved!
```

For every project:

**Comment by uhlhosting** [comment]
The fun part is that I can run it as root, not as user...

**Comment by L1ghtn1ng** [comment]
@uhlhosting Would be worth mentioning this to the brew package maintainer as this is nothing to do with us.
If they want to submit a PR to help get support for brew in order that would be great as long as it does not break anything

**Comment by L1ghtn1ng** [comment]
Timeout
