### ISSUE TITLE
error creating the report when using the docker container

### ISSUE THREAD

**Issue by nikosch86** [laramies/theHarvester#248]
I receive an error creating the report when using the docker container.
Funny enough, if I enter the container and run manually it fails the first time and works the second time.
The error message:  
`module 'theHarvester.lib.reportgraph' has no attribute 'GraphGenerator'`  

the command I am using is `theHarvester.py -d target.com -e 8.8.8.8 -b all -s -f filename`

**Comment by L1ghtn1ng** [comment]
@NotoriousRebel Can you have a look at this or I can if you cannot once I have setup a docker env

**Comment by nikosch86** [comment]
I played around with the import command for reportgraph (changing it to `import .lib.reportgraph` and different variations) and  I get the feeling that this is somehow timing related as I get inconsistent results as to when it works and when it doesn't.  
for now I have removed the lines around __main.py__:880-882 so I can use the tool.  

btw, this is on master

**Comment by NotoriousRebel** [comment]
@L1ghtn1ng  I will take a look when I get a chance.

**Comment by L1ghtn1ng** [comment]
@nikosch86 Can you check master to see if you still get this?

**Comment by L1ghtn1ng** [comment]
Clsoing due to timeout

**Comment by janmasarik** [comment]
I'm still receiving this issue while running it in docker 😕

**Comment by NotoriousRebel** [comment]
@janmasarik can you try using docker as it states in the [wiki](https://github.com/laramies/theHarvester/wiki/Installation) and let me know if it still doesn't work, I will test later today as well.

**Comment by beerMT** [comment]
I'm having this issue as well when running in Docker. 
Dockerfile appears to be incorrect in repo. 
FROM kalilinux/kali is the distro that I believe should be pulled down.
