### ISSUE TITLE
Issue...

### ISSUE THREAD

**Issue by lucasvanjos** [laramies/theHarvester#250]
$ python2 theHarvester.py

Traceback (most recent call last):
  File "theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "/data/data/com.termux/files/home/theHarvester/theHarvester/__main__.py", line 96
    print(f'\033[94m[*] Target: {word} \n \033[0m')
                                                 ^
SyntaxError: invalid syntax

**Comment by L1ghtn1ng** [comment]
You need to use python3.6+
________________________________

**Comment by lucasvanjos** [comment]
i'm using python 3.6

**Comment by L1ghtn1ng** [comment]
No you are not which is stated by you having the command python2 at the beginning in your output, you need to have it python3 instead

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
