### ISSUE TITLE
theHarvester.py: error: the following arguments are required: -d/--domain

### ISSUE THREAD

**Issue by Pikramag** [laramies/theHarvester#253]
I started theHarvester.py and i see this error.
Can you give me command to fix this?

**Comment by NotoriousRebel** [comment]
How did you run it? If you ever confused you can do -h and it will display examples of how to use the tool. You must include -d/--domain as that is the domain to search for information about.

**Comment by monkeysuffrage** [comment]
I'm getting this too when I do:
python3 theHarvester.py –d Microsoft.com
or
./theHarvester.py –d Microsoft.com
on Windows 10 (cygwin)

**Comment by NotoriousRebel** [comment]
@monkeysuffrage You did not specify a search engine.

**Comment by monkeysuffrage** [comment]
Yes but that's not the issue here.

**Comment by NotoriousRebel** [comment]
When you run it what is the output?

**Comment by monkeysuffrage** [comment]
It says:
*******************************************************************
*  _   _                                            _             *
* | |_| |__   ___    /\  /\__ _ _ ____   _____  ___| |_ ___ _ __  *
* | __|  _ \ / _ \  / /_/ / _` | '__\ \ / / _ \/ __| __/ _ \ '__| *
* | |_| | | |  __/ / __  / (_| | |   \ V /  __/\__ \ ||  __/ |    *
*  \__|_| |_|\___| \/ /_/ \__,_|_|    \_/ \___||___/\__\___|_|    *
*                                                                 *
* theHarvester 3.1.0.dev0                                          *
* Coded by Christian Martorella                                   *
* Edge-Security Research                                          *
* cmartorella@edge-security.com                                   *
*                                                                 *
*******************************************************************


usage: theHarvester.py [-h] -d DOMAIN [-l LIMIT] [-S START] [-g] [-p] [-s]
                       [-v] [-e DNS_SERVER] [-t DNS_TLD] [-n] [-c]
                       [-f FILENAME] [-b SOURCE] [-x EXCLUDE]
theHarvester.py: error: the following arguments are required: -d/--domain

**Comment by L1ghtn1ng** [comment]
As the error states you need to specify the -d example.com and then you will be able to run it but that is a required parameter

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Pikramag** [comment]
How to specify?
Like: python3 theHarvester.py example.com?
Im freaking noob(((

**Comment by L1ghtn1ng** [comment]
python3 theHarvester.py -d example.com -b all

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by monkeysuffrage** [comment]
Yes, this is when using the -d parameter.
This seems to be an issue with argparse so probably nothing will come of this here.

**Comment by L1ghtn1ng** [comment]
Timeout
