### ISSUE TITLE
file error 

### ISSUE THREAD

**Issue by devocc17** [laramies/theHarvester#254]
got an error on line 94. the line reads print(f'\033[94m[*] Target: {word} \n \033[0m') with a syntaxerror.

**Comment by L1ghtn1ng** [comment]
Hi what version of python are you using?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by devocc17** [comment]
python, python 2, and python 3. python and python 2 give the same syntaxerror and python 3 is giving a modulenotfounderror:

**Comment by L1ghtn1ng** [comment]
theHarvester needs python3.6+ and if your do a pip3 install -r requirements.txt that will fix it for you

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by devocc17** [comment]
I have done that but it was giving me a pip3 command not found

**Comment by L1ghtn1ng** [comment]
If you are on a debain system apt install python3-pip
________________________________

**Comment by devocc17** [comment]
using kali wsl

**Comment by L1ghtn1ng** [comment]
This will need to be investigated
________________________________

**Comment by devocc17** [comment]
I got it to work for the pip install and its installing the requirements.txt

**Comment by L1ghtn1ng** [comment]
Ah okay nice, well done 👍

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
