### ISSUE TITLE
Unbound Local Error

### ISSUE THREAD

**Issue by stamperj1** [laramies/theHarvester#256]
When running the command: **theharvester -b all -d somedomain.com**
I get the following output: 

**found supported engines
Traceback (most recent call last):
  File "/usr/bin/theharvester", line 813, in <module>
    start(sys.argv[1:])
  File "/usr/bin/theharvester", line 145, in start
    print(("[-] Starting harvesting process for domain: " + word + "\n"))
UnboundLocalError: local variable 'word' referenced before assignment
None**

I searched through the code trying to find the issue but was unsuccessful.

**Comment by L1ghtn1ng** [comment]
Swap the -b -d params around and does that fix your issue?

**Comment by reconngg** [comment]
> Swap the -b -d params around and does that fix your issue?

yes, for a matter of fact it did work after that....hmmmm
anyways thanks!

**Comment by L1ghtn1ng** [comment]
No problem, thought that was the issue and that should be a thing of the past now with using argparse that is in git, we need to do a release to get it into kali
