### ISSUE TITLE
Source inconsistencies

### ISSUE THREAD

**Issue by kaizensoze** [laramies/theHarvester#26]
The sources are inconsistent between the README, usage text, invalid search engine text, and files in the discovery folder. What should be the current source list? It might also make sense to have them lexicographically ordered throughout.

**Comment by laramies** [comment]
I need to go over them and keep only one source of truth.. Will try to do it for the next release.

**Comment by laramies** [comment]
Hi @kaizensoze  this was fixed in the last update. thanks for raising  it.
