### ISSUE TITLE
Unable to run scanning with using TheHarvester.

### ISSUE THREAD

**Issue by Sthomssec** [laramies/theHarvester#263]
Hello Team, @laramies 

I'm getting an old know issue with TheHarvester tool, but more than that, seems to be related to Wfuzz. Error message = "Warning: Pycurl is not compiled against Openssl. Wfuzz might not work correctly when fuzzing SSL sites. Check Wfuzz's documentation for more information."

I have Openssl and pycurl install with libcurl4 installed. i've been looking for solutions but no results. I'm using kali linux. 

![Screenshot from 2019-07-06 07-16-12fixed](https://user-images.githubusercontent.com/52600822/60756704-2da68080-9fbe-11e9-954e-a532aa76d226.png)

I will really appreciate any help to figure it out. 

Thanks in advance.

**Comment by NotoriousRebel** [comment]
Scanning should still work, what is the output?

**Comment by L1ghtn1ng** [comment]
from the screenshot you have provided I can see that you are spesifying the -b parameter twice, you only need 1, this should fix your issue
