### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by d6626410** [laramies/theHarvester#266]
Error occurred in the Censys module downloading pages from Censys - IP search: + HTTPSConnectionPool(host='censys.io', port=443): Max retries exceeded with url: /ipv4/_search?q=yahoo.com&page=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f34020e1518>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Error occurred in the Censys module downloading pages from Censys - certificates search: HTTPSConnectionPool(host='censys.io', port=443): Max retries exceeded with url: /certificates/_search?q=yahoo.com&page=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f34020e14a8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Error occurred in the Censys module - hostname search: HTTPSConnectionPool(host='censys.io', port=443): Max retries exceeded with url: /ipv4/getdns (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f34020e1c88>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
  File "/root/KALI/theHarvester_DateTime/theHarvester/__main__.py", line 947, in entry_point
    start()
  File "/root/KALI/theHarvester_DateTime/theHarvester/__main__.py", line 409, in start
    hosts = filter(search.get_hostnames())
  File "/root/KALI/theHarvester_DateTime/theHarvester/discovery/constants.py", line 13, in filter
    lst = set(lst)  # Remove duplicates.
TypeError: 'NoneType' object is not iterable
None

**Comment by NotoriousRebel** [comment]
Are you using the most up to date version?

**Comment by L1ghtn1ng** [comment]
Closing due to timeout, as @NotoriousRebel rebel says please make sure you are using the version from git and if still having this issue then please re-open
