### ISSUE TITLE
Unable to run scanning with using TheHarvester - reopened

### ISSUE THREAD

**Issue by Sthomssec** [laramies/theHarvester#267]
Hello Team, @laramies #

I'm getting an old know issue with TheHarvester tool, but more than that, seems to be related to Wfuzz. Error message = "Warning: Pycurl is not compiled against Openssl. Wfuzz might not work correctly when fuzzing SSL sites. Check Wfuzz's documentation for more information."

I have Openssl and pycurl install with libcurl4 installed. i've been looking for solutions but no results. I'm using kali linux. 

![60756704-2da68080-9fbe-11e9-954e-a532aa76d226](https://user-images.githubusercontent.com/52600822/61345807-ca192000-a813-11e9-9d84-02d203d45ead.png)

I will really appreciate any help to figure it out.

Thanks in advance.

#
PD: I reopened an old issue #263 since it was closed, one collaborators recommended to remove the double -d parameter from the whole syntax, however it's not causing the issue since i did it how it is supposed to and did not work.

**Comment by laramies** [comment]
Hi, I  removed the wfuzz plugin that is causing that pycurl error message. I will re-enable it when is fully implemented. In theory it should be fixed now.  Also worth mentioning that is not an issue, as it is only a warning on how your pycurl is compiled.

**Comment by Sthomssec** [comment]
Hi, @laramies 

Appreciate the fact you answered and clarify this. I will continue experimenting and implementing resources for the grow of the community. Related to pycurl compilation i will carefully review it. 

Thanks 

Warm Regards
