### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by lyouinou** [laramies/theHarvester#268]
Hi,

 Im trying to install theHarvester on a brand new Raspbian distro.

 I tried to install requirements in a virtualenv, but I got this after setup test :

running test
running egg_info
writing theHarvester.egg-info/PKG-INFO
writing dependency_links to theHarvester.egg-info/dependency_links.txt
writing entry points to theHarvester.egg-info/entry_points.txt
writing top-level names to theHarvester.egg-info/top_level.txt
reading manifest file 'theHarvester.egg-info/SOURCES.txt'
writing manifest file 'theHarvester.egg-info/SOURCES.txt'
running build_ext
reportgraph (unittest.loader._FailedTest) ... ERROR
__main__ (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: reportgraph (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: reportgraph
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/pi/python/Harv/theHarvester/theHarvester/lib/reportgraph.py", line 5, in <module>
    import plotly.plotly as py
  File "/home/pi/python/Harv/lib/python3.7/site-packages/plotly/plotly/__init__.py", line 4, in <module>
    _chart_studio_error("plotly")
  File "/home/pi/python/Harv/lib/python3.7/site-packages/_plotly_future_/__init__.py", line 49, in _chart_studio_error
    submodule=submodule
ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead. 

======================================================================
ERROR: __main__ (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: __main__
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/pi/python/Harv/theHarvester/theHarvester/__main__.py", line 7, in <module>
    from theHarvester.lib import reportgraph
  File "/home/pi/python/Harv/theHarvester/theHarvester/lib/reportgraph.py", line 5, in <module>
    import plotly.plotly as py
  File "/home/pi/python/Harv/lib/python3.7/site-packages/plotly/plotly/__init__.py", line 4, in <module>
    _chart_studio_error("plotly")
  File "/home/pi/python/Harv/lib/python3.7/site-packages/_plotly_future_/__init__.py", line 49, in _chart_studio_error
    submodule=submodule
ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead. 

----------------------------------------------------------------------
Ran 2 tests in 0.002s

FAILED (errors=2)
Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>

 Any idea ?

Lorentz

**Comment by luger19** [comment]
I have the same problem (Raspbian too) and I installed the chart-studio successfully with `sudo pip3 install chart-studio --upgrade` but I don't know how to _use_ chart-studio.plotly _instead_ as it says in the error message.

**Comment by lyouinou** [comment]
I installed chart-studio as you did, but still getting the same error.

**Comment by L1ghtn1ng** [comment]
It will need to be changed in the code and will be able to have a look at this later
________________________________

**Comment by littl3field** [comment]
Hi, there is a solution for this. 
When using Plotly version 4 you will get this error. 
You can downgrade to version 3.10.0 to fix this this. 

Simply run:

`pip3 install plotly==3.10.0`

This will fix your problem.

**Comment by L1ghtn1ng** [comment]
I have a PR lined up that is in draft at the minute, once it has been merged this will be resolved

**Comment by shantarsecurity** [comment]
> 
> 
> Hi, there is a solution for this.
> When using Plotly version 4 you will get this error.
> You can downgrade to version 3.10.0 to fix this this.
> 
> Simply run:
> 
> `pip3 install plotly==3.10.0`
> 
> This will fix your problem.

Confirming this fixes the issue.

**Comment by clayha** [comment]
> Hi, there is a solution for this.
> When using Plotly version 4 you will get this error.
> You can downgrade to version 3.10.0 to fix this this.
> 
> Simply run:
> 
> `pip3 install plotly==3.10.0`
> 
> This will fix your problem.

Echoing this as a fix action - first time install on new build post requirements install.

**Comment by L1ghtn1ng** [comment]
I have a pr that will allow to use the new version, just need to get it merged once a few other changes have gone in
________________________________

**Comment by lyouinou** [comment]
Hi all,

 @littl3field  thank you for the advice. I tried your solution and theHarvester is now working perfectly.

@ shantarsecurity, problem fixed, thank you.
@L1ghtn1ng wonderful if that can be modified in a future update, as I'm pretty sure some other people will have the same issue.

 Thank you all for your help.

**Comment by L1ghtn1ng** [comment]
This is now fixed in master, closing
