### ISSUE TITLE
This is a issue

### ISSUE THREAD

**Issue by paradiseduo** [laramies/theHarvester#271]
![image](https://user-images.githubusercontent.com/14846965/61922103-e9d9e200-af91-11e9-80d5-b9f69b6f9d73.png)

**Comment by L1ghtn1ng** [comment]
Now fixed in master

**Comment by paradiseduo** [comment]
![image](https://user-images.githubusercontent.com/14846965/66895567-b903c900-f025-11e9-87b0-cd5fd7f4aeff.png)

**Comment by paradiseduo** [comment]
Now this issue reopen~~~~~~

**Comment by L1ghtn1ng** [comment]
Seems we have no luck with this as I adjusted it as the formatting on Kali was wrong in the new release on Kali and I do not know why
________________________________
