### ISSUE TITLE
IntelX phonebook error.

### ISSUE THREAD

**Issue by tylerjkline** [laramies/theHarvester#272]
Hi,

On a clean install and new API of IntelX, when running, the harvester output returns this error: 
```
[*] Searching Intelx.
An exception has occurred: HTTPSConnectionPool(host='public.intelx.io', port=443): Max retries exceeded with url: /phonebook/search (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5a32040ed0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
'NoneType' object is not iterable
```

The rest of the Intelx scan works just fine though. I saw 2 months ago, [IntelX released their own python API scripts](https://github.com/IntelligenceX/SDK/tree/master/Python), one of them being specifically for the phonebook.

**Comment by NotoriousRebel** [comment]
Are you able to reach the website? This seems to be a networking issue, will take a look of their API scripts as those did not exist when I wrote the plugin.

**Comment by tylerjkline** [comment]
> Are you able to reach the website? This seems to be a networking issue, will take a look of their API scripts as those did not exist when I wrote the plugin.

Yes. I verified that it was an issue with hydra by running it in a Kali VM and then on windows outside the VM. Respectively, it could be something with my network connection, but I see that as unlikely as other tools that use the same API seem to work alright.

**Comment by NotoriousRebel** [comment]
Can you please take a screenshot of your error @tylerjkline, and make sure you are using the most up to date version of the tool.

**Comment by L1ghtn1ng** [comment]
Closing this due to timeout
