### ISSUE TITLE
How can I use this under GFW?

### ISSUE THREAD

**Issue by ALeftHanded** [laramies/theHarvester#282]
I use the ssr proxy to reach google on Firefox. But I can't connect to google in terminal. 
![图片](https://user-images.githubusercontent.com/26318474/63576168-3c70e300-c5be-11e9-882d-c9603b10b753.png)

**Comment by L1ghtn1ng** [comment]
Clone the repo from git and see how that behaves for you as there has been a lot of changes that will at some point soon ish get tagged for a realese and get pushed into Kali with a lot of big fixes etc
________________________________

**Comment by ALeftHanded** [comment]
Many Chinese geek may really appreciate that. Btw, fk GFW :(.

**Comment by L1ghtn1ng** [comment]
You might want to give DoH a try but other than that I do not know how to help you, sorry

**Comment by ALeftHanded** [comment]
I finally done with using SSR vpn. Really thank u for developing this outstanding software.

**Comment by L1ghtn1ng** [comment]
From all the team thank you for your kind words
________________________________
