### ISSUE TITLE
Skip search option if API is missing "-b all"

### ISSUE THREAD

**Issue by git-me-help** [laramies/theHarvester#286]
Hi!

The "-b all"  option does not work if you miss an API key for one of the search databases. This also happend when google blocked your ip (which you already have resolved). Is it possible to make it so that theharvester will do all the querys possible in the "-b all" options that are possible without "hanging/stopping" on a search database that is not equipped with an API key.

The alternative for users now is that they have to do multiple scans by hand. Or make a "-b baidu -b google -b linkedin" kind of oneliner, but the later is capped by around 6 options or so. more options then that will simply get ignored by theharvester for some reason.

Sorry for the intrusion.

(First ever post on github, yell at me if i do something wrong! I will correct.)

**Comment by L1ghtn1ng** [comment]
You just need to do -b google,yahoo,intelx etc like that no need for multiple -b and in master the -b all option has been removed
________________________________

**Comment by git-me-help** [comment]
Ah great. This was a L1ghtn1ng quick response. I also see that it skips the "no API" response if you do it like this. Thanks for resolving
