### ISSUE TITLE
"all" sources not working

### ISSUE THREAD

**Issue by verdienansein** [laramies/theHarvester#294]
When I execute theHarvester with the following parameters:

`python3 theHarvester.py -d host -l 500 -b all`

I get the following output:
` 
[!] Invalid source.
`

From the code doesn't look like accepting 'all' parameter.

**Comment by L1ghtn1ng** [comment]
This has be removed due to issues
________________________________

**Comment by verdienansein** [comment]
So, can I remove it from arguments documentation?

**Comment by L1ghtn1ng** [comment]
It should be already removed, are you using the most up to date version of the code? Or have I missed removing it from somewhere?
________________________________

**Comment by verdienansein** [comment]
I see this in __main__.py:

    ```
parser.add_argument('-b', '--source', help='''baidu, bing, bingapi, censys, crtsh, dnsdumpster,
                        dogpile, duckduckgo, github-code, google,
                        hunter, intelx,
                        linkedin, linkedin_links, netcraft, securityTrails, threatcrowd,
                        trello, twitter, vhost, virustotal, yahoo, all''')
```

**Comment by L1ghtn1ng** [comment]
Ah so I have, will fix that

**Comment by verdienansein** [comment]
> Ah so I have, will fix that

I can do

**Comment by L1ghtn1ng** [comment]
I am going to push a few other changes as well so will be sorted in the next 5 mins

**Comment by L1ghtn1ng** [comment]
In master this has now been fixed if you update the code, thanks for pointing it out

**Comment by Reginella89** [comment]
Could you please share to me how to solve It?

**Comment by Naichell** [comment]
> In master this has now been fixed if you update the code, thanks for pointing it out

Reply: Please share how to fix the code
