### ISSUE TITLE
DNS Brute Force Error

### ISSUE THREAD

**Issue by rwbnetsec** [laramies/theHarvester#30]
Not sure if this is something I'm doing wrong, but when trying to invoke the DNS Brute Force option, it gives an error that it can't open the dictionary file. After looking at the source files, I noticed the "dns-names.txt" file wasn't there. I'm using Kali 2.0, and there's another instance of theHarvester under /usr/share/golismero/tools, which contains the dictionary file.

I copied the dictionary file to /usr/share/theharvester, then edited the "dnssearch.py" file to point to the dictionary file, and it worked fine. 

I'm not a Python expert by any means, and this was probably a quick and dirty fix, but was wondering if there was another way I was supposed to run the brute force option?

**Comment by laramies** [comment]
Hi, the dictionary file handling for the DNS is bad, it is currently hardcoded in the dnssearch.py plugin as:         self.file = "dns-names.txt"
So if you have that file in the same directory as you run theHarvester it should work.  I need to add this option to the command line. Will keep this issue open until i fix this. 
Thanks for the feedback.

**Comment by binarymist** [comment]
Any idea when this will be going into the Kali repo? Thanks.
