### ISSUE TITLE
Running theHarvester for the first time.

### ISSUE THREAD

**Issue by BMFI** [laramies/theHarvester#302]
Traceback (most recent call last):
File "/usr/bin/theharvester", line 19, in
from lib import htmlExport
ImportError: cannot import name htmlExport

I am new here, but working on all the jargon, rules and compliance. I am not sure why? I have python3.7 and tried using the gnome or Gui to open and got this Traceback. I downloaded the zip put it on the Desktop, extracted here, next opened theHarvester, lib, and core.py so I copied all the code and loaded it in the terminal. I still get a different traceback either start in the terminal
root@kali:~/Desktop/theHarvester-master# python3 theHarvester.py
Traceback (most recent call last):
File "theHarvester.py", line 10, in
from theHarvester import main
File "/root/Desktop/theHarvester-master/theHarvester/init.py", line 1, in
And from the gnome or gui I get
Information gathering, OSINT analysis, TheHarvester gives:
Traceback (most recent call last):
File "/usr/bin/theharvester", line 19, in
from lib import htmlExport
ImportError: cannot import name htmlExport
I can be working on this one, but I am slow due to time constraints and figuring out the jargon, rules and compliance, but in the mean time I am real good with quick fixes and shotgun answers, so if anyone has a resolution? I can use the help.

**Comment by NotoriousRebel** [comment]
Are you still having this error, and if so please provide a screenshot of your current python version as well as you running the code.

**Comment by L1ghtn1ng** [comment]
You need to use python3.6+ and I recommend using a virtualenv to install the requirements.txt file and with that you should be up and running, if you still have issues re-open. Thank you for reporting an issue
