### ISSUE TITLE
Replace censys with spyse

### ISSUE THREAD

**Issue by sophisticcitizen** [laramies/theHarvester#306]
Check out [spyse](https://spyse.com) API. It should be compared to censys, cause they pretty similar but Spyse could get more validated data. But also, they are less stable than censys

**Comment by L1ghtn1ng** [comment]
We are redoing the censys module to use the api and this would be a good addition to have
________________________________

**Comment by sophisticcitizen** [comment]
cool

**Comment by L1ghtn1ng** [comment]
We have decided to remove censys in favour of using spyse

**Comment by L1ghtn1ng** [comment]
This will be resolved by #320 once I get access to the new API to create the module for the new one API

**Comment by sophisticcitizen** [comment]
That's cool. I think you can contact those guys for some info about products. I know that they going to update their API to V2

**Comment by L1ghtn1ng** [comment]
So I have everything in the code base in place just need to get access to the v2 API to sort the module out properly. I do have a module but it is disabled for now till it is ready for prime time
