### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by jankooistra** [laramies/theHarvester#308]
hi,

i am on debian 10, installed it via source. But when i try to run theharvester i get:

[*] No IPs found.

[*] No emails found.

[*] No hosts found.

Everytime, with every switch. I can't find wat is wrong. Someone?

P.S. It also outputs: "table results already exits"
Cheers

**Comment by NotoriousRebel** [comment]
Are you using the most recent version? Did you also install the requirements and are using python3.6+?

**Comment by jankooistra** [comment]
Yes, Yes and yes. I found that it does work when i put a source with the -b switch after it, but it only allows one source to search

**Comment by L1ghtn1ng** [comment]
You can do the following -b google,duckduckgo,threatcrowd and so forth
________________________________
