### ISSUE TITLE
Add static typing to files

### ISSUE THREAD

**Issue by L1ghtn1ng** [laramies/theHarvester#314]
Title says it all

**Comment by GoelBiju** [comment]
Hello @L1ghtn1ng , I'm new to the project but would be happy to help. Is this for all files in the repository or within theHarvester source?

**Comment by L1ghtn1ng** [comment]
This would be for the modules and theHarvester source
________________________________

**Comment by GoelBiju** [comment]
@L1ghtn1ng I'm quite new to statically typing in Python but I'll have a learn about it and apply it here.

**Comment by GoelBiju** [comment]
@L1ghtn1ng I have just been trying to use theHarvester.py script within a pipenv shell (Python 3.7.4) however, I keep on encountering the issue that 'gevent' has not been found. Is this an issue with the way I have set up the environment? I did run pipenv install before-hand.

**Comment by L1ghtn1ng** [comment]
pipenv install grequests
________________________________

**Comment by GoelBiju** [comment]
Ok so I have it finally working when running 'python theHarvester.py'. I tried just plainly deactivating the virtual environment and running a 'pip install gevent' however I came across an access is denied issue when installing. I am using PyCharm and decided to run it as administrator. I opened the terminal instance inside PyCharm again and ran 'pipenv install' and it worked.
