### ISSUE TITLE
Shodan search not working

### ISSUE THREAD

**Issue by apatedolos** [laramies/theHarvester#315]
I realised that host_ips are not being populated for use with shodan so it is not working currently.

For now I have got around this with a bit of a hacky fix by changing the followin in __main__.py

    shodanres = []
    if shodan is True:
        import texttable
        tab = texttable.Texttable()
        header = ['IP address', 'Hostname', 'Org', 'Services:Ports', 'Technologies']
        tab.header(header)
        tab.set_cols_align(['c', 'c', 'c', 'c', 'c'])
        tab.set_cols_valign(['m', 'm', 'm', 'm', 'm'])
        tab.set_chars(['-', '|', '+', '#'])
        tab.set_cols_width([15, 20, 15, 15, 18])
        host_ip = list(set(host_ip))
        print('\033[94m[*] Searching Shodan. \033[0m')
        try:
            for ip in host_ip:
                print(('\tSearching for ' + ip))
                shodan = shodansearch.SearchShodan()
                rowdata = shodan.search_ip(ip)
                time.sleep(2)
                tab.add_row(rowdata)
            printedtable = tab.draw()
            print(printedtable)
        except Exception as e:
            print(f'\033[93m[!] An error occurred with Shodan: {e} \033[0m')
    else:
        pass

To 

    shodanres = []
    if shodan is True:
        import texttable
        tab = texttable.Texttable()
        header = ['IP address', 'Hostname', 'Org', 'Services:Ports', 'Technologies']
        tab.header(header)
        tab.set_cols_align(['c', 'c', 'c', 'c', 'c'])
        tab.set_cols_valign(['m', 'm', 'm', 'm', 'm'])
        tab.set_chars(['-', '|', '+', '#'])
        tab.set_cols_width([15, 20, 15, 15, 18])
        host_ips = []
        for x in full:
            host = x.split(':')[1]
            if ',' in host:
                multihost = x.split(':')[1].split(',')
                for i in multihost:
                    rmw = "".join(i.split())
                    host_ips.append(rmw)
            else:
                host_ips.append(host)
        host_ips2 = list(set(host_ips))
        print('\033[94m[*] Searching Shodan. \033[0m')
        try:
            for ip in host_ips2:
                print(('\tSearching for ' + ip))
                shodan = shodansearch.SearchShodan()
                rowdata = shodan.search_ip(ip)
                time.sleep(2)
                tab.add_row(rowdata)
                printedtable = tab.draw()
                print(printedtable)
        except Exception as e:
            print(f'\033[93m[!] An error occurred with Shodan: {e} \033[0m')
    else:
        pass

I know this is very likely not the best way to do it but wanted to get it working until a proper fix can be implemented.

**Comment by NotoriousRebel** [comment]
Thank you for the issue! This is being looked at.

**Comment by NotoriousRebel** [comment]
@apatedolos I have reworked the shodan logic inside __main__.py as well as reworked how the hostchecker works. Upon further examiniation there seems to be an API error with the default key; however, if you have your own key it should work now! The fix is currently [here](https://github.com/L1ghtn1ng/theHarvester/pull/27) and will be merged here soon!
Thank you for pointing this out.

**Comment by apatedolos** [comment]
Great stuff!

Ta

**Comment by L1ghtn1ng** [comment]
THis is now fixed in master
