### ISSUE TITLE
Rework of unique method inside myparser.py

### ISSUE THREAD

**Issue by NotoriousRebel** [laramies/theHarvester#316]
Inside theHarvester/parsers, the method unique inside myparser.py could use reworking as it is convoluted and could be improved upon.

**Comment by cueo** [comment]
Can I pick this up?

**Comment by NotoriousRebel** [comment]
@cueo Anyone can pick these up, these issues aren't necessarily reserved for one person. You are more than welcome to create a PR for this issue :)
