### ISSUE TITLE
Skipping emails when word-break <wbr>

### ISSUE THREAD

**Issue by JohnLife96** [laramies/theHarvester#32]
Results seem to be incomplete or missing when there are <wbr></wbr> tags after the '@' before parsing.

The result displayed will be: "@domainname.com", so no name before of the '@'.

I've tried cleaning up the results but unsuccessful so far.
Has anyone found a fix for this?

**Comment by laramies** [comment]
Hi John, can you provide me some example strings that would fail, and I will review the parser?
Cheers

**Comment by JohnLife96** [comment]
An example would be this:

```html
<em>
   name
</em>
@
<wbr></wbr>
<em>
   domainname.com
</em>
```

So I'm guessing the `<em>` tags get cleaned up nicely but the `<wbr>` does not.

**Comment by JohnLife96** [comment]
Another example


```html
<em>
   name
</em>
@

<em>
   domainname.com
</em>
```

**Comment by JohnLife96** [comment]
It seems to be a problem with the way ```<wbr>``` are handled by the HTMLparser lib in python. I found a thread about it here: http://stackoverflow.com/questions/10341954/lxml-and-wbr-tags

I'll see if I can get a workaround.

**Comment by laramies** [comment]
I made a change in the parser, can you please check it with the latest version?

**Comment by NotoriousRebel** [comment]
As this has been resolved, closing!
