### ISSUE TITLE
Add docstring

### ISSUE THREAD

**Issue by NotoriousRebel** [laramies/theHarvester#321]
Some modules and functions throughout the code base have little to no docstring, this should change!

**Comment by 400notOK** [comment]
Should documentation follow PEP8 standards?

**Comment by moodule** [comment]
hey there, I have a few PR to make so I'll add docstrings to the impacted portions.

I'd second @cueo in #346 and recommend / use [numpy](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html) or [google](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) format.

**Comment by moodule** [comment]
And I'll create a branch for documentation as soon as the async factorisation is merged :arrow_up_small:

**Comment by Medu444** [comment]
I'll third that

**Comment by L1ghtn1ng** [comment]
The async stuff has been merged so have at it at adding doc strings
