### ISSUE TITLE
Rework dorks.txt wordlist

### ISSUE THREAD

**Issue by NotoriousRebel** [laramies/theHarvester#322]
Some of the dorks are not that helpful and coul be replaced with more useful stuff.

**Comment by moodule** [comment]
What about merging & then pointing to the [SecLists dorks](https://github.com/gwen001/SecLists/blob/master/mine/gsearch-dorks.txt)?

They have github & google dorks listings, and this repo must have more traction on this subject.

**Comment by Sbajary** [comment]
some info needed:
- First, is %XT% symbol has specific purpose within some dorks at the wordlist ?

- secondly (it is a feature request more than question), can I pass the dork with the command line input (after -g option)? I think that will decrease of showing "Google blocked your IP..." message, when the whole wordlist used.

**Comment by L1ghtn1ng** [comment]
@Sbajary Sorry for the long time to respond, with regards to your first point I would assume so. With regards to your second point it would not decrease Google blocking you, needs to be looked at redoing how the Google stuff is done using there search API with there API key. Not a small job
