### ISSUE TITLE
hostchecker error

### ISSUE THREAD

**Issue by sh1va73** [laramies/theHarvester#332]
I get this error when doing a search, any idea how to fix?

I got this error after i commented out hostchecker. This was a fix suggester here : https://github.com/laramies/theHarvester/issues/45

That fix was for another error.

[+] Hosts found in search engines:
------------------------------------

Total hosts: 7

[-] Resolving hostnames IPs... 
 
Traceback (most recent call last):
  File "/usr/bin/theharvester", line 813, in <module>
    start(sys.argv[1:])
  File "/usr/bin/theharvester", line 545, in start
    full_host = hostchecker.Checker(all_hosts)
NameError: name 'hostchecker' is not defined
None

**Comment by L1ghtn1ng** [comment]
@sh1va73 You using kali by any chance? if so that is a bug in the old version of the app which you will not get in master. We will be doing a new release soon and when it gets picked up in kali this will be resolved

**Comment by sh1va73** [comment]
thanks for your reply. yes i am on latest kali.

**Comment by sh1va73** [comment]
I just did a manual install of the new version 3.1.0 and this is working fine.
