### ISSUE TITLE
relax dependencies in setup.py

### ISSUE THREAD

**Issue by blshkv** [laramies/theHarvester#345]
Please do not require the explicit version using ```pythonpkg==2.0.0``` unless it is absolutely necessary.
It is hard to impossible to satisfy two different tools, if the second tool would require ```pythonpkg==2.0.1```, for example.

The much better way is to use ```>=2.0.0```. You can also add ```<=3.0.0``` if you want to be safe

**Comment by L1ghtn1ng** [comment]
The reason we do this and there are no packages in setup.py is having reproducible builds to what the core team use and what the ci uses
________________________________

**Comment by blshkv** [comment]
hm... ok, this is good that it is not in setup.py, so I do need to remove it and can just ignore a specific version.
