### ISSUE TITLE
[Other] Enforce checkstyle

### ISSUE THREAD

**Issue by cueo** [laramies/theHarvester#346]
**Feature Request or Bug or Other**
Other

**Describe the feature request or bug or other**
Enforce checkstyle using customized variation of pylint or pychecker.
As part of this, we should enforce DocString for every method added.

As an aside, we can revisit all the existing DocStrings and convert them to Google or Numpy format. Recommended [here](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#targetText=NumPy%20style%20tends%20to%20require,long%20and%20in-depth%20docstrings.) and [here](https://github.com/Khan/style-guides/blob/master/style/python.md#docstrings).

**To Reproduce**
N/A

**Expected behavior**
Errors when checkstyle fails (eg: no DocString is added for a new method).

**Screenshots**
N/A

**System Information (System that tool is running on):**
N/A

**Additional context**
N/A

**Comment by cueo** [comment]
I'd like to work on this if this looks like something worth doing.

**Comment by L1ghtn1ng** [comment]
I like the output of Googles docstring format with type annotations. How would this work with tests that use the doc strings like noset test iirc?
________________________________

**Comment by L1ghtn1ng** [comment]
@cueo Any update on this?

**Comment by cueo** [comment]
@L1ghtn1ng Will take it up next to next weekend.
