### ISSUE TITLE
do not write stash.sqlite in the current location

### ISSUE THREAD

**Issue by blshkv** [laramies/theHarvester#347]
I was testing the latest 3.1 release today and was running the tool from different folders.
Apparently,  the tool creates a "stash.sqlite" file in the current folder and it polluted my FS.

Please define a ~/.theHarvester or similar folder and write output in one place.

**Comment by NotoriousRebel** [comment]
@blshkv where would you want it stored?

**Comment by blshkv** [comment]
I already mentioned ```~/.theHarvester``` but any single location for the entire output would be great

**Comment by L1ghtn1ng** [comment]
I have renamed #235 to include this and it will be tracked from there as they are the same thing basically just different files
