### ISSUE TITLE
Adding a feature; how to contribute back!

### ISSUE THREAD

**Issue by mannanj** [laramies/theHarvester#35]
Hi I added a feature that saves emails in .json and .csv format, to a folder within the directory called "harvestedEmails" > "Domain".

The point is to get them in easy to manipulate .json format of: {Full Name: Email address, ...}
And a .csv format of where first row is fullnames and next row is emails.

So the way this works is if you search for emails in the domain "@microsoft.com" you get a folder called harvestedEmails and a subfolder called "microsoft.com" with the saved {fullnames: emails} .json file and the .csv

So my question is: 
How do I contribute this back and commit, and are you looking for features like this to be contributed back? I am not used to committing to another project repo so I was wondering how this works. Also not sure how author recognition works in that regard.

**Comment by laramies** [comment]
Hi Mannaj, 

 

You can contribute doing a pull request and then I will review the code, and approve it if it is fine.

 

Definitely I am looking for new feature and fixes, there are other people helping with stuff.

 

In regards recognition I will add your name in the Readme, in the changelog when I explain the new feature I mention who made it.

 

Hope it helps!

Chris

**Comment by mannanj** [comment]
Awesome will do that, thanks for the quick reply.
