### ISSUE TITLE
[?] ModuleNotFoundError: No module named 'gevent'

### ISSUE THREAD

**Issue by emrecakmak** [laramies/theHarvester#351]
**Describe the feature request or bug or other**
I can't open theHarvester because of this error, I installed twice with

`pip3 install gevent` command

but still gives an error about that.

**Screenshots**
<img width="568" alt="Screen Shot 2019-10-19 at 19 39 10" src="https://user-images.githubusercontent.com/16281631/67148467-9af9cb00-f2a8-11e9-86a5-73254fbd237e.png">

**System Information (System that tool is running on):**
 - OS: [MacOS]
 - Version [10.14.6 Majove]

**Comment by L1ghtn1ng** [comment]
you also need to use grequests which is what uses gevent

**Comment by emrecakmak** [comment]
> you also need to use grequests which is what uses gevent

When I try to install grequests, It says that "Requirement already satisfied"

<img width="1185" alt="Screen Shot 2019-10-19 at 19 54 08" src="https://user-images.githubusercontent.com/16281631/67148636-5707c580-f2aa-11e9-83f1-473e858f7d4a.png">

**Comment by L1ghtn1ng** [comment]
Try the following ```python3.7 -m pip install pipenv
python3.7 pipenv install
```

**Comment by L1ghtn1ng** [comment]
Then follow the instructions on-screen

**Comment by emrecakmak** [comment]
Thanks for the help but this didn't solve the problem either.

I tried pip & pip3 install pipenv then pipenv install, the output is like this.

I also tried another solutions related with path and reinstalling ptyhon but they also didn't work, I'm about to go crazy 🤯

<img width="1103" alt="Screen Shot 2019-10-19 at 23 42 49" src="https://user-images.githubusercontent.com/16281631/67151271-84656b00-f2cc-11e9-9b83-494f5d310c53.png">

**Comment by emrecakmak** [comment]
I tried another code like 
`python3 -m pip install -r requirements.txt`
 it fixed the problem. 

Thanks for the @L1ghtn1ng

**Comment by SidaliDzHack** [comment]
i will trie it
