### ISSUE TITLE
ERROR: ERROR: Package installation failed...

### ISSUE THREAD

**Issue by M0dred** [laramies/theHarvester#357]
uname -a 
Linux XXXXXX 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

python3 -V
Python 3.7.5rc1

sudo pipenv install

warning: build_py: byte-compiling is disabled, skipping.', '    ', '    running build_ext', "    building '_cffi_backend' extension", '    creating build/temp.linux-armv7l-3.7', '    creating build/temp.linux-armv7l-3.7/c', '    arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.7m -I/root/.local/share/virtualenvs/theHarvester-L_WfqTyM/include/python3.7m -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.7/c/_cffi_backend.o', '    c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory', '     #include <ffi.h>', '              ^~~~~~~', '    compilation terminated.', "    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1", '    ----------------------------------------', 'ERROR: Command errored out with exit status 1: /root/.local/share/virtualenvs/theHarvester-L_WfqTyM/bin/python3 -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/tmp/pip-install-zbb84q3p/cffi/setup.py\'"\'"\'; __file__=\'"\'"\'/tmp/pip-install-zbb84q3p/cffi/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' install --record /tmp/pip-record-fzop0750/install-record.txt --single-version-externally-managed --compile --install-headers /root/.local/share/virtualenvs/theHarvester-L_WfqTyM/include/site/python3.7/cffi Check the logs for full command output.']
ERROR: ERROR: Package installation failed...

**Comment by NotoriousRebel** [comment]
Do you have gcc installed?

**Comment by L1ghtn1ng** [comment]
Timeout
