### ISSUE TITLE
File "theHarvester.py", line 9, in <module>

### ISSUE THREAD

**Issue by WrongProgram1** [laramies/theHarvester#359]
![image](https://user-images.githubusercontent.com/49438078/67850785-0c0c6e80-fb44-11e9-9b81-564f9677ebc9.png)

**Comment by L1ghtn1ng** [comment]
You will need to use a virtualenv, so pipenv and you should not get this issue, please look at the readme in git
________________________________

**Comment by digininja** [comment]
With a bit of struggle I've got pipenv working and installing things but still can't get this working. Can you give a bit more detailed help on getting the whole lot setup?

**Comment by john-connort8001** [comment]
I have pipenv installed and I get the same error.

**Comment by L1ghtn1ng** [comment]
@digininja @WrongProgram1 Sorry for the delay in this have an ear infection in both ears. This should be a good guide for you both to get you up and running correctly. If it does I will add it to the readme https://jcutrer.com/python/pipenv-pipfile

**Comment by L1ghtn1ng** [comment]
@digininja @WrongProgram1 I have added gevent to the requirements.txt which pipenv will also use as it exists, so in the feature should not happen now. Okay to close this ticket out?

**Comment by digininja** [comment]
Is t suggest adding that link, or a summary of it, to the installation
instructions.

**Comment by L1ghtn1ng** [comment]
Will do

________________________________

**Comment by L1ghtn1ng** [comment]
Have added the link to the wiki and will be adding the link in the readme to the wiki https://github.com/laramies/theHarvester/wiki/Installation
