### ISSUE TITLE
RFE - Identify URLs

### ISSUE THREAD

**Issue by quizbuk** [laramies/theHarvester#36]
I'd like to suggest theharvester identifies URLs as well as e-mails and domains. I find a lot of sites and files that shouldn't be available publicly during OSINT analysis. There is a lot of value in this information and even more if theharvester could make them available.

**Comment by laramies** [comment]
Hi Quizbuk, could you please provide some examples?

**Comment by quizbuk** [comment]
After submitting my RFE I stumbled across this: 
http://www.chrisains.com/seo-tools/extract-urls-from-web-serps/
Essentially, when trying to discover information about an organization i.e. Bank of America, I look for pages or URLs that aren't advertised i.e. bankofamerica.com/secret-file-share. I was thinking the harvester might be a good utility to extract those links, but after seeing the results from that javascript tool it might make for very overly complicated results on the harvester. Just a suggestion, ultimately it's up to you on how the harvester is enhanced. Either way I really appreciate what you've accomplished, great work!

**Comment by laramies** [comment]
I understand, but at the moment I work with Search engine results and I am not querying the target websites. In order to do so we need some crawling functionality.  Or do you have another idea?

**Comment by laramies** [comment]
Closing as no other ideas where proposed.
