### ISSUE TITLE
DOC: How to add and store API keys

### ISSUE THREAD

**Issue by anoduck** [laramies/theHarvester#360]
**Feature Request or Bug or Other**
Other

**Describe the feature request or bug or other**
Looking for documentation explaining how to add and store api keys for use when running modules that require them.  
Where does the script look for api_keys.yml?  

**To Reproduce**
1. Run tool with `-b all`
2. Receive error that api keys are not found for: github, hunter, bing, etc....

**Expected behavior**
Does the harvester look for keys in `~/.config/theHarvester/api_keys.yml`

**Screenshots**
Screenshots: N/A

**System Information (System that tool is running on):**
 - OS: Kali Linux
 - Version: Current

**Additional context**
The readme states, "explained below", scroll down and there is no mention of them. The project wiki is also empty, and the link on edgesecurity.com just redirects back to the github page.

**Comment by L1ghtn1ng** [comment]
What version are you using the one that is in Kali or a git clone?
________________________________

**Comment by anoduck** [comment]
@L1ghtn1ng I have both now, so it really doesn't matter. But, for ease of maintenance, let's say the version from Kali's distro, because that is what I was inquiring about originally.

**Comment by L1ghtn1ng** [comment]
The keys are in /etc/theHarvester but there is a big as we did not know they get stored there so I'm git I have added the ability to get it from there or the current directory. We need to do another release to fix that issue in Kali
________________________________

**Comment by anoduck** [comment]
Well, hot diggity dang! There it is.... Well done!

**Comment by kaliscandinavia** [comment]
.

**Comment by NoellaFomum** [comment]
I have been working on theHarvester for days now and still having issues with the API DIRECTORY.
whenever I run nano /etc/theHarvester , it shows empty dir

**Comment by L1ghtn1ng** [comment]
What operating system are you using?
How you running it?

On 9 Nov 2024, at 00:47, Noella Engwari Fomum ***@***.***> wrote:

﻿

I have been working on theHarvester for days now and still having issues with the API DIRECTORY.
whenever I run nano /etc/theHarvester , it shows empty dir

**Comment by NoellaFomum** [comment]
I'm using Kali Linux

**Comment by L1ghtn1ng** [comment]
If you run it with the -b fullhunt it should automatically then create the file

On 9 Nov 2024, at 00:52, Noella Engwari Fomum ***@***.***> wrote:

﻿

I'm using Kali Linux

**Comment by NoellaFomum** [comment]
I just did but it still empty

**Comment by NoellaFomum** [comment]
![Screenshot 2024-11-08 195651](https://github.com/user-attachments/assets/a3bfeaa4-f98a-4194-b1a8-01d15ab7a42d)

**Comment by NoellaFomum** [comment]
that's what I'm saying

**Comment by NoellaFomum** [comment]
or maybe I need to Update first

**Comment by L1ghtn1ng** [comment]
When you run theHarvester what version do you get in the header?

On 9 Nov 2024, at 01:02, Noella Engwari Fomum ***@***.***> wrote:

﻿

or maybe I need to Update first
