### ISSUE TITLE
Odd debug showing before the banner

### ISSUE THREAD

**Issue by digininja** [laramies/theHarvester#363]
**Feature Request or Bug or Other**
Other

**Describe the feature request or bug or other**
Each time I run the app I get the message "table results already exists" before the banner. It looks like debug that has been left in somewhere but I can't find a reference to that text anywhere in the app itself so it may be from one of the dependencies.

**To Reproduce**

Simply run the app:

```
$ pipenv run python3.7 ./theHarvester.py 
table results already exists

*******************************************************************
*  _   _                                            _             *
* | |_| |__   ___    /\  /\__ _ _ ____   _____  ___| |_ ___ _ __  *
* | __|  _ \ / _ \  / /_/ / _` | '__\ \ / / _ \/ __| __/ _ \ '__| *
* | |_| | | |  __/ / __  / (_| | |   \ V /  __/\__ \ ||  __/ |    *
*  \__|_| |_|\___| \/ /_/ \__,_|_|    \_/ \___||___/\__\___|_|    *
*                                                                 *
* theHarvester 3.1.1dev3                                          *
* Coded by Christian Martorella                                   *
* Edge-Security Research                                          *
* cmartorella@edge-security.com                                   *
*                                                                 *
******************************************************************* 


usage: theHarvester.py [-h] -d DOMAIN [-l LIMIT] [-S START] [-g] [-p] [-s]
                       [-v] [-e DNS_SERVER] [-t DNS_TLD] [-n] [-c]
                       [-f FILENAME] [-b SOURCE]
theHarvester.py: error: the following arguments are required: -d/--domain
```

**Expected behaviour**
No debug before the banner

**System Information (System that tool is running on):**
Ubuntu 18.04 up-to-date with the latest git code and a pip environment just created.

**Additional context**
It might not be your problem, but if not, I've no idea where I should be looking.

**Comment by NotoriousRebel** [comment]
This may be with when the program first interacts with SQLite will look into it.

**Comment by digininja** [comment]
I have updated from an older version so it may be that the old database
structure needs a tweak to bring it up to date.

**Comment by L1ghtn1ng** [comment]
@digininja We have noticed this ourselfs but not sure what it is, you idea sounds very plausible but as @NotoriousRebel  says we will have a look into that, but for now it does not causing any issues from what we have observed

**Comment by digininja** [comment]
Didn't seem to cause a problem beyond looking odd.

Happy to help debug if needed.

**Comment by L1ghtn1ng** [comment]
That would be great more heads looking at it the better 😊

________________________________

**Comment by digininja** [comment]
Let me know where to look and I'll see what I can do.

**Comment by L1ghtn1ng** [comment]
Stash.py and maybe also check the library that we are using to give ideas as well

________________________________

**Comment by digininja** [comment]
Found it, theHarvester/lib/stash.py line 21

```
c.execute('CREATE TABLE results (domain text, resource text, type text,
find_date date, source text)')
```

It looks like you always create the table regardless of whether it already
exists or not.

**Comment by L1ghtn1ng** [comment]
Yeah that would do it

________________________________

**Comment by L1ghtn1ng** [comment]
Do you get that message if you delete the database?
________________________________

**Comment by digininja** [comment]
Pull request incoming.
