### ISSUE TITLE
[Bug] No gevent

### ISSUE THREAD

**Issue by bphd** [laramies/theHarvester#364]
**Feature Request or Bug or Other**
Bug

**Describe the feature request or bug or other**
No module named 'gevent'

**To Reproduce**
```bash
python3 -m pip install pipenv
pipenv install
apt-get install python-gevent python-gevent-websocket
python3 theHarverster-master/theHarverster.py
```

**Expected behaviour**
A convivial interface who ask me to enter the informations to search and showing results 

**Screenshots**
```python
theHarvester.py line 9
__init__.py line 1
No module named 'gevent'
```

**System Information (System that tool is running on):**
 - OS: Ubuntu latest

**Additional context**

**Comment by NotoriousRebel** [comment]
Thank you for bringing this to our attention it looks like gevent is not in requirements.txt could you try pip installing it? ```python3 -m pip install gevent```
