### ISSUE TITLE
Hunter API key to theHarvester

### ISSUE THREAD

**Issue by John0516** [laramies/theHarvester#367]
I am trying to use theHarvester with the command "-b all." I have an API key for Hunter, but I don't know how to put it into theHarvester.

**Comment by L1ghtn1ng** [comment]
You using git or the one in Kali?
________________________________

**Comment by John0516** [comment]
kali

**Comment by L1ghtn1ng** [comment]
For now you will want to have the git version until we do a new release which has a fix in it for kali and then you can just follow the README.md

________________________________

**Comment by John0516** [comment]
thanks
