### ISSUE TITLE
[Bug] No gevent 2

### ISSUE THREAD

**Issue by bphd** [laramies/theHarvester#368]
**Feature Request or Bug or Other**
Feature Request | Bug | Other

**Describe the feature request or bug or other**
Following #364
Still same error after downloading the new requirements.txt 

**To Reproduce**
Steps to reproduce the behaviour:
Same than #364 + downloading the new requirements.txt

**Expected behaviour**
Same

**Screenshots**
Same

**System Information (System that tool is running on):**
Same

**Additional context**

**Comment by NotoriousRebel** [comment]
Thank you for bringing this to our attention, I just realized that gevent is not in the Pipfile I am not too familiar with pyenvs but would that fix it?

**Comment by bphd** [comment]
Can't tell you, let's wait for the author

**Comment by NotoriousRebel** [comment]
@bphd on the bright side grequests + gevent will be gone soon, we are working on big changes that will make the tool much faster :)

**Comment by bphd** [comment]
Okay, but to execute it now, what should i do ?

**Comment by NotoriousRebel** [comment]
Can you try python3.7 -m pip install gevent

**Comment by L1ghtn1ng** [comment]
@bphd This has timed out but also look at https://github.com/laramies/theHarvester/wiki/Installation to help you
