### ISSUE TITLE
[Bug|pipenv install error

### ISSUE THREAD

**Issue by M0dred** [laramies/theHarvester#369]
pipenv install

**Feature Request or Bug or Other**
Feature Request | Bug | 
Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/', '    ----------------------------------------', 'ERROR: Command errored out with exit status 1: \'c:\\users\\administrator\\.virtualenvs\\theharvester-_numwgve\\scripts\\python3.exe\' -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'C:\\\\Users\\\\Administrator\\\\AppData\\\\Local\\\\Temp\\\\pip-install-bmrt39un\\\\gevent\\\\setup.py\'"\'"\'; __file__=\'"\'"\'C:\\\\Users\\\\Administrator\\\\AppData\\\\Local\\\\Temp\\\\pip-install-bmrt39un\\\\gevent\\\\setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' install --record \'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-record-1z417dib\\install-record.txt\' --single-version-externally-managed --compile --install-headers \'c:\\users\\administrator\\.virtualenvs\\theharvester-_numwgve\\include\\site\\python3.8\\gevent\' Check the logs for full command output.']

ERROR: ERROR: Package installation failed...

**System Information (System that tool is running on):**
 - OS: [Windows10]
 - Version [2.7.15]

**Comment by L1ghtn1ng** [comment]
theHarvester does not work on python2
