### ISSUE TITLE
[Bug| pip3 install error ,This package cannot be safely installed by EasyInstall

### ISSUE THREAD

**Issue by M0dred** [laramies/theHarvester#370]
**Feature Request or Bug or Other**
Feature Request | Bug | Other

 setuptools.sandbox.SandboxViolation: SandboxViolation: open('_configtest.c', 'w') {}

    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.

    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**System Information (System that tool is running on):**
 - OS: [Windows10]
 - Python -V [3.8]

**Comment by L1ghtn1ng** [comment]
@M0dred please have a look at https://github.com/laramies/theHarvester/wiki/Installation

**Comment by L1ghtn1ng** [comment]
Timeout
