### ISSUE TITLE
[*] Searching Github (code).  [Errno 2] No such file or directory: 'api-keys.yaml'

### ISSUE THREAD

**Issue by darkmatter1505** [laramies/theHarvester#371]
Bug

Searching domain name and when theharvester gets to Github I get this error. The error happens if I have my key in the api-key.yaml file and it happens when the key is not in the yaml file.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tool like this: 'theharvester -d domain.org -l 1000 -b all -s -f harvest.html '
2. See error:
       [Errno 2] No such file or directory: 'api-keys.yaml'

**System Information (System that tool is running on):**
 - OS: Mac OSx
 - Version 10.14.6

**Comment by NotoriousRebel** [comment]
What version of theHarvester are you using?

**Comment by darkmatter1505** [comment]
3.1.0

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by distny** [comment]
Hello

I've copied the api-keys.yaml file to /root/ and edited it in /etc/theHarvester/ too, but I am still getting the error: 
[Errno 2] No such file or directory: 'api-keys.yaml'

I am using the 3.1.0 version on Kali Linux from Kali repositories.

**Comment by NotoriousRebel** [comment]
@darkmatter1505 can you please try with the latest version and follow the instructions in the wiki to install it? [wiki](https://github.com/laramies/theHarvester/wiki/Installation)

**Comment by NotoriousRebel** [comment]
@distny  please read this [issue](https://github.com/laramies/theHarvester/issues/360)

**Comment by darkmatter1505** [comment]
@NototiousRebel downloaded the latest version and installed per the wiki. The is not happening any longer, but a different error is happening. 

[*] Reporting started.
module 'theHarvester.lib.reportgraph' has no attribute 'GraphGenerator'

[!] An error occurred while creating the output file.

Do you want me to open a new issue for this error?

**Comment by VHE-AUG** [comment]
Hi,
i had to the same issue that @darkmatter1505  had.

1) moved the api-keys.yaml the same folder as theHaverster.py abd that resolved the issue.

2) 

> [*] Reporting started.
module 'theHarvester.lib.reportgraph' has no attribute 'GraphGenerator'

I had issue aswell and discoved that the intendation is not good in the reportgraph.py

As I am brandnew to github i don't how to sugest this fix. thats why i will drop it here in zip.

[reportgraph.zip](https://github.com/laramies/theHarvester/files/3964392/reportgraph.zip)

ps:Feel free to tell me if, how to do code sugests/fixes



``

**Comment by L1ghtn1ng** [comment]
Closing this out now and the report graph issue should now be fixed in master

**Comment by vinci011235** [comment]
`cat /etc/theHarvester/api-keys.yaml`
see, APIs is in white.
Delete or add.

**Comment by L1ghtn1ng** [comment]
You can replace the keys that are there with your own and the ones that are missing you add in your own ones there as well
________________________________

**Comment by koleademola** [comment]
i am having similar issues,can anyone guide me

**Comment by L1ghtn1ng** [comment]
Can you tell me what version of the code you are running and what OS please?
________________________________

**Comment by koleademola** [comment]
I am getting the same error message both on Kali 2020 version and Kali
2019. I have the two installed separately.

Thanks

**Comment by L1ghtn1ng** [comment]
If you clone the version from got it should work fine
________________________________

**Comment by koleademola** [comment]
I dont know how to do this. Please guide me.

Thanks

**Comment by L1ghtn1ng** [comment]
https://github.com/laramies/theHarvester/wiki/Installation
________________________________
