### ISSUE TITLE
[Bug] failed to detect a valid IP address from 'shops.myshopify.com'

### ISSUE THREAD

**Issue by chsafe** [laramies/theHarvester#374]
[!] Missing API key. 
[*] Searching Intelx. 
[*] Searching Netcraft. 
[*] Searching Github (code). 

[!] Missing API key. 
[*] Searching AlienVault OTX. 
	Searching results.
[*] Searching Bing. 
	Searching 0 results.
[*] Searching VirusTotal. 
	Searching results.
[*] Searching DuckDuckGo. 
[*] Searching Suip. This module can take 10+ mins to run but it is worth it.
	Searching results.
[*] Searching DNSdumpster. 

[*] IPs found: 56
-------------------

failed to detect a valid IP address from 'shops.myshopify.com'

test on macbook pro 10.15.2

**Comment by NotoriousRebel** [comment]
Thank you for bringing this to our attention, this will be looked at.

**Comment by VHE-AUG** [comment]
Hi,
still a newb at github sooo here goes.
I had the same problem and solved it like this:
It seems that netaddr.IPAddress doesn't like anything that is not an ip.
I resolved it adding some error handling.

In main.py:

`    # Results
    if len(all_ip) == 0:
        print('\n[*] No IPs found.')
    else:
        print('\n[*] IPs found: ' + str(len(all_ip)))
        print('-------------------')
        # use netaddr as the list may contain ipv4 and ipv6 addresses
        all_ip = sorted(list(set(all_ip)))
        x = 0
        ip_list: list = []
        while (x<len(all_ip)):
            try:
                ip_list.append(str(netaddr.IPAddress(all_ip[x].strip())))
                x+=1
            except:
                print('VHE error: is not valid ip adress ' + all_ip[x])
                x+=1
                continue
        #ip_list = sorted([netaddr.IPAddress(ip.strip()) for ip in set(all_ip)])
        print('\n'.join(map(str, ip_list)))`

**Comment by NotoriousRebel** [comment]
@VHE-AUG  can you please tell me what verison of the tool you are using? I just went to theHarvester/lib/hostchecker.py and tested if it can resolve shops.myshopify.com it worked just fine.

**Comment by NotoriousRebel** [comment]
Here is what I did
```async def main():
    x = Checker(hosts=['shops.myshopify.com'])
    hosts, addresses = await x.check()
    import pprint as p
    print('HOSTS')
    p.pprint(hosts, indent=4)
    print('ADRESSES')
    p.pprint(addresses, indent=4)


if __name__ == '__main__':
    asyncio.run(main())
```
inside [hostchecker.py](https://github.com/laramies/theHarvester/blob/master/theHarvester/lib/hostchecker.py)

**Comment by VHE-AUG** [comment]
Hi,
i did a fresh git clone to be sure my customizations did not mess up anything.

![image](https://user-images.githubusercontent.com/58828460/71404725-a2847a00-2633-11ea-9b15-1d083250149e.png)



for me its not returning NXDOMAIN records from searchotx.py
![image](https://user-images.githubusercontent.com/58828460/71404562-2c801300-2633-11ea-8417-feb5689c0e2d.png)


Its returning any type of record. And iam not sure its limited to the otx engine, thats why i added error handling.

**Comment by VHE-AUG** [comment]
to illustrate further.
The api returns this:
https://otx.alienvault.com/api/v1/indicators/domain/shops.myshopify.com/passive_dns

i might be missing something here since iam very new to python but i would expect the adress tag to return IP adresses:

![image](https://user-images.githubusercontent.com/58828460/71405310-59cdc080-2635-11ea-94aa-8863f87eaeb1.png)


------------------------------------------------------------
To respond to you comment about hostchecker.py:
the hostchecker.py runs on the var 'all_host'
the issue i have is on the var 'all_ip'.
I think i don't see what you are getting at :-<

**Comment by L1ghtn1ng** [comment]
The api is correct, what we do with the otx module is get the URLs from it then try and and resolve those URLs to an IP if I recall correctly. Will need to double check the module as I was the one that wrote it
________________________________

**Comment by NotoriousRebel** [comment]
@VHE-AUG  I do see what you are getting at now, you just never stated in your original issue that it was due to a certain module. I will take a look at the parser for OTX as it may need reworking, thank you for bringing this to our attention.

**Comment by L1ghtn1ng** [comment]
This has been fixed in the otx module and this in now in master so if you do an update this will work if you use the git version

**Comment by orejasdetrapo** [comment]
> Hi,
> still a newb at github sooo here goes.
> I had the same problem and solved it like this:
> It seems that netaddr.IPAddress doesn't like anything that is not an ip.
> I resolved it by adding some error handling.
> 
> In main.py:
> 
> ```
> # Results
> if len(all_ip) == 0:
>     print('\n[*] No IPs found.')
> else:
>     print('\n[*] IPs found: ' + str(len(all_ip)))
>     print('-------------------')
>     # use netaddr as the list may contain ipv4 and ipv6 addresses
>     all_ip = sorted(list(set(all_ip)))
>     x = 0
>     ip_list: list = []
>     while (x<len(all_ip)):
>         try:
>             ip_list.append(str(netaddr.IPAddress(all_ip[x].strip())))
>             x+=1
>         except:
>             print('VHE error: is not valid ip adress ' + all_ip[x])
>             x+=1
>             continue
>     #ip_list = sorted([netaddr.IPAddress(ip.strip()) for ip in set(all_ip)])
>     print('\n'.join(map(str, ip_list)))
> ```

Perfect my friend!!!

**Comment by L1ghtn1ng** [comment]
Just a reminder that this issue has been fixed in master
