### ISSUE TITLE
[Other] Factor the code?

### ISSUE THREAD

**Issue by moodule** [laramies/theHarvester#378]
Hello there, great work!!
Your project bumped me so much ahead of my little scraping :D
Apart from the functionnalities I have a few thoughts on coding style.
It's on the annoying side of coding, since it wouldn't add features, but it may make things easier in the future!

**Feature Request or Bug or Other**
Other

**Describe the feature request or bug or other**
Code snippets are duplicated with hard to spot adjustments.
It makes the code bigger, harder to read, and harder to test since there's no central point for each feature.
__main__.py is especially big and convoluted

**To Reproduce**
Read __main__.py :D

**Expected behaviour**
One function / method / script per feature:
- argument parsing
- logging (console / file)
- exporting (html / xml)
- etc
- __main__.py just controling / calling the processing modules

**Screenshots**
N/A

**System Information (System that tool is running on):**
N/A

**Additional context**
It would make debugging, testing, profiling way easier, no?

**Comment by NotoriousRebel** [comment]
@moodule Thank you for the kind words :) The entire codebase has been getting refactored as we are in the process of making everything asynchronous. Please look [here](https://github.com/L1ghtn1ng/theHarvester/tree/dev) for the current progress, we are almost done with the refactoring and there should be a new release soon.

**Comment by moodule** [comment]
oops :D
Thanks for the pointer I completely missed that!

I may have another kind of factoring for you, it should add to @L1ghtn1ng 's work hopefully.
I'll do a piece to check with you if it's going in the right direction.

**Comment by L1ghtn1ng** [comment]
@moodule You going to work on this or shall I close this out?

**Comment by L1ghtn1ng** [comment]
Timeout
