### ISSUE TITLE
[Feature Request] Reverse DNS

### ISSUE THREAD

**Issue by moodule** [laramies/theHarvester#379]
**Feature Request or Bug or Other**
Feature Request

**Describe the feature request or bug or other**
It looks like reverse DNS is proposed in the CLI / `__main__.py`, but not actually implemented?

**To Reproduce**
Steps to reproduce the behaviour:
1. Run python theHarvester.py -d <...> -n
2. See error "module 'theHarvester.discovery.dnssearch' has no attribute 'DnsReverse'"

**Expected behaviour**
I'd guess DnsReverse would check the IPs in the neighboorhood of all the discovered hosts?
And then check whether there's a domain registered for every tested IP?

**Screenshots**
N/A

**System Information (System that tool is running on):**
N/A

**Additional context**
N/A

**Comment by NotoriousRebel** [comment]
Thank you for raising this issue, this will be looked at soon!

**Comment by moodule** [comment]
Actually I have a little proposition :D
But I'm really not sure if I understant correctly!!

I wrote 'DnsReverse' as a copy of 'DnsForce', simply adding a step to reverse every ip in the target, then resolving.

It's waiting in a fork.

**Comment by moodule** [comment]
I couldn't make out what to return from the looks of `__main__.py`:
- results are appended to the variable `full` but not to the db
- `full` is added to the db before brute dns & reverse dns processing
- `full` seems to be a list of str, but nothing definite about that

I have so many questions about `__main__.py`!!

**Comment by L1ghtn1ng** [comment]
This has been a thing Todo on Chris's Todo list as part of the refactoring it got removed and so far it's only a basic one, but work still needs doing to it to make it feature complete again
________________________________

**Comment by moodule** [comment]
I implemented it [here](https://github.com/moodule/theHarvester/blob/reverse-dns-lookup/theHarvester/discovery/dnssearch.py).

It tested it manually:
it finds a couple of linked & valid IPs in the neighbourhood of a given domain.

**Comment by L1ghtn1ng** [comment]
Submit a pr for this would be perfect
________________________________

**Comment by orejasdetrapo** [comment]
Hi,
 I make the changes inside dns search.py, but in execution it show this error... 'Dns Reverse' object has no attribute 'list'

**Comment by NotoriousRebel** [comment]
@orejasdetrapo without access to the code or a traceback it is much harder to help.

**Comment by orejasdetrapo** [comment]
Yes!! this is the code: https://github.com/moodule/theHarvester/blob/reverse-dns-lookup/theHarvester/discovery/dnssearch.py

**Comment by moodule** [comment]
Hey there, @orejasdetrapo you should pull `__main__.py` too.
The method `DnsReverse.list` has been removed and the calls in `__main__.py` modified

**Comment by moodule** [comment]
But I have the changes in mind, I'm just waiting for the upcoming merge with L1ghn1ng's fork.
I'll rather go help fix this merge when I can!

**Comment by NotoriousRebel** [comment]
@moodule any updates?

**Comment by moodule** [comment]
Hey there, sorry I let this drag!!
Looking into it now, hopefully I'll submit a PR today :grin:

**Comment by L1ghtn1ng** [comment]
This has been resolved
