### ISSUE TITLE
[Other] API keys Documentation

### ISSUE THREAD

**Issue by DonRichards** [laramies/theHarvester#380]
**Feature Request or Bug or Other**
Other

**Describe the feature request or bug or other**
Add the documentation to the README on how to configure the API keys

**To Reproduce**
N/A

**Expected behaviour**
Docs on how to configure in the README and not relying on the closed tickets.

**Screenshots**
N/A

**System Information (System that tool is running on):**
N/A

**Additional context**
Information is in https://github.com/laramies/theHarvester/issues/360

**Comment by NotoriousRebel** [comment]
@DonRichards Thank you for raising this issue, this will be taken care.

**Comment by L1ghtn1ng** [comment]
This is in master now, are you happy with it? It is also in the wiki

**Comment by DonRichards** [comment]
Did you intend to leave your Shodan and intelx keys in the api-keys.yaml file? Was this an example?

**Comment by L1ghtn1ng** [comment]
They are public ones which is fine to be in there

**Comment by L1ghtn1ng** [comment]
But come to think of it probably can remove them as think those keys have been revoked anyway

**Comment by L1ghtn1ng** [comment]
Shodan yes not sure about the intelx one

**Comment by L1ghtn1ng** [comment]
I have removed shodan and will be checking it in a sec, closing this out as the information is on the readme
