### ISSUE TITLE
HTTPConnectionPool(host='www.google.com', port=80): Max retries exceeded with url: /search?num=100&start=0&hl=en&meta=&q=%40%22cisco.com%22 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96fb3d6ad0>: Failed to establish a new connection: [Errno 110] Connection timed out')) local variable 'r' referenced before assignment

### ISSUE THREAD

**Issue by Zaarc** [laramies/theHarvester#382]
Hello I'm facing this issue where the internet wont let me connect. I have had this issue from the moment i started using the Harvester. I am in China currently and I'm using shadow socks proxy so my question is does it have anything to do with it? either ways please post a solution. Thanks in advance :)

**Comment by NotoriousRebel** [comment]
You may need to modify the requests so they go through the proxy see [here](https://stackoverflow.com/questions/12601316/how-to-make-python-requests-work-via-socks-proxy) for more info.

**Comment by Zaarc** [comment]
Thanks for replying I'm sorry but i have a very basic understanding of python so is there anyway that you could help me how to make requests over python?
although i checked the link but im not sure how to configure and import requests libs in python. Thanks again :)

**Comment by NotoriousRebel** [comment]
Requests is a library that we use to make the http requests, it has already been imported. In your case lets look at [googlesearch.py](https://github.com/laramies/theHarvester/blob/master/theHarvester/discovery/googlesearch.py) where we do requests.get(urly, headers=headers) you will most likely have to change it to  
requests.get(urly, headers=headers, proxies=dict(http='socks5://user:pass@host:port',
                                 https='socks5://user:pass@host:port')) You are going to have to pip install pysocks as well as do pip install -U requests[socks]

**Comment by Zaarc** [comment]
Yes, I have already installed the modules now what it is the next procedure?

**Comment by NotoriousRebel** [comment]
You need to modify how the requests are made add the extra parameter to the request. I encourage you to learn more about Python and the requests library.

**Comment by L1ghtn1ng** [comment]
Closing this out
