### ISSUE TITLE
Problem when start the harvester

### ISSUE THREAD

**Issue by ringawy** [laramies/theHarvester#384]
I,m pip requirements.txt and when try python3 theHarvester.py i have error please help
![Screenshot_٢٠٢٠٠١١٤-٠٤٠٢١٣_Termux](https://user-images.githubusercontent.com/18529940/72307448-fdcde900-3682-11ea-9bbd-445e6e5a02f8.jpg)

**Comment by L1ghtn1ng** [comment]
Please have a look at https://github.com/laramies/theHarvester/wiki/Installation
________________________________

**Comment by L1ghtn1ng** [comment]
Closing due to timeout
