### ISSUE TITLE
Bug with IntelX and Trello modules

### ISSUE THREAD

**Issue by padstm** [laramies/theHarvester#386]
There's a bug with the IntelX and Trello modules

Steps to reproduce the behaviour for IntelX:
1. Provide an API key in the api-keys.yaml file
2. Run command:
theHarvester -d google.ca -b intelx
3. See output error:
[*] Searching Intelx. 
An exception has occurred: Expecting value: line 1 column 1 (char 0)

Steps to reproduce the behaviour for Trello:
1. Run command:
theHarvester -d google.ca -b trello
2. See output:
[*] Searching Trello. 
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
substring not found
	Searching 0 results.

System Information:
 - Kali Linux (4.17.0-kali1-686)
 - theHarvester 3.1.1dev3
 - python 3.7.5

**Comment by NotoriousRebel** [comment]
@padstm I believe this has been resolved in the upcoming merge, I tested this on my fork's dev branch and it worked with no errors :)

**Comment by L1ghtn1ng** [comment]
This will be fixed when #383 is merged, closing this out
