### ISSUE TITLE
Ubuntu  19.10 failed to install

### ISSUE THREAD

**Issue by XD346** [laramies/theHarvester#387]
Installed harvester in /obt 
Traceback (most recent call last):
  File "theHarvester.py", line 9, in <module>
    from theHarvester import __main__
  File "/opt/theHarvester/trunk/theHarvester/__main__.py", line 3, in <module>
    from theHarvester.discovery import *
  File "/opt/theHarvester/trunk/theHarvester/discovery/baidusearch.py", line 3, in <module>
    import grequests
ModuleNotFoundError: No module named 'grequests'

r/trunk$ python theHarvester.py 
[!] Make sure you have Python 3.7+ installed, quitting.

python
Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 9.2.1 20191008] on linux2

Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] on linux

**Comment by NotoriousRebel** [comment]
@XD346 Did you follow every step as documented here: [installation](https://github.com/laramies/theHarvester/wiki/Installation)

**Comment by L1ghtn1ng** [comment]
Timeout

**Comment by Bennysam171** [comment]
I keep having problem after installing theHarvester
I can't get it to run

**Comment by L1ghtn1ng** [comment]
Please install theHarvester on a supported OS version of Ubuntu 22.04 which is the latest LTS release and follow the install instructions with regards to virtualenv that is on the wiki and you will be fine after that

On 3 May 2022, at 14:58, Bennysam171 ***@***.***> wrote:

﻿

I keep having problem after installing theHarvester
I can't get it to run
