### ISSUE TITLE
How to deploy this project in azure ?

### ISSUE THREAD

**Issue by Hari-c4** [laramies/theHarvester#390]
This is not an issue. I dont know whether this is the right place to ask this question. I would like to know Is it possible to deploy this as an azure function ? I tried to create an HTTP triggered azure function to return Emails only as the json response. It works for single search engine, but for 'all' search search engines, a timeout error is occurring.

**Comment by L1ghtn1ng** [comment]
This is not something we have ever tried but if you get things working please update the wiki
________________________________

**Comment by NotoriousRebel** [comment]
Also @Hari-c4 if you can post a log that maybe helpful for either us or others to help out :)

**Comment by L1ghtn1ng** [comment]
Timeout
