### ISSUE TITLE
crtsh error

### ISSUE THREAD

**Issue by shanow7** [laramies/theHarvester#392]
![image](https://user-images.githubusercontent.com/37192410/74777389-adf1cb80-5299-11ea-8498-cda7daf08eb7.png)

**Comment by NotoriousRebel** [comment]
@shanow7 could you please try this with the most up to date version of the tool?

**Comment by L1ghtn1ng** [comment]
What operating system are you using as that is the old version the current stable is 3.1 in master it is 3.2 and you should not get any issues with crtsh in those
________________________________

**Comment by shanow7** [comment]
thx :)

**Comment by shanow7** [comment]
jak zainstalowac wersje 3.2 bo instaluje sie tylko 3.1.0 zarowno przez apt install theharverster jak i https://github.com/laramies/theHarvester

**Comment by L1ghtn1ng** [comment]
https://github.com/laramies/theHarvester/wiki/Installation

**Comment by shanow7** [comment]
I used 
  $ ~ > git clone https://github.com/laramies/theHarvester 
    $ ~ > cd theHarvester

    If developing do:
        $ ~ > python3 -m pip install -r requirements/dev.txt
    Else:
        $ ~ > python3 -m pip install -r requirements/base.txt

    $ ~ > python3 theHarvester.py -h  

and still have 3.1.0

**Comment by NotoriousRebel** [comment]
@shanow7 If you run the tool what does the banner display?

**Comment by shanow7** [comment]
if I use theharvester or sudo theharvester is 3.1.0 but when I use python3 theharvester.py is 3.2

**Comment by L1ghtn1ng** [comment]
That will be due to the version that is installed on kali

________________________________
