### ISSUE TITLE
Hardcoded path to proxies.yaml

### ISSUE THREAD

**Issue by whoot** [laramies/theHarvester#393]
**Bug**

You are using the hardcoded path '/etc/theHarvester' to search for the proxies.yaml.
For anyone who did not install theHarvester on */etc/theHarvester* the tool does not work, because of the hardcoded path.

Error message:
```
Traceback (most recent call last):
  File "/opt/theHarvester/theHarvester/lib/core.py", line 95, in proxy_list
    with open('/etc/theHarvester/proxies.yaml', 'r') as api_keys:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/theHarvester/proxies.yaml'
```

You should not use hardcoded paths

**Comment by L1ghtn1ng** [comment]
Did you install it via git in that location? As if so it should find it in its current directory
________________________________

**Comment by whoot** [comment]
I cloned the repo to */opt/theHarvester* and did a 
*python3 -m pip install -r requirements/base.txt*

Im starting the tool with
*python3 /opt/theHarvester/theHarvester.py [...]*

**Comment by L1ghtn1ng** [comment]
Ah I see your problem you to cd into the location and run it from there then you will not get that error
________________________________

**Comment by whoot** [comment]
> 
> Ah I see your problem you to cd into the location and run it from there then you will not get that error
>

Indeed, this works.

However, I tried to install theHarvester and execute it and got this:

```
root@kali:# theHarvester 

*******************************************************************
*  _   _                                            _             *
* | |_| |__   ___    /\  /\__ _ _ ____   _____  ___| |_ ___ _ __  *
* | __|  _ \ / _ \  / /_/ / _` | '__\ \ / / _ \/ __| __/ _ \ '__| *
* | |_| | | |  __/ / __  / (_| | |   \ V /  __/\__ \ ||  __/ |    *
*  \__|_| |_|\___| \/ /_/ \__,_|_|    \_/ \___||___/\__\___|_|    *
*                                                                 *
* theHarvester 3.2.0dev0                                          *
* Coded by Christian Martorella                                   *
* Edge-Security Research                                          *
* cmartorella@edge-security.com                                   *
*                                                                 *
******************************************************************* 


<coroutine object entry_point at 0x7f8b692fa050>
sys:1: RuntimeWarning:

coroutine 'entry_point' was never awaited
```

**Comment by NotoriousRebel** [comment]
@whoot Can you do python3 --version and show me the output?

**Comment by whoot** [comment]
Sure, here you go:
```
$ python3 -V

Python 3.7.6
```

**Comment by cosad3s** [comment]
I encounter the same problem.

- Tested in Docker image "ubuntu:latest"
- Python version: 3.10.6
- Clone from git in a new folder /app/ : `git clone https://github.com/laramies/theHarvester && cd theHarvester && pip install -r requirements/base.txt && chmod a+x theHarvester.py`
- Execute: `./theHarvester.py -b all -l 50 -d example.org -f "test"`

Result:

```bash
Traceback (most recent call last):
  File "/app/theHarvester/theHarvester/lib/core.py", line 96, in proxy_list
    with open('/etc/theHarvester/proxies.yaml', 'r') as proxy_file:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/theHarvester/proxies.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/theHarvester/theHarvester/lib/core.py", line 100, in proxy_list
    with open('/usr/local/etc/theHarvester/proxies.yaml', 'r') as proxy_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/etc/theHarvester/proxies.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/theHarvester/theHarvester.py", line 5, in <module>
    from theHarvester import __main__
  File "/app/theHarvester/theHarvester/__main__.py", line 4, in <module>
    from theHarvester.discovery import dnssearch, takeover, shodansearch
  File "/app/theHarvester/theHarvester/discovery/takeover.py", line 1, in <module>
    from theHarvester.lib.core import *
  File "/app/theHarvester/theHarvester/lib/core.py", line 238, in <module>
    class AsyncFetcher:
  File "/app/theHarvester/theHarvester/lib/core.py", line 239, in AsyncFetcher
    proxy_list = Core.proxy_list()
  File "/app/theHarvester/theHarvester/lib/core.py", line 103, in proxy_list
    with open('proxies.yaml', 'r') as proxy_file:
FileNotFoundError: [Errno 2] No such file or directory: 'proxies.yaml'
```

**Comment by L1ghtn1ng** [comment]
Will work on the docker issue this weekend as that should be easy to resolve that for docker

**Comment by L1ghtn1ng** [comment]
This has been fixed now in the docker image

**Comment by mashiachilov-dev** [comment]
guys I am facing the same problem. can you guys tell me where can I find docker instruction to solve this

**Comment by L1ghtn1ng** [comment]
It will error but you run again and it should be fine if you are using the latest version as it will automatically create it.

On 7 Jan 2024, at 19:26, mashiachilov-dev ***@***.***> wrote:

﻿

guys I am facing the same problem. can you guys tell me where can I find docker instruction to solve this

**Comment by mashiachilov-dev** [comment]
> in my case it is saying invalid source. I am just using google as source. if i dont put google is says argument needed

**Comment by L1ghtn1ng** [comment]
Yeah Google is not a source so that is correct, it got removed a while ago due to it getting blocked all the time

On 7 Jan 2024, at 19:30, mashiachilov-dev ***@***.***> wrote:

﻿

in my case it is saying invalid source. I am just using google as source. if i dont put google is says argument needed

**Comment by mashiachilov-dev** [comment]
yeah that came to my mind now.  other sources are working but google was not. thank you all good now
