### ISSUE TITLE
[Bug] DnsForce not using dnsserver?

### ISSUE THREAD

**Issue by BrunoMCBraga** [laramies/theHarvester#395]
**Feature Request or Bug or Other**

**Describe the feature request or bug or other**
Going over the code to understand what you do with the dnsresolver input i spotted:
https://github.com/laramies/theHarvester/blob/c66c1981106e259254deb93e59922cc736e2a940/theHarvester/discovery/dnssearch.py#L9

I don't see the dnsserver i provide as input being used for the requests. Is this correct or am i missing something?

Was expecting to see something like:

https://stackoverflow.com/questions/3898363/set-specific-dns-server-using-dns-resolver-pythondns

**Comment by NotoriousRebel** [comment]
Thanks for bringing this up, this will be looked up.

**Comment by NotoriousRebel** [comment]
@BrunoMCBraga please try now :)

**Comment by L1ghtn1ng** [comment]
Timeout
