### ISSUE TITLE
[Bug] Proxy feature for Takeover seems broken

### ISSUE THREAD

**Issue by BrunoMCBraga** [laramies/theHarvester#396]
**Feature Request or Bug or Other**
Feature Request | Bug | Other

**Describe the feature request or bug or other**
Yesterday was having issues with the api keys file using Kali version of the tool. Pulled the new version and was sorted. Now, when i run a scan and use the Takeover flag, it returns an error.

**To Reproduce**
Command on the screenshot

**Expected behaviour**

**Screenshots**
<img width="611" alt="Screenshot 2020-02-27 at 17 52 14" src="https://user-images.githubusercontent.com/5751467/75466154-0c016b80-598a-11ea-8dc2-fd83598b255e.png">

**System Information (System that tool is running on):**
 - Kali Linux 

**Additional context**

**Comment by NotoriousRebel** [comment]
Thank you making this issue, I will look at this ASAP.

**Comment by BrunoMCBraga** [comment]
Let me know if you need more details.

**Comment by NotoriousRebel** [comment]
@BrunoMCBraga can you do a git pull and try again?

**Comment by NotoriousRebel** [comment]
When you run the tool you should be seeing
![image](https://user-images.githubusercontent.com/36310667/75486836-47486e00-597b-11ea-942c-2b8d55cb4440.png)

**Comment by BrunoMCBraga** [comment]
Let me try this tomorrow Sir. Quite late here :). Thank you for the prompt response.

**Comment by BrunoMCBraga** [comment]
Also, i left another issue: https://github.com/laramies/theHarvester/issues/395

i may be totally wrong here but if i am not, the requests are not being sent to the DNS provided which may compromise the users anonymity  .

**Comment by BrunoMCBraga** [comment]
Did you push the changes? Your last commit is from February 16 and when i run git pull i get a message saying it is up to date.

**Comment by NotoriousRebel** [comment]
@BrunoMCBraga When you run the tool notice the banner that is being displayed, you are not using the most recent version of the tool. Please try with the most recent version and let me know if the error still exists.

**Comment by BrunoMCBraga** [comment]
It is sorted now. Not sure if you can answer this but when i checked the last commit it was weeks ago. When i did git status it said no changes detected but when i ran git pull the banner changed. How did this happen?

**Comment by BrunoMCBraga** [comment]
It is sorted now. Thank you
