### ISSUE TITLE
'theharvester' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by francesco1119** [laramies/theHarvester#398]
**Feature Request or Bug or Other**
Other

**Describe the feature request or bug or other**
As described [here ](https://pypi.org/project/theHarvester/#description)I typed `pip install theHarvester` and the installation worked. However after installation if I type `theHarvester` nothing happens:

![2020-03-08 21_37_38-Window](https://user-images.githubusercontent.com/3397477/76170742-10e1ce80-6185-11ea-8cc6-dc5c8dc72f92.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Type `pip install theHarvester` and install theHarvester
2. Now type `theHarvester`, nothing works

**Expected behaviour**
theHarvester should have path set by default or at least the documentation should explain how to install on Windows 10

**System Information (System that tool is running on):**
 - OS: Windows10 Home

**Comment by NotoriousRebel** [comment]
Thank you for bringing this up, we do not maintain the pip package at the moment so I suggest installing it via an alternative method as described in the wiki.
