### ISSUE TITLE
Google redirects to captcha page after few hits

### ISSUE THREAD

**Issue by rockyhalo** [laramies/theHarvester#40]
Google redirects to captcha page after few search.

After googling found this
https://support.google.com/websearch/answer/86640?hl=en

ex link
https://ipv4.google.com/sorry/IndexRedirect?continue=https://www.google.com/search%3Fnum%3D100%26start%3D0%26hl%3Den%26meta%3D%26q%3D%2522%2540domain.com%2522&hl=en&q=CGMSBF_aYP8Y-LmqtwUiGQDxp4NLWqImWuv_B6W9kLBkNtRCdvfTC2wqUGh0dHBzOi8vd3d3Lmdvb2dsZS5jb20vc2VhcmNoP251bT0xMDAmc3RhcnQ9MCZobD1lbiZtZXRhPSZxPSUyMiU0MGltcGV0dXMuY29tJTIy

@laramies Any solution is appreciated.

**Comment by laramies** [comment]
That's normal if you do a lot of queries with theHarvester, in order to prevent this you should use the googleCSE API (Custom Search Engine) in order to prevent any kind of blocking.
