### ISSUE TITLE
Error google dorks

### ISSUE THREAD

**Issue by X-n3t** [laramies/theHarvester#409]
I have this error:
[*] Searching Google. 

[-] Searching with Google Dorks: 
[Errno 2] No such file or directory: 'wordlists/dorks.txt'

![imagen](https://user-images.githubusercontent.com/52056830/77733745-c1662400-7007-11ea-9a4b-329241c7c37a.png)

**Comment by L1ghtn1ng** [comment]
Please use the version from git
________________________________

**Comment by X-n3t** [comment]
![imagen](https://user-images.githubusercontent.com/52056830/77742014-11e47e00-7016-11ea-97cf-e5c81ca01942.png)
![imagen](https://user-images.githubusercontent.com/52056830/77742078-2e80b600-7016-11ea-88a7-29e90b606474.png)

**Comment by L1ghtn1ng** [comment]
What operating system are you using?
________________________________

**Comment by X-n3t** [comment]
with native directory works!:
python3 theHarvester.py ....

parrot OS

**Comment by L1ghtn1ng** [comment]
Yeah will be due to the fact that the default python version is 2 which will be why you are getting that, will need to see how they are packaging it to make it consistent with Kali
________________________________

**Comment by X-n3t** [comment]
For parrot OS I apply this solution:
#Uninstall 3.2
python3 setup.py install --record files.txt
xargs rm -rf < files.txt  
#Install 3.1
apt-get install theharvester

**Comment by X-n3t** [comment]
Eror with 3.1 version:
[*] No Trello URLs found.

[*] Reporting started.
module 'theHarvester.lib.reportgraph' has no attribute 'GraphGenerator'

[!] An error occurred while creating the output file.

**Comment by L1ghtn1ng** [comment]
That has been fixed in master
________________________________
