### ISSUE TITLE
[BUG]report.htm

### ISSUE THREAD

**Issue by X-n3t** [laramies/theHarvester#410]
I have cleaned theharvester installation and reinstall again. When check the reports, I see only a few lines (4 lines), after I had a full report with tables.

**Comment by NotoriousRebel** [comment]
how are you running the tool?

**Comment by X-n3t** [comment]
![imagen](https://user-images.githubusercontent.com/52056830/78554149-eaa66180-780a-11ea-9776-19f9fc38db00.png)

https://pastebin.com/jW3HvWvT

**Comment by X-n3t** [comment]
![imagen](https://user-images.githubusercontent.com/52056830/78555536-8b961c00-780d-11ea-88f1-fb3e68c96f51.png)

https://pastebin.com/jW3HvWvT

**Comment by L1ghtn1ng** [comment]
@X-n3t Can you please check with the current changes in master please?

**Comment by L1ghtn1ng** [comment]
Timeout
