### ISSUE TITLE
Spyse API Key (Update)

### ISSUE THREAD

**Issue by Greg-spec** [laramies/theHarvester#411]
We noticed that you used the API of one of Spyse's products most likely it was Findsubdomains, Cert DB or DNS table. We want to notify you about the release of a new and improved API key which you can find in your personal account at spyse.com. 
Unfortunately, we should stop supporting the old API a few weeks earlier, starting from Monday. Thanks for being with us.

**Comment by L1ghtn1ng** [comment]
Hi Greg, thanks for letting us know

**Comment by L1ghtn1ng** [comment]
We have now fixed this in master
