### ISSUE TITLE
[Bug|theharvestor suddenly stops giving any output

### ISSUE THREAD

**Issue by amartya89** [laramies/theHarvester#412]
I have run theharvester couple of times in different domains and found the results from various sources as supported by theharvestor.

But suddenly it stops returning any results on the same domains and any domain i search

Below are the sets of commands that i have triggered:

theharvester -d zzz.com -l 500 -b google
theharvester -d zzz.com -l 500 -b linkedin

Request you to please look into it and help me out.

I think it is giving HTTP error 429: Too many requests. I have tried using another tool at that time and found the same there. Seems this is the cause. How to resolve this please?

**Comment by L1ghtn1ng** [comment]
That is due to Google blocking you, if you are using the version from got you can use proxies and there is not much we can do unfortunately
________________________________

**Comment by amartya89** [comment]
Hi @L1ghtn1ng 

Thanks for the reply. I am using the version comes inbuilt with Kali and also using proxies. Still hitting the same issue.

**Comment by L1ghtn1ng** [comment]
Yeah for now use the got version till we tag a new release to get hooked into kali

**Comment by amartya89** [comment]
Hi @L1ghtn1ng 

I express my heartiest thanks to you and the community for such a great tool. But as i told, the problem still persists everywhere. Google is blocking by rate limiting and throwing HTTP error 429. I have checked this in multiple locations and across everywhere the same is happening. 

This is actually hampering the tool's use. I would earnestly request you to please look into it if the same can be handled from within the code. 

Because after 2 -3 hits only, (i.e. google, baidu, bing... just 2-3) google is blocking. That means each time we need a proxy, which is not feasible. 

On behalf of all the users this is an appeal to you for helping us.

**Comment by L1ghtn1ng** [comment]
I understand your frustration as it frustrates us as well but unfortunately it is a cat and mouse game that we cannot win, there is only a few things we can do and we have. Unless someone develops a new search engine that returns the same results as Google that does not block scripts then there is no hope

**Comment by NotoriousRebel** [comment]
How are you running the tool? If you use the latest versions you can provide more than one proxy and it will randomly select one per request. You are not limited to one proxy, also if you do -b all you should still be getting a lot of results.

**Comment by amartya89** [comment]
I am as of now running the tool coming with kali. Indeed -b gives lots of result against a domain. But after that if i try to search another domain, it hits 429 HTTP error. And once an i.p. is getting blocked , that i.p. i have checked is not getting opened even after 72 hours.

"If you use the latest versions you can provide more than one proxy and it will randomly select one per request", -- Does it mean, if i give 3 proxies and do a '-b', then google search, baidu, linkedin  etc all will randomly use one of the 3 proxies? 

Lastly, Thanks a lot for your community's very prompt response in order to help the users. I really appreciate your effort.

Regards

**Comment by amartya89** [comment]
Hi,

Waiting to hear from you please.

Regards,

**Comment by L1ghtn1ng** [comment]
Yes it will use one of the proxies

**Comment by amartya89** [comment]
Thanks. Also, in proxies.yaml can we only give https proxies and not https proxies? Would you please tell me why https proxies are not supported?

**Comment by amartya89** [comment]
Hi,

I have tried with multiple proxies and with multiple times. But observed one, thing, With proxy the email ids against a domain is much much less or negligible compared to without proxy search. 

Would you please give me an insight?

Thanks

**Comment by NotoriousRebel** [comment]
@amartya89 The reason it only supports HTTP proxies is because aiohttp does not support https [proxies](https://github.com/aio-libs/aiohttp/blob/62ecefee5ed45361fa6ff45bbdea4d3d254dfca9/docs/client_advanced.rst). We may look into [aiosocks](https://github.com/nibrag/aiosocks) for sock proxy support.
