### ISSUE TITLE
IPs not resolving for hostnames

### ISSUE THREAD

**Issue by darkmatter1505** [laramies/theHarvester#414]
**Feature Request or Bug or Other**
Bug 

**Describe the feature request or bug or other**
Whenever I run theHavester.py -d (somedomain) -b all, when it gets to the IPs found, it will give me a number of found IPs and then the following error message, "failed to detect a valid IP address from 'some host name' and the script quits. I'm running version 3.1.1dev3

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tool like this: theHavester.py -d (somedomain) -b all
2. See error: "failed to detect a valid IP address from 'some host name' 

**Expected behaviour**
The IPs and hostnames are shown and the script continues to run normally to its end.

**Screenshots**
If possible please add screenshots to help explain your problem.

**System Information (System that tool is running on):**
 - OS: Mac OS Catalina 
 - Version 10.15.4 (19E266)
![Screen Shot 2020-04-09 at 10 57 52 AM](https://user-images.githubusercontent.com/12475799/78915055-f97e5580-7a50-11ea-9af6-8ba50b1fd133.png)

**Additional context**

**Comment by darkmatter1505** [comment]
Additional screen capture.
![Screen Shot 2020-04-09 at 12 12 10 PM](https://user-images.githubusercontent.com/12475799/78922056-83332080-7a5b-11ea-8334-61bcd6a0f6c8.png)

**Comment by NotoriousRebel** [comment]
@darkmatter1505 Thank you for raising this to our attention, could you try with the latest version of the tool and let me know if those errors still exist?

**Comment by darkmatter1505** [comment]
Now I'm getting the following error under most of the searches:

Google is blocking your ip and the workaround, returning
Google is blocking your ip and the workaround, returning

Also getting IP's, emails, and hosts and the script appears to have ended normally.
![Screen Shot 2020-04-09 at 1 33 32 PM](https://user-images.githubusercontent.com/12475799/78928709-b6c77800-7a66-11ea-841e-99c986bcf592.png)

**Comment by L1ghtn1ng** [comment]
Make sure you have up to date tool dependencies as we have changed things in with the newer version and that the Google blocking part there is nothing we can do due to how Google detects scripts. That is why there is the proxy option for it
