### ISSUE TITLE
the suip

### ISSUE THREAD

**Issue by dafeifei2016** [laramies/theHarvester#417]
**Feature Request or Bug or Other**
Feature Request | Bug | Other

**Describe the feature request or bug or other**
A clear and concise description of what the bug, feature request,
or other request is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tool like this: '...'
2. See error

**Expected behaviour**

**Screenshots**
If possible please add screenshots to help explain your problem.

**System Information (System that tool is running on):**
 - OS: [e.g. Windows10]
 - Version [e.g. 2.7]

**Additional context**

**Comment by dafeifei2016** [comment]
the suip engine does not work when i type "python3 theHarevester.py -d ** -b suip", can you fix it ? Thanks a lot !

**Comment by NotoriousRebel** [comment]
1) Are you using the latest version of the tool?
2) Do you get results with suip if you use their website?

**Comment by L1ghtn1ng** [comment]
Timeout
