### ISSUE TITLE
[Bug|Feature Request|Other] Short Description of Issue

### ISSUE THREAD

**Issue by antihackme** [laramies/theHarvester#419]
getting an error saying Windows can't find harvester.html. How do i fix this error in windows 10?

**Comment by NotoriousRebel** [comment]
Are you using the most recent version of the tool and how are you using it?

**Comment by antihackme** [comment]
Hi,

Is there a guide online somewhere on how i can use theharvester on windows?

Regards,
*Dexter Ng *
Chief Technology Officer
Mobile: (65) 9878 8993  Address: 9 Craig Road, #03-01, S089669
Website: www.antihack.me <https://img.newoldstamp.com/r/7141/w> Email:
dexter@antihack.me Linkedin: https://www.linkedin.com/in/dexterng/
<https://www.facebook.com/antihack.me/> <https://twitter.com/AntihackMe>
<https://www.linkedin.com/company/antihackme/>

**Comment by NotoriousRebel** [comment]
@antihackme Thank you for reaching out I will test on Windows, it should be possible maybe without uvloop. If you have the windows subsystem for Linux on Windows I know the tool works there.

**Comment by NotoriousRebel** [comment]
Ok to get the tool working on Windows what you need to remove uvloop from [requirements/base.txt](https://github.com/laramies/theHarvester/blob/master/requirements/base.txt)
Uvloop does not currently support Windows if you try and pip install -r base.txt you will see this error:
![image](https://user-images.githubusercontent.com/36310667/81197733-a1bf0580-8f8e-11ea-89b2-85f77c61449e.png)
After you remove uvloop from base.txt you need to [theHarvester.py](https://github.com/laramies/theHarvester/blob/master/theHarvester.py) and comment out lines 7 and 15.
Please try these steps and let me know if the tool works.

**Comment by antihackme** [comment]
Hi,

Thanks so much for the help.... will need the linux subsystem for this to
work right?

Regards,
*Dexter Ng *
Chief Technology Officer
Mobile: (65) 9878 8993  Address: 9 Craig Road, #03-01, S089669
Website: www.antihack.me <https://img.newoldstamp.com/r/7141/w> Email:
dexter@antihack.me Linkedin: https://www.linkedin.com/in/dexterng/
<https://www.facebook.com/antihack.me/> <https://twitter.com/AntihackMe>
<https://www.linkedin.com/company/antihackme/>

**Comment by NotoriousRebel** [comment]
You will not need the Windows subsystem for Linux for this to work. If you wish to install the Windows subsystem for Linux that would bring the advantage of using uvloop as it currently doesn't support Widows.

**Comment by L1ghtn1ng** [comment]
Timeout
