### ISSUE TITLE
[Bug] Can't get xml output using docker on Kali

### ISSUE THREAD

**Issue by cagriaslan** [laramies/theHarvester#426]
**Describe the feature request or bug or other**
I installed theHarvester using docker as specified on wiki page. After I run the tool using the parameters below. I looked for the output but there wasn't any.

Steps to reproduce the behaviour:
1. Run tool like this: '`sudo docker run theharvester -d domain_name -b all -f harv.xml`'

**Expected behaviour**
I would like to get harv.xml with the results.

At the end this was the last outputs to the terminal.
```
[*] Reporting started.
[*] Reporting finished.
[*] Saving files.
[*] Files saved.
```

**System Information (System that tool is running on):**
Description:    Kali GNU/Linux Rolling
Release:          2020.2

**Additional context**
I did apt update and upgrade just before.

**Comment by NotoriousRebel** [comment]
1. Are you using the latest version of the tool?
2. If you run the tool as ```sudo docker run theharvester -d domain_name -b all -f harv``` does this work?

**Comment by cagriaslan** [comment]
1. It was the latest version as of while writing my problem. I cloned just before running to tool.
2. Didn't produced any output again. 
3. When I use it with venv it works btw.

**Comment by L1ghtn1ng** [comment]
@cagriaslan Sorry for taking a bit to reply, can you try it without the -b all and does it work if you use .html instead?

**Comment by L1ghtn1ng** [comment]
Ah just realized what you are doing, you need to do this to get the file out https://stackoverflow.com/questions/22049212/copying-files-from-docker-container-to-host

**Comment by cagriaslan** [comment]
Thanks!
