### ISSUE TITLE
Unable to open Database file

### ISSUE THREAD

**Issue by FernandoIV** [laramies/theHarvester#427]
Hi,
This happens after install on arch linux.
this is the command:
`theharvester -d tesla.com -b google` 
`returning exception unable to open database file
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aiosqlite/core.py", line 171, in run
    result = function()
  File "/usr/lib/python3.8/site-packages/aiosqlite/core.py", line 386, in connector
    return sqlite3.connect(loc, **kwargs)
sqlite3.OperationalError: unable to open database file
unable to open database file`

Thanks for your help

**Comment by NotoriousRebel** [comment]
If you do ls do you see a file called stash.sqlite?

**Comment by JOSBEAK** [comment]
can anyone please give me the solution.

**Comment by NotoriousRebel** [comment]
@JOSBEAK do you see a file called stash.sqlite? If you wish to interact with the database you can do  this:
![image](https://user-images.githubusercontent.com/36310667/81595539-a883b900-9390-11ea-91a0-2d0a190806e9.png)

**Comment by JOSBEAK** [comment]
all

> @JOSBEAK do you see a file called stash.sqlite? If you wish to interact with the database you can do this:
> ![image](https://user-images.githubusercontent.com/36310667/81595539-a883b900-9390-11ea-91a0-2d0a190806e9.png)

all i am able to see is this
![image](https://user-images.githubusercontent.com/59971421/81642836-d8c06b80-9413-11ea-82d0-4dd535df3e4d.png)
now what to do

**Comment by L1ghtn1ng** [comment]
I would suggest reporting that to parrot

**Comment by L1ghtn1ng** [comment]
As you are now getting a bug that is nothing to do with us as it is a parrot issue I am now going to close this

**Comment by BullsEye0** [comment]
Have the same problem with Anarchy Arch Linux
![2020-08-03_19-14](https://user-images.githubusercontent.com/33765660/89209129-fdb11e80-d5bd-11ea-9693-40124358c2f1.png)
