### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Gurnoor09** [laramies/theHarvester#428]
argument -d/--domain are required
please help to fix it

**Comment by L1ghtn1ng** [comment]
You need to specify a domain 

For example 

theHarvester.py -d google.com -b otx 

You can see more sources if you do theHarvester.py -h

**Comment by Gurnoor09** [comment]
![Screenshot 2020-05-11 at 1 32 44 PM 1](https://user-images.githubusercontent.com/64983842/81538432-60fb2e00-938c-11ea-9cff-fcd986ff4a80.png)
when I try starting theHarvester it shows this and automatically quits
Thanks
