### ISSUE TITLE
List modules in alphabetical order

### ISSUE THREAD

**Issue by leebaird** [laramies/theHarvester#43]
in the README file.

-baidu: Baidu search engine
-bing: microsoft search engine  - www.bing.com
-bingapi: microsoft search engine, through the API (you need to add your Key in
          the discovery/bingsearch.py file)
-google: google search engine  - www.google.com
-googleCSE: google custom search engine
-googleplus: users that works in target company (uses google search)
-google-profiles: google search engine, specific search for Google profiles
-linkedin: google search engine, specific search for Linkedin users
-pgp: pgp key server - pgp.rediris.es
-shodan: Shodan Computer search engine, will search for ports and banner of the
         discovered hosts  (http://www.shodanhq.com/)
-twitter: twitter accounts related to an specific domain (uses google search)
-vhost: Bing virtual hosts search
-yahoo: Yahoo search engine

**Comment by laramies** [comment]
Done
