### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by leebaird** [laramies/theHarvester#44]
When the tool is ran with no arguments, not all of the modules are listed.
Also place the modules in alphabetical order.

baidu - missing
bing
bingapi
google
googleCSE
googleplus
google-profiles
linkedin
pgp
shodan - missing
twitter
vhost - missing
yahoo - missing

dogpilesearch - not listed in README or tool
jigsaw - not listed in README

**Comment by laramies** [comment]
Done, thanks Lee!
