### ISSUE TITLE
spyse module not recognizing API key

### ISSUE THREAD

**Issue by leebaird** [laramies/theHarvester#441]
**Bug**

**Describe the feature request or bug or other**
[!] Missing API key. 
Key located in api-keys.yaml

**To Reproduce**
python3 theHarvester.py -d target.com -b spyse

**Expected behaviour**
A bunch of result.

**System Information**
 - OS: Kali Linux
 - Version 2020.2 rolling

**Comment by L1ghtn1ng** [comment]
it works for me no issues, you could try putting the file in /etc/theHarvester/api-keys.yaml and seeing if that fixes your issue?

**Comment by leebaird** [comment]
That fixed the problem!
