### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by overt-tech** [laramies/theHarvester#449]
Hello,

I installed the harvester via pipenv following the wiki and i got the following error messages when i try to do a search:

.local/share/virtualenvs/theHarvester-d_kUtoOx/lib/python3.7/site-packages/aiosqlite/core.py", line 171, in run
    result = function()

.local/share/virtualenvs/theHarvester-d_kUtoOx/lib/python3.7/site-packages/aiosqlite/core.py", line 386, in connector
    return sqlite3.connect(loc, **kwargs)
sqlite3.OperationalError: unable to open database file

It does seem to give results. although there are more problems when i expand my search queries. Has anyone come in contact with this particular problem and does anyone know how to fix this?

**Comment by L1ghtn1ng** [comment]
We have not come across this issue and cannot replicate it, what OS version are you running?
________________________________

**Comment by overt-tech** [comment]
I'm on Debian Buster.

**Comment by commandermoon** [comment]
I'm getting the same errors but installing without using pipenv and in Kali. And like OP, I do get some results. 



kali@kali:/opt/theHarvester$ cat ~/harvester.txt 
returning exception unable to open database file
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.8/site-packages/aiosqlite/core.py", line 171, in run
    result = function()
  File "/home/kali/.local/lib/python3.8/site-packages/aiosqlite/core.py", line 386, in connector
    return sqlite3.connect(loc, **kwargs)
sqlite3.OperationalError: unable to open database file
returning exception unable to open database file
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.8/site-packages/aiosqlite/core.py", line 171, in run
    result = function()
  File "/home/kali/.local/lib/python3.8/site-packages/aiosqlite/core.py", line 386, in connector
    return sqlite3.connect(loc, **kwargs)
sqlite3.OperationalError: unable to open database file
returning exception unable to open database file
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.8/site-packages/aiosqlite/core.py", line 171, in run
    result = function()
  File "/home/kali/.local/lib/python3.8/site-packages/aiosqlite/core.py", line 386, in connector
    return sqlite3.connect(loc, **kwargs)
sqlite3.OperationalError: unable to open database file
kali@kali:/opt/theHarvester$ uname -a
Linux kali 5.6.0-kali2-amd64 #1 SMP Debian 5.6.14-2kali1 (2020-06-10) x86_64 GNU/Linux

**Comment by NotoriousRebel** [comment]
@commandermoon Are you using the latest version of the tool? If you do ls, do you see a file called stash.sqlite? If so can you 
```sqlite3 stash.sqlite``` 
Does that command work for you? After that, can you delete the sqlite file and try running the tool?

**Comment by commandermoon** [comment]
@NotoriousRebel stash.sqlite did exist in my home dir and I was able to open with `sqlite3 stash.sqlite`. Just removed all references to theHarvester including deleting stash.sqlite. Did a fresh git clone and installed using option 3. After installing there was no stash.sqlite and running theHarvester gave an error related to the DB file.

Then installed via apt (this was how it was originally installed as default with Kali). This one worked without issue (although the pretty banner has one * out of line)

**Comment by L1ghtn1ng** [comment]
The banner had been fixed in git for ages just need to do a new release to get it in theHarvester
________________________________

**Comment by NotoriousRebel** [comment]
@overt-tech  + @commandermoon please see this [issue](https://github.com/gunthercox/ChatterBot/issues/1044) try running with sudo.

**Comment by L1ghtn1ng** [comment]
Timeout
