### ISSUE TITLE
ImportError: cannot import name htmlExport

### ISSUE THREAD

**Issue by TehProject26** [laramies/theHarvester#45]
```
root@kali:~# theharvester
Traceback (most recent call last):
  File "/usr/bin/theharvester", line 19, in <module>
    from lib import htmlExport
ImportError: cannot import name htmlExport
root@kali:~# 
```

Anyone have any ideas i have searched pip for htmlExport and even google with no wheel or questions on this issuse.

many thanks john

**Comment by initbar** [comment]
@TehProject26 I don't think `htmlExport` is a pip package. It should be [this](https://github.com/laramies/theHarvester/blob/master/lib/htmlExport.py).

I can't say for sure as I can't repro - but could you `asciinema` from a fresh clone?

**Comment by Phexcom** [comment]
I got a Fix for this issue.. 

nano /usr/bin/theHarvester

from  lib import *  
#from lib import htmlExport   #commented this out
#from lib import hostchecker   #commented this out


nano /usr/share/theharvester/lib/htmlExport.py

from lib import *
#from lib import markup #commented this out
#from lib import graphs #commented this out

**Comment by Zer0ne83** [comment]
Holy crap, thank you, @Phexcom!

**Comment by NotoriousRebel** [comment]
As this has been resolved, closing.
