### ISSUE TITLE
He doesn't seem to work properly

### ISSUE THREAD

**Issue by klionsec** [laramies/theHarvester#451]
# python3 theHarvester.py -d google.com

[*] No IPs found.
[*] No emails found.
[*] No hosts found.

**Comment by NotoriousRebel** [comment]
Are you using the latest version of the tool? Furthermore, you are not using the tool correctly you need to specify the -b parameter which indicates the data sources you want to use.  
For example
```python3 theHarvester.py -d google.com -b baidu,dopgile,bing```

**Comment by L1ghtn1ng** [comment]
I will do a change to fix stop people from missing the -b flag
