### ISSUE TITLE
[Feature?] Request about email found

### ISSUE THREAD

**Issue by John33000** [laramies/theHarvester#452]
Hi,

I use your tool and I have question. When you found email adress it's possible to know where you are found this adress ? For example : 

Tata@example.com found in Github
toto@example.com found in Linkdin
titi@example.com found in shodan 

Because if I found mail of my company for example my manager what I said ? I found your email and ??? And what ? It can be very good if I can tell him : I found your PROFESSIONNAL email in github and you are commercial no developper why you use your email professionnal ? You understand what I mean ? 

Best regards

**Comment by John33000** [comment]
And question, in report.html, we see this : RecordType Email, Source : Baidu Total Results : 3 ok it's very good but what is the 3 emails in Baidu ? Same thing for RecordType : host what is host ? Host = domain ? Please I want more details in report  it's possible ?

**Comment by NotoriousRebel** [comment]
@John33000 I'm glad you like the tool :). In regards to your inquiry you do not have to specify an output file to see where results are coming from. There is a sqlite3 database you can interact with to see where results are coming from:
Perhaps something like this is what you are looking for?

![image](https://user-images.githubusercontent.com/36310667/84837040-13b25200-b005-11ea-8978-e19ad0052e9e.png)

**Comment by John33000** [comment]
Hi, @NotoriousRebel 

I don't understand, this sqlite3 database it's for report html ? 
And if I want the source like : 

Email found : 1

tata@gmail.com from linkedin 

It's not possible ? In the CLI, no report ? For report I will look how it's works.

**Comment by NotoriousRebel** [comment]
The sqlite3 database is always there, for every result theHarvester obtains it is stored in a sqlite3 database that you can interact with. In that screenshot I am exporting all results from the table to a csv file called awesome.csv. If you want the source like teta@gmail.com from Linkedin that is in the report :). With the HTML report you can easily search for it. 
For example
```python3 theHarvester.py -d netflix.com -b intelx,bing,baidu,dogpile -f output -l 250```
Make sure you are using the latest version of the tool as well.

**Comment by John33000** [comment]
Hi @NotoriousRebel 

I will try to use your sqlite3 for get the email source in CLI. And yes I have the last version of your product.

Best Regards

**Comment by John33000** [comment]
Hi @NotoriousRebel 

When I do : `select * from results;` (like you) I have nothing, it's normal ? 

and the table result is the table of report html ? What is the table of result of the command : `python3 theHarvester.py -d netflix.com -b intelx,bing,baidu,dogpile -f output -l 250 `

And what is the limit of result with args '-l' ? 250 ? 500 ? 2 000 ?

Best Regards

**Comment by NotoriousRebel** [comment]
By default, if you do not specify -l it will be set to 500 which is a pretty good number. If you do:
```ls -las``` 
Does stash.sqlite exist and if it does exist (it should) is the size greater than 0? 
I just cloned the repo and ran that command the table did exist, without a screenshot of exactly how you are interacting with the sqlite database it is hard to help you further. Double check you are typing things correctly and to exit sqlite do ctrl + D.
![image](https://user-images.githubusercontent.com/36310667/85151136-6c5e3680-b221-11ea-9221-7116bc52fc60.png)

**Comment by John33000** [comment]
H @NotoriousRebel 

Last week I generate awesome.csv. Today I retry to generate it again after run TheHarvester but my file.csv is empty, you know why ? 

Sorry if you don't understand correctly my issue, my english is maybe bad. The result in awesome.csv with : test|IP|date|source is very good, but I need to connect in database. It's not to possible to modify TheHarvester script to see this in output of the command ? 

`python3 theHarvester.py -d test -l 500 -b all -f result.html`

Best regards

**Comment by John33000** [comment]
Sorry I have a other question, in api-keys.yaml it's possible to add others api key ? Like Facebook, Twitter or other ?

**Comment by L1ghtn1ng** [comment]
To add other api-keys to it you would need to create a module and then put it in there with the relevent code in certain files
________________________________

**Comment by John33000** [comment]
Hi @L1ghtn1ng 

Ok thank you

**Comment by John33000** [comment]
Hi @NotoriousRebel,

Can you give me an answer for my question please ? :

Sorry if you don't understand correctly my issue, my english is maybe bad. The result in awesome.csv with : test|IP|date|source is very good, but I need to connect in database. It's not to possible to modify TheHarvester script to see this in output of the command ?

`python3 theHarvester.py -d test -l 500 -b all -f result.html`

Best Regards

**Comment by L1ghtn1ng** [comment]
If you want to connect to the DB you connect to stash.sqlite and can read things from there using sqlite3 commands you should also checkout the the latest version from git as I think it has what you are looking for now in the result.html

**Comment by NotoriousRebel** [comment]
@John33000 just adding on to what L1ghtn1ng has already said. When you write results to the HTML and XML file previous scan results are also included. Please make sure you are using the latest version of the tool and make sure you are doing -d "yourdomain.tld"

**Comment by John33000** [comment]
Hi @NotoriousRebel 

I understand thank you. But my problem is I need to connect to stash.sqlite for see ALL result with ALL source. And I need to export this result in CSV. I would like this result with argument in the command. For exemple the -f generate the same report of stash.sqlite. I don't know it's more clearly sorry

Best regards
