### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by soupnatzi** [laramies/theHarvester#457]
Hi loving the tool and the new outlook was hoping to see if we can add more information to the reports example if we can add which hosts are alive or not or which hosts returned subdomain takeover in the reports but if am missed something and its already implemented please guide me in the right direction.

**Comment by NotoriousRebel** [comment]
Glad you're liking the tool :) You are right that subdomain takeover checking is not in the report should be pretty trivial to add. In regards to whether hosts are alive, we are planning on adding screenshot functionality to the tool so perhaps the best way would be to check if a host is alive via either the takeover or screenshot functionality as those are both active.

**Comment by soupnatzi** [comment]
@NotoriousRebel yea screenshots would really bring it together sort of like aquatone theharvester would definetly be my go to tool if implemented for sure.

**Comment by NotoriousRebel** [comment]
@soupnatzi the addition is essentially done just needs a tad more testing it is currently in my dev branch. You would just need to make sure to install requirements.txt as there are two additional packages used (aiomultiprocess + pyppeteer). 
You would also want to run this script if you do not have pyppeteer already installed as this will install the latest version of chromium.

```python
import asyncio
from pyppeteer import launch

async def main():
    browser = await launch()
    page = await browser.newPage()
    await page.goto('https://example.com')
    await page.screenshot({'path': 'example.png'})
    await browser.close()

asyncio.get_event_loop().run_until_complete(main())
```

I have been testing it like so: 

```py .\theHarvester.py -d netflix.com --screenshot D:\repos\theHarvester\theHarvester\screenshot\http -l 400 -b bing,duckduckgo,baidu,dogpile```

**Comment by L1ghtn1ng** [comment]
@soupnatzi Screenshots support has been added to git

**Comment by L1ghtn1ng** [comment]
closing this out
