### ISSUE TITLE
[Bug] SQLite error

### ISSUE THREAD

**Issue by unguest** [laramies/theHarvester#461]
**Feature Request or Bug or Other**
Bug

**Describe the feature request or bug or other**
An error occurs when launching the script and it's about sqlite.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tool like this: ./theHarvester.py -d microsoft -l 500 -b google -f test.txt
2. See error : 

returning exception unable to open database file
Traceback (most recent call last):
  File "/home/king-arthur/.local/lib/python3.8/site-packages/aiosqlite/core.py", line 171, in run
    result = function()
  File "/home/king-arthur/.local/lib/python3.8/site-packages/aiosqlite/core.py", line 386, in connector
    return sqlite3.connect(loc, **kwargs)
sqlite3.OperationalError: unable to open database file

**Expected behaviour**
Run the script and save results saved in test.txt.

**System Information (System that tool is running on):**
 - OS: Ubuntu
 - Version 20.04 LTS Focal Fossa

**Additional context**
Nothing more to say :)

**Comment by NotoriousRebel** [comment]
Are you using the latest version of the tool?

**Comment by unguest** [comment]
Yes, I've just clone it & made a git pull to be sure.

**Comment by NotoriousRebel** [comment]
Interesting, if you try with -d microsoft.com does anything change? 
Also if you do ls do you see a file called stash.sqlite?
Could you delete it and retry running? If there are important results there moveit to a separate directory.

**Comment by NotoriousRebel** [comment]
@unguest please see this [issue](https://github.com/gunthercox/ChatterBot/issues/1044), try running with sudo.

**Comment by unguest** [comment]
Oh nice it works well, thank you !
