### ISSUE TITLE
[Bug] Error with spyse

### ISSUE THREAD

**Issue by John33000** [laramies/theHarvester#464]
Hi,
TheHarvester version : theHarvester 3.2.0dev2

I have an error when Harvester asks Spyse : 
```
Searching results
An exception has occurred: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.spyse.com/v2/data/domain/subdomain?limit=100&domain=domain.fr')
An exception has occurred: string indices must be integers

```

I need to change something in code ? 

And why I have this : `Google is blocking your ip and the workaround, returning `
How I can repair that ?
It's juste my second request today.

Best regards

**Comment by L1ghtn1ng** [comment]
The spyse module needs to upgraded to V3 of the API and to get around the Google option you will need to use a proxy etc, there is not a lot we can do on that one unfortunately
________________________________
