### ISSUE TITLE
Whats the easiest way to install this on windows 10?

### ISSUE THREAD

**Issue by antihackme** [laramies/theHarvester#468]
Need help to install this on windows 10

**Comment by NotoriousRebel** [comment]
Head on over to the wiki and read the installation section.

**Comment by antihackme** [comment]
> Head on over to the wiki and read the installation section.

I went there... but which should i follow for windows? can't seem to get it to work on windows 10

**Comment by NotoriousRebel** [comment]
Without more details, it's a bit hard to tell. I am using Windows 10 and just cloned the repo and pip installed the requirements and the tool works just great.

**Comment by steve-bate** [comment]
I installed it on Window 10 (git clone, pip install) and it works fine.

**Comment by antihackme** [comment]
I installed latest python

tried doing pip command in cmd doesnt work
Regards,
*Dexter Ng *
Chief Technology Officer
Mobile: (65) 9878 8993  Address: 9 Craig Road, #03-01, S089669
Website: www.antihack.me <https://img.newoldstamp.com/r/7141/w> Email:
dexter@antihack.me Linkedin: https://www.linkedin.com/in/dexterng/
<https://www.facebook.com/antihack.me/> <https://twitter.com/AntihackMe>
<https://www.linkedin.com/company/antihackme/>

**Comment by NotoriousRebel** [comment]
@antihackme make sure pip is installed and that Python is in your path in environment variables.
