### ISSUE TITLE
failed to detect a valid IP address from 'ns2.namespace4you.de'

### ISSUE THREAD

**Issue by reb891** [laramies/theHarvester#470]
Hi,
I have the following issue when running theHarvester on my kali. 
[*] IPs found: 4
-------------------
failed to detect a valid IP address from 'ns2.namespace4you.de'

I tried varying configs for -l -e -d
 I already uninstalled and reinstalled it. 
sudo apt-get autoremove --purge theharvester
sudo apt get update && Sudo apt-get dist-upgrade 
sudo apt-get install theharvester

I tried another kali machine didn't work either.

**Comment by L1ghtn1ng** [comment]
Can you please install from git via 1 of the following https://github.com/laramies/theHarvester/wiki/Installation  and see if you have the issue still?

**Comment by L1ghtn1ng** [comment]
Do sudo pip3 install PyYaml
________________________________

**Comment by L1ghtn1ng** [comment]
TImeout
