### ISSUE TITLE
PGP keyserver

### ISSUE THREAD

**Issue by spyder-7** [laramies/theHarvester#48]
There is also something wrong with PGP key server.
When data source given as all it started with google and then pgp and then exits.
on checking the code for pgp module in discovery:
     self.server = "pgp.rediris.es:11371"
     self.hostname = "pgp.rediris.es"
both these links are not working, any help ??

Thanks,

**Comment by jamyoung** [comment]
Hi spyder-7, I have the same issue. Everything was working fine till my last dist-upgrade, and now some of my tools are broken. 
Please can somebody help.
Thanks

**Comment by boshox** [comment]
i will be waiting for the fix, i got the same problem.

**Comment by laramies** [comment]
Hi all, seems that the keyserver is down, I will look for an alternative service and update as soon as possible. Thanks for raising the issue.

**Comment by laramies** [comment]
Please check now, I changed the server.

**Comment by spyder-7** [comment]
Hi laramies,

Thanks, PGP Search now says "404 NOT found" but atleast harvester is not exiting at PGP now.

Here is the output:
[-] Searching in PGP Key server..
404
Not found
[-] Searching in Bing..
	Searching 50 results...

Thank you any way for quick fix.

**Comment by laramies** [comment]
Hmm, something is wrong with the new server, depending on the domain you are looking fro it gets an error or the results. I will dig into other options this week.

**Comment by reubadoob** [comment]
Any ETA on a fix?

**Comment by raiderng** [comment]
I need some help with a problem I have with hackers I'm in desperate need
of some white hats because children are in danger.

**Comment by laramies** [comment]
The problem is not in theHarvester, is in the PGP key servers, if you try to search for domains like apple.com or microsoft.com servers like pgp.mit.edu will provide an error handling, some domains with little results will work.. seems that servers fails when domains have lots of results.

**Comment by lux-lth** [comment]
I still have the problem using last version of theHarvester master branch
