### ISSUE TITLE
[Bug] Xml Report failing with ipv6

### ISSUE THREAD

**Issue by Agammonn** [laramies/theHarvester#487]
**Feature Request or Bug or Other**
Bug

**Describe the feature request or bug or other**
If IPv6 are found, the program will crash during the creation of the XML report with error `too many values to unpack (expected 2)`

**To Reproduce**
`./theHarvester.py -d <domain> -b all -f out.xml`

**System Information (System that tool is running on):**
 - Version 3.2.0dev3     

**Possible fix**
The problem come from `__main__.py`
https://github.com/laramies/theHarvester/blob/1e61d8cf295b3704c91b1674256de607468e50d4/theHarvester/__main__.py#L698-L716
changing `x.split(':')` line 706 & 712 to `x.split(':',1)` seems to correct the issue.

**Comment by NotoriousRebel** [comment]
Thank you for creating this issue, could you perhaps create a PR with the fix?

**Comment by L1ghtn1ng** [comment]
closing as this has been fixed in master
