### ISSUE TITLE
[Feature Request] Support for local user installation

### ISSUE THREAD

**Issue by VainlyStrain** [laramies/theHarvester#497]
**Feature Request or Bug or Other**
Feature Request

**Describe the feature request or bug or other**
I'd be nice to provide a local installation method without relying on sudo. If running `$python setup.py install --user`, it will try to create a config file in /etc, which will result in a permission denied error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the base and/or developer dependencies.
2. Run `$python setup.py install --user`
3. See error

**Expected behaviour**
There would be created a local configuration file, so that installation passes without sudo.

**System Information (System that tool is running on):**
 - OS: Fedora Linux 32, 64bit
 - Python Version: 3.8.5
 - theHarvester version: latest

**Comment by NotoriousRebel** [comment]
Any suggestions of where the config file should be placed as an alternative?

**Comment by L1ghtn1ng** [comment]
You can just run everything from the git clone as long as you have dependencies installed
________________________________

**Comment by VainlyStrain** [comment]
@NotoriousRebel `~/.config` would be a good place
@L1ghtn1ng yes, I'm currently using it like that :+1:

**Comment by L1ghtn1ng** [comment]
Easy enough for me to sort out, he says 😅 will look at this tomorrow

**Comment by L1ghtn1ng** [comment]
Okay so having a look at this, we are following debain/posix packaging when it comes to this and after further consideration I do not see a clean way of adding support for this without making the code be a mess, which I do not want the code to be or to have to maintain that mess so unfortunately this will not be supported
