### ISSUE TITLE
theHarvester.py: command not found

### ISSUE THREAD

**Issue by duranetworks** [laramies/theHarvester#501]
Hello PLease help,

I installed theharvester with:

Option 4 - From Source (With Pipenv)

The fourth option is building from source and using pipenv. If you need help with pipenv look here
Make sure you are using Python3.7+

    $ ~ > git clone https://github.com/laramies/theHarvester 
    $ ~ > cd theHarvester
    $ ~ > python3 -m pip install pipenv
    $ ~ > pipenv install 
    $ ~ > pipenv shell
    $ ~ > python3 theHarvester.py -h
everything seem to worked well, till i tried to test it and it gave same error message "theHarvester.py: command not found"

i used all the possible combinations;
theharvester -d gmail.com -l 100 -b google
theharvester.py -d gmail.com -l 100 -b google
theHarvester -d gmail.com -l 100 -b google
theHarvester.py -d gmail.com -l 100 -b google

Please any suggestions on how to make it work?

**Comment by duranetworks** [comment]
Im using a linux mint 19.2 cinnamon 64bit

**Comment by sundruid** [comment]
Make sure you're in the theHarvester directory and then use a ./theHarvester.py <args> to execute. You may also need to call python3 as well instead of the ./ notation.

**Comment by L1ghtn1ng** [comment]
please do what @sundruid mentioned
