### ISSUE TITLE
whois error

### ISSUE THREAD

**Issue by shanow7** [laramies/theHarvester#503]
hi, I've heve this

[!] Whois Lookup : 

/usr/local/lib/python3.8/dist-packages/ipwhois/net.py:138: UserWarning: allow_permutations has been deprecated and will be removed. It is no longer needed, due to the deprecation of asn_alts, and the addition of the asn_methods argument.
  warn('allow_permutations has been deprecated and will be removed. '
/usr/local/lib/python3.8/dist-packages/ipwhois/asn.py:178: UserWarning: IPASN._parse_fields_dns() has been deprecated and will be removed. You should now use IPASN.parse_fields_dns().
  warn('IPASN._parse_fields_dns() has been deprecated and will be '
/usr/local/lib/python3.8/dist-packages/ipwhois/whois.py:586: UserWarning: Whois._get_nets_other() has been deprecated and will be removed. You should now use Whois.get_nets_other().
  warn('Whois._get_nets_other() has been deprecated and will be '
/usr/local/lib/python3.8/dist-packages/ipwhois/whois.py:333: UserWarning: Whois._parse_fields() has been deprecated and will be removed. You should now use Whois.parse_fields().
  warn('Whois._parse_fields() has been deprecated and will be '

can you help?

**Comment by L1ghtn1ng** [comment]
We do not even use that package, what version are you running?
________________________________

**Comment by shanow7** [comment]
3.2.0dev3

**Comment by shanow7** [comment]
I've problem with google he's blocking my IP 

[*] Searching Baidu. 
Google is blocking your ip and the workaround, returning
        Searching 0 results.
[*] Searching Trello. 
Google is blocking your ip and the workaround, returning
        Searching 0 results.
[*] Searching CRTsh. 
[*] Searching Hackertarget. 
        Done Searching Results
[*] Searching SecurityTrails. 
[*] Searching Threatcrowd. 
Google is blocking your ip and the workaround, returning
        Searching 100 results.
[*] Searching Netcraft. 
[*] Searching Otx. 
Google is blocking your ip and the workaround, returning
        Searching 0 results.
[*] Searching Bing. 
        Searching results.
[*] Searching Certspotter. 
        Searching 100 results.
Google is blocking your ip and the workaround, returning
        Searching 200 results.
Google is blocking your ip and the workaround, returning
Google is blocking your ip and the workaround, returning
Google is blocking your ip and the workaround, returning
        Searching 300 results.
        Searching 100 results.
        Searching 200 results.
Google is blocking your ip and the workaround, returning
        Searching 400 results.
Google is blocking your ip and the workaround, returning
Google is blocking your ip and the workaround, returning
        Searching 200 results.
        Searching 300 results.
Google is blocking your ip and the workaround, returning
        Searching 500 results.
[*] Searching Google. 
Google is blocking your ip and the workaround, returning
Google is blocking your ip and the workaround, returning
        Searching 300 results.
        Searching 400 results.
An exception has occurred: 
[*] Searching Rapiddns. 
Google is blocking your ip and the workaround, returning
Google is blocking your ip and the workaround, returning
        Searching 400 results.
        Searching 500 results.

**Comment by L1ghtn1ng** [comment]
Google detects it is a script running and then blocks your requests, not a lot we can do with that unfortunately
________________________________

**Comment by L1ghtn1ng** [comment]
As there is nothing we can do with this and am not getting that error with my setup unless you provide reproduce steps, will close this out

**Comment by shanow7** [comment]
kali:/opt/theHarvester$ sudo python3 theHarvester.py -d ptchc.pl -b all


*******************************************************************
*  _   _                                            _             *                                                                                        
* | |_| |__   ___    /\  /\__ _ _ ____   _____  ___| |_ ___ _ __  *                                                                                        
* | __|  _ \ / _ \  / /_/ / _` | '__\ \ / / _ \/ __| __/ _ \ '__| *                                                                                        
* | |_| | | |  __/ / __  / (_| | |   \ V /  __/\__ \ ||  __/ |    *                                                                                        
*  \__|_| |_|\___| \/ /_/ \__,_|_|    \_/ \___||___/\__\___|_|    *                                                                                        
*                                                                 *                                                                                        
* theHarvester 3.2.0dev3                                          *                                                                                        
* Coded by Christian Martorella                                   *                                                                                        
* Edge-Security Research                                          *                                                                                        
* cmartorella@edge-security.com                                   *                                                                                        
*                                                                 *                                                                                        
*******************************************************************                                                                                        
                                                                                                                                                           
                                                                                                                                                           
[*] Target: ptchc.pl 
                                                                                                                                                           
An exception has occurred in PentestTools search: 'pentestTools'
[*] Searching Spyse. 
[*] Searching Dogpile. 
[*] Searching Netcraft. 
        Searching 100 results.
[*] Searching Intelx. 
        Searching 0 results.
[*] Searching Rapiddns. 
        Searching results.
[*] Searching Hunter. 
[*] Searching Dnsdumpster. 
        Searching 100 results.
[*] Searching Virustotal. 
[*] Searching Threatminer. 
        Searching 200 results.
[*] Searching Duckduckgo. 
        Searching 200 results.
[*] Searching Otx. 
        Searching results.
[*] Searching Certspotter. 
[*] Searching Sublist3r. 
        Searching 300 results.
[*] Searching Bufferoverun. 
        Searching 300 results.
[*] Searching CRTsh. 
        Searching 400 results.
        Searching 400 results.
[*] Searching Baidu. 
        Searching 500 results.
[*] Searching Google. 
        Searching 0 results.
[*] Searching Bing. 
Google is blocking your ip and the workaround, returning
[*] Searching Threatcrowd. 
Google is blocking your ip and the workaround, returning
        Searching 500 results.
[*] Searching Linkedin. 

[*] Users found: 23
---------------------
Amat Cama 
Angie Teh - Senior Business Systems Analyst 
Barry Young - Retail Operations Manager 
Beth Butcher - Office Assistant 
Bill Martin - Principal Planner 
Bryce Holland - Service Coordinator 
Greater New York City Area 
Greater San Diego Area 
Janice Poling - Office Manager 
Joanna Erdman 
Jose Orozco - North America 
Julia V. - Lead Patient Access Coordinator 
Julie Kimithi - College Administrator 
Liesl Theron - Global Rights Summit Consultant 
Marcia Ramdass - Nurse 
Michael Anthony Pomante 
Mike Morasco - Director 
Tracy W. - Interim Service Manager 
Yolanda Sanchez - Home Health Aide 
Your search 
anna aranovich - rn 
Searching results
        Searching 100 results.
        Done Searching Results
[*] Searching SecurityTrails. 
[*] Searching Bing. 
[*] Searching Hackertarget. 
[*] Searching Urlscan. 
        Searching 0 results.
[*] Searching Github-code. 
Google is blocking your ip and the workaround, returning
[*] Searching Exalead. 
        Searching 200 results.
Google is blocking your ip and the workaround, returning
        Searching 0 results.
[*] Searching Trello. 
Google is blocking your ip and the workaround, returning
        Searching 300 results.
Google is blocking your ip and the workaround, returning
        Searching 400 results.
Google is blocking your ip and the workaround, returning
        Searching 500 results.

**Comment by L1ghtn1ng** [comment]
Can you try the latest version from git please and see if that works?
________________________________

**Comment by shanow7** [comment]
theHarvester$ sudo python3 theHarvester.py -d ptchc.pl -b all

*******************************************************************
*  _   _                                            _             *                                                                                        
* | |_| |__   ___    /\  /\__ _ _ ____   _____  ___| |_ ___ _ __  *                                                                                        
* | __|  _ \ / _ \  / /_/ / _` | '__\ \ / / _ \/ __| __/ _ \ '__| *                                                                                        
* | |_| | | |  __/ / __  / (_| | |   \ V /  __/\__ \ ||  __/ |    *                                                                                        
*  \__|_| |_|\___| \/ /_/ \__,_|_|    \_/ \___||___/\__\___|_|    *                                                                                        
*                                                                 *                                                                                        
* theHarvester 3.2.0dev5                                          *                                                                                        
* Coded by Christian Martorella                                   *                                                                                        
* Edge-Security Research                                          *                                                                                        
* cmartorella@edge-security.com                                   *                                                                                        
*                                                                 *                                                                                        
*******************************************************************                                                                                        
                                                                                                                                                           
                                                                                                                                                           
[*] Target: ptchc.pl 
                                                                                                                                                           
An exception has occurred in PentestTools search: 'pentestTools'
[*] Searching Bing. 
[*] Searching CRTsh. 
[*] Searching Hackertarget. 
        Searching results.
[*] Searching Suip this module can take 10+ min but is worth it. 
[*] Searching Otx. 
        Searching results.
[*] Searching Dnsdumpster. 
[*] Searching Virustotal. 
        Searching 0 results.
[*] Searching Bing. 
[*] Searching Threatcrowd. 
[*] Searching Urlscan. 
[*] Searching Intelx. 
[*] Searching Bufferoverun. 
        Searching 0 results.
[*] Searching Baidu. 
[*] Searching Sublist3r. 
[*] Searching Github-code. 
[*] Searching Rapiddns. 
[*] Searching Duckduckgo. 
[*] Searching Hunter. 
        Searching results.
[*] Searching Certspotter. 
Searching results
        Searching 500 results.
[*] Searching Qwant. 
Google is blocking your ip and the workaround, returning
[*] Searching Spyse. 
        Searching 100 results.
        Done Searching Results
[*] Searching SecurityTrails. 
Google is blocking your ip and the workaround, returning
        Searching 0 results.
[*] Searching Exalead. 
[*] Searching Threatminer. 
[*] Searching Dogpile. 
Google is blocking your ip and the workaround, returning
Google is blocking your ip and the workaround, returning
        Searching 100 results.
Google is blocking your ip and the workaround, returning
        Searching 100 results.
        Searching 200 results.
Google is blocking your ip and the workaround, returning
        Searching 0 results.
[*] Searching Trello. 
[*] Searching Netcraft. 
Google is blocking your ip and the workaround, returning
        Searching 200 results.
Google is blocking your ip and the workaround, returning
Google is blocking your ip and the workaround, returning
        Searching 300 results.
        Searching 200 results.
Google is blocking your ip and the workaround, returning
        Searching 300 results.
Google is blocking your ip and the workaround, returning
Google is blocking your ip and the workaround, returning
        Searching 400 results.
        Searching 300 results.
Google is blocking your ip and the workaround, returning
        Searching 400 results.
Google is blocking your ip and the workaround, returning
        Searching 500 results.
[*] Searching Linkedin. 

[*] No users found.


Google is blocking your ip and the workaround, returning
Google is blocking your ip and the workaround, returning
        Searching 500 results.
[*] Searching Google. 
        Searching 400 results.
Google is blocking your ip and the workaround, returning
        Searching 500 results.
[*] Searching Linkedin. 

[*] No links found.



[*] IPs found: 5
-------------------
51.77.66.153
54.38.194.82

[*] No emails found.

[*] Hosts found: 99
---------------------
autoconfig.ptchc.pl
autoconfig.ptchc.pl:51.77.66.153
autodiscover.ptchc.pl
autodiscover.ptchc.pl:51.77.66.153
discover.ptchc.pl:51.77.66.153
discover.ptchc.pl
haslo.ptchc.pl
haslo.ptchc.pl:51.77.66.153
imap.ptchc.pl
imap.ptchc.pl:51.77.66.153
mail.ptchc.pl
mail.ptchc.pl:51.77.66.153
mua.ptchc.pl:2001:41d0:700:2499::7
mua.ptchc.pl:51.77.66.153
mx1.ptchc.pl:2001:41d0:700:2499::1
mx1.ptchc.pl:51.77.66.153
poczta.ptchc.pl
poczta.ptchc.pl:51.77.66.153
pop3.ptchc.pl
pop3.ptchc.pl:51.77.66.153
ptchc.pl:mx1.ptchc.pl
smtp.ptchc.pl
smtp.ptchc.pl:51.77.66.153
ssp.ptchc.pl
ssp.ptchc.pl:51.77.66.153
webmail.ptchc.pl
webmail.ptchc.pl:51.77.66.153
wm.ptchc.pl
wm.ptchc.pl:51.77.66.153
ww.ptchc.pl:54.38.194.82
ww.ptchc.pl
www.ptchc.pl:54.38.194.82error input is invalid
www.ptchc.pl:54.38.194.82
www.ptchc.pl:2001:41d0:602:1952::11
wwww.ptchc.pl
wwww.ptchc.pl:54.38.194.82
zmiana-hasla.ptchc.pl:51.77.66.153
zmiana-hasla.ptchc.pl
zmianahasla.ptchc.pl:51.77.66.153
zmianahasla.ptchc.pl
zmien-haslo.ptchc.pl
zmien-haslo.ptchc.pl:51.77.66.153
zmienhaslo.ptchc.pl:51.77.66.153
zmienhaslo.ptchc.pl

[*] No Trello URLs found.

**Comment by L1ghtn1ng** [comment]
Do not see an issue, Google blocks your IP as it has detected you are running a script and Trello uses Google so not sure what can be done
________________________________

**Comment by shanow7** [comment]
and why Google is not blocking you?

**Comment by L1ghtn1ng** [comment]
As it detects basically that we are being a bot, and you would need to have a request being done each time from a different IP each time, will need to have a word with the team to see if we swap Google out for something else that can be less of a pain
________________________________

**Comment by shanow7** [comment]
thx :)

**Comment by L1ghtn1ng** [comment]
Closing
