### ISSUE TITLE
Help With That asyncio library

### ISSUE THREAD

**Issue by mina2222** [laramies/theHarvester#513]
Traceback (most recent call last):
  File "theHarvester.py", line 6, in <module>
    import asyncio
ImportError: No module named asyncio
what should i do!?

**Comment by mina2222** [comment]
i'm using termux !?how about that!?

**Comment by L1ghtn1ng** [comment]
Ah on Android um yeah that is not officially supported, I unfortunately have no idea on that one
________________________________

**Comment by NotoriousRebel** [comment]
@mina2222 maybe issue #499 may be useful.
