### ISSUE TITLE
No results after search

### ISSUE THREAD

**Issue by Concat-conris** [laramies/theHarvester#518]
I saw some people with the same problem but I didn´t see how they fixed. 
All the results are empty. 
Some people said to change the -b, like change google to bing or something like this, well, I´ve tried all the sources and nothing worked.

I´m with the lastest pythons´ versions. 
If anyone knows how to fix, pls help me.

![hvstr](https://user-images.githubusercontent.com/70733981/92193124-eb850300-ee3d-11ea-8a13-9c80d224530e.PNG)
![hvstr2](https://user-images.githubusercontent.com/70733981/92193211-20915580-ee3e-11ea-84e1-11d8afa302ff.PNG)

**Comment by L1ghtn1ng** [comment]
Please look at using the git version as that has lots of fixes and improvements and read the wiki install guide
________________________________

**Comment by Concat-conris** [comment]
For everyone who has the same issue, here is the tip that I´ve solved today. Just upgrade the kali version.
Here the lines to use in kali:

you can see the version with: 
 -->   cat etc/apt/sources.list

after:
 --> sudo apt-get update    // here will download all the stuff you need upate in kali

after:
 --> sudo apt-get upgrade  //here will start to update all tools inside your kali, it will take a while(me around 30 minutes)

If you´re using a virtual machine like VirtualBox, in the final will ask to keep without install  the grub and you can keep the installation without.

Hope help everyone, I learned it today lol
THX
