### ISSUE TITLE
system install (as a module) support and setup.py for easier installation

### ISSUE THREAD

**Issue by blshkv** [laramies/theHarvester#52]
There are few minor changes would be required. Something like this:

```
sed -e 's|from discovery|from theHarvester.discovery|' -i theHarvester.py || die "sed failed"
sed -e 's|from lib|from theHarvester.lib|' -i theHarvester.py || die "sed failed"
sed -e 's|from lib|from theHarvester.lib|' -i lib/htmlExport.py || die "sed failed"
for i in discovery/*.py; do
     sed -e 's|import myparser|from theHarvester import myparser|' -i $i || die "sed for $i failed"
done
touch __init__.py
```

**Comment by blshkv** [comment]
I noted that there is a new sqlite database in use. That should be installed into homedir ~/.theHarverster . The wordlist can be installed into a shared directory.

**Comment by NotoriousRebel** [comment]
@blshkv would you want to create an install.sh for this? There is currently a dockerfile and you can also git clone it.

**Comment by blshkv** [comment]
no, that would be a wrong approach. It has to be setup.py which should list the required dependencies and define system location of all files. The tool should also support system-wide installation, i.e. installed under root into ```/usr/share``` or ```/usr/lib{32,64}``` and a regular user should be able to run it. That would also require  to move all write operations (database, outputs) from a ```current``` directory into ```~/.theHarvester``` or similar.

**Comment by NotoriousRebel** [comment]
@blshkv would you want to work on this and submit a pull request?

**Comment by blshkv** [comment]
Sorry, I don't have bandwidth for development of other tools. Just a simple bug reporting (like this issue) and maintaining hundreds  of packages takes a fair amount of time which I could afford.

**Comment by L1ghtn1ng** [comment]
Hi All, I have updated the documentation for the dependencies but it needs to be merge and when you run the tool for the first time it creates the sqlite DB

**Comment by L1ghtn1ng** [comment]
@blshkv My changes have been merged can you take a look at the README.md please?

**Comment by blshkv** [comment]
Not sure what to look for. Does the tool support system install using setup.py?
No.

Will it only from the current folder? Yes. 
 So nothing changed

**Comment by L1ghtn1ng** [comment]
The dependencies section and will look to getting the Kali patch upstreamed which should fix this
________________________________

**Comment by blshkv** [comment]
I have tried it, still long way to go.

```
setup.py is a python file, which usually tells you that the module/package you are about to install has been packaged and distributed with Distutils, which is the standard for distributing Python Modules.

This allows you to easily install Python packages. Often it's enough to write:

$ python setup.py install
and the module will install itself.
```

https://docs.python.org/3/installing/index.html#installing-index

**Comment by NotoriousRebel** [comment]
@blshkv what do you think of the PR for setup.py?

**Comment by blshkv** [comment]
I have tried to convert the harvester into a proper python module but this is a major re-design and I'm unable to test all functions. As I said, I have no time to rewrite it, however I will be happy to test your progress. I can also help with minor fixes, once the direction of the development is clear.

**Comment by leebaird** [comment]
Please review the new setup.py file that was added. Would like to close out this ticket.

**Comment by blshkv** [comment]
Tested and failed. Have you  tested at all?
The current setup.py doesn't install  ```wordlists``` folder and ```theHarvester.py```.
I copied the binary into /usr/bin manually but the tool failed to start:
```
$ theHarvester.py 
Traceback (most recent call last):
  File "/usr/bin/theHarvester.py", line 3, in <module>
    from discovery import *
  File "/usr/lib64/python3.6/site-packages/discovery/shodansearch.py", line 3, in <module>
    from shodan import exception
ModuleNotFoundError: No module named 'shodan
```

You need to convert paths etc. Still  longs way to go

**Comment by blshkv** [comment]
Regarding the wordlists, please use the following example:
https://github.com/derv82/wifite2/issues/102
They used ```data_files``` function for this purpose

**Comment by NotoriousRebel** [comment]
@blshkv please try now I tested it after the most recent commit and it seems to be working :)

**Comment by blshkv** [comment]
worldlist files are installed into an unusual location: ```/usr/worldlist``` now, all other issues are not fixed

**Comment by blshkv** [comment]
FYI, you can debug it with the following command:
```python3 setup.py install --user```

**Comment by blshkv** [comment]
https://github.com/laramies/theHarvester/pulls
I have started to redesign the tool here, let's see if you agree with it.

**Comment by blshkv** [comment]
https://github.com/vulnersCom/getsploit/pull/14/files

**Comment by NotoriousRebel** [comment]
@blshkv if you are satifised with the changes that have happened feel free to close :)

**Comment by blshkv** [comment]
@NotoriousRebel thank you for accepting the patch. That would be the first stage, I can install the tool as a system package now (using root account). The second stage is to redirect all output to a userdir, something like ~/.theHarvester so a regular user would be able to run it without touching system files

**Comment by L1ghtn1ng** [comment]
@blshkv Would you agree that this issue could be closed now? As I think we now for fill the subject of this thread and open a new thread to do with the other bits and pieces that you have mentioned.

**Comment by blshkv** [comment]
Ok, sure. Thanks for accepting my patch once again
