### ISSUE TITLE
[BUG] theHarvester fails with multiple errors in Kali 2020.3

### ISSUE THREAD

**Issue by Slad3G** [laramies/theHarvester#530]
Bug

**Describe the feature request or bug or other**

An exception has occurred in PentestTools search: 'pentestTools'
string indices must be integers
sys:1: RuntimeWarning: coroutine 'start.<locals>.store' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tool like this: `python3 ./theHarvester.py -d domain.com -f domain.html -b all`
2. See error:
An exception has occurred in PentestTools search: 'pentestTools'
**string indices must be integers
sys:1: RuntimeWarning: coroutine 'start.<locals>.store' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback**

**Expected behaviour**
The tool should run and produce output on the specified domain

**System Information (System that tool is running on):**
 - Kali 2020.3 from a directory with the cloned repo and also with the system installed version

**Additional context**
The first lines regarding an exception change and sometimes isn't even present, the other lines are always there.

**Comment by L1ghtn1ng** [comment]
Can you try it like this please? python3 ./theHarvester.py -d
domain.com  -b all -f domain.html

**Comment by Slad3G** [comment]
Thanks for the prompt response, please see the ouput below from both the repo directory (/opt) and the native install in /etc.
![harvester2](https://user-images.githubusercontent.com/15789694/93501170-157d0180-f8e3-11ea-9676-1c82389d425f.PNG)

**Comment by L1ghtn1ng** [comment]
Does things work correctly if you do not use -b all
________________________________

**Comment by Slad3G** [comment]
L1tghtn1ng,

The sequence does complete without that switch.
SG

![harvester3](https://user-images.githubusercontent.com/15789694/93507019-14e86900-f8eb-11ea-9453-d0710490cf5c.PNG)

**Comment by L1ghtn1ng** [comment]
Can you pick 1 or 2 sources and see how that goes?
________________________________

**Comment by Slad3G** [comment]
It works fine with bing, google, duckduckgo. I will go through each individual source and see where the failure is.

**Comment by Slad3G** [comment]
Team,

It is the github_code source causing the failure, removing that allows the tool to complete.

S

**Comment by L1ghtn1ng** [comment]
Thanks for looking into it
________________________________

**Comment by L1ghtn1ng** [comment]
@Slad3G I cannot replicate your error as when I run it ./theHarvester.py -d microsoft.com -b github-code -f results.html it works fine. I suggest that you look at your API token and you need to use a personal access token with read privs on a few things and it works fine

**Comment by L1ghtn1ng** [comment]
Timeout

**Comment by 0xhughes** [comment]
> 
> 
> similar error is seen...
> result: An error occurred with Shodan: string indices must be integer
> error: API key in /etc/theHarvester/api-keys.yaml w/o space between key: and key itself
> fix: add missing space

Had the same issue, adding the space between the key value in the api yaml file and "key:" fixed the error. I see the issue was just timed out in this issue - but that seemed to be the issue pairing the original poster's symptoms as I had experienced them.

**Comment by NotoriousRebel** [comment]
@0xhughes Please try with the latest version of the tool and let us know if you have the same issue.

**Comment by 0xhughes** [comment]
I had encountered OP's error with a copy of this repository cloned yesterday, and the fix was applied yesterday and worked.

**Comment by NIRVANIAN472821** [comment]
Damn, im going through this issue again. rip

**Comment by NotoriousRebel** [comment]
@NIRVANIAN472821 Are you using the latest version of the tool?

**Comment by NIRVANIAN472821** [comment]
> @NIRVANIAN472821 Are you using the latest version of the tool?

Oh, I'm not sure... But I'm using the latest version of Kali linux (2021.2) on VMbox.

**Comment by NotoriousRebel** [comment]
If you do `python3 theHarvester.py -h` it will show the current version, if you are using the latest version it will print 4.0.0

**Comment by 0xhughes** [comment]
Using version 4.0, I entered API keys for Shodan, BinaryEdge, Hunter, and Github - without spaces between the API key values and the colons in the API YAML file. I ran for those four sources only against a domain, and received the originally described error.

I changed the API YAML file to include the spaces between the API keys and the colons, re-ran with the same sources against the same domain, and it worked without error.

Using Python 3.9 in Windows 10 x64 with all requirement modules installed before execution, again, in harvester version 4.0 as denoted by the -h flag mentioned above.

**Comment by NIRVANIAN472821** [comment]
> If you do `python3 theHarvester.py -h` it will show the current version, if you are using the latest version it will print 4.0.0

I'm using the latest version of the harvest (4.0.0)... Stated on the harvester execution.

I might just use a specific proxy to get a proper and working API.

**Comment by ishmailrealism** [comment]
having the same issues as well. don't know when this started, but i've tried uninstalling and reinstalling and now receive this error:

sys:1: RuntimeWarning: coroutine 'start.<locals>.store' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by facebookstaff** [comment]
apt install python3.9-full should fix your problem
