### ISSUE TITLE
Rate limit information

### ISSUE THREAD

**Issue by cryptocodyclub** [laramies/theHarvester#54]
Is there any way to determine when you have been rate limited with the script?

For example I want to get some emails and it would be useful to know that instead of the script returning 0 results, which could mean it didn't find any, or that I'm rate limited. That I could get get some feedback from the results saying it was limited.

**Comment by NotoriousRebel** [comment]
This has just been implemented sorry for taking so long! The only thing that usually limits requests is Google but we are working on it. 
Closing.
