### ISSUE TITLE
cannot see clearly output

### ISSUE THREAD

**Issue by dondon210** [laramies/theHarvester#55]
hello, 

if i try theharvester with sudo theharvester.py -d domainname.* -b all

but the output is not clear at all like : 

n"  div class "ftrD" id "ftrD_Language"  a class "b_toggle" role "menuitem" href " search?q %40ludia.* amp count 50 amp adlt strict amp lf 1 amp qpvt %40ludia.*" h "ID SERP,5815.1" Only English  a  a class 

cause i want to search with all the top level domain , maybe i do something wrong i have tryed to search in google ...

And finally how to search : -d recrutement@*.sometopleveldomain
I dont want to spam but just to find an internship, sorry if i'm not at the good place.

Best regards.

**Comment by NotoriousRebel** [comment]
@dondon210 has this been fixed, sorry for late reply. 
Try running as seen in the examples and output should be just fine!

**Comment by NotoriousRebel** [comment]
As this has been resolved, closing!
