### ISSUE TITLE
Cannot use socks proxy

### ISSUE THREAD

**Issue by kdlsw** [laramies/theHarvester#56]
Due to the working environment, I have to use a proxy to get to internet, so I set up a ssh dynamic tunnel on port 1080, and put it into my kali linux system proxy setting.
This is what came up when I try to run theharvester
input `theharvester -d google.com -b all`
output 
`Full harvest..
[-] Searching in Google..
Unable to determine SOCKS version from socks://127.0.0.1:1080/
`
Can someone please give some advice, thanks

**Comment by kdlsw** [comment]
I figured it out, when I change the SET all_proxy and ALL_PROXY from `socks://127.0.0.1:1080/`to `socks5://127.0.0.1:1080/` it works. But since github cannot allow delete an issue...I will just leave it here

**Comment by mzx5464** [comment]
thanks a lot, I met the same problem and the method does work

**Comment by gdymind** [comment]
I encountered the same problem, too. But it seems that `all_proxy` & `ALL_PROXY` changes back to `socks://127.0.0.1:1080/` after I exit the terminal. Could you please help me fix it?

**Comment by mzx5464** [comment]
You can just add 
```
all_proxy=socks5://127.0.0.1:1080/
ALL_PROXY=socks5://127.0.0.1:1080/
```
to `/etc/environment` and reboot

**Comment by leebaird** [comment]
This is an issue related to the OS and not to theHarvester.

**Comment by NotoriousRebel** [comment]
As this issue was resolved and is not related to theHarvester, closing!

**Comment by GuNanHai** [comment]
@kdlsw Someone like me will need this post ,a big help
