### ISSUE TITLE
[Bug|

### ISSUE THREAD

**Issue by BlackBatman1980** [laramies/theHarvester#587]
**Bug**:
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from theHarvester.lib.core import Core
  File "/home/yeet/theHarvester/theHarvester/lib/core.py", line 6, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

When I run the setup, there seems to be a missing module and I don't know if I have to install it or if it is supposed to be installed.

**System Information:**
 - OS: [e.g. Windows10]
 - Version [e.g. 2.7]

**Comment by L1ghtn1ng** [comment]
If you run pip3 install -r requirements.txt it will install all the libraries for you
________________________________

**Comment by BlackBatman1980** [comment]
Ok. Thanks for support!!

**Comment by ph3rx** [comment]
@L1ghtn1ng this error still persist while trying to run `sudo python3 setup.py build` for system installation after having run:

```
pip3 install -r requirements/base.txt
pip3 install -r requirements/dev.txt
pip3 install -r requirements.txt
```

When running this command on my cloned folder
```
$ sudo python3 setup.py build
```

I get same error as @BlackBatman1980 on his Windows machine:

```
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from theHarvester.lib.core import Core
  File "/home/ferx/Source/GitHub/laramies/theHarvester/theHarvester/lib/core.py", line 6, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
```

System information: `Linux mintbox 5.4.0-58-generic #64-Ubuntu`
