### ISSUE TITLE
[Other] Licensing the repository

### ISSUE THREAD

**Issue by toidi** [laramies/theHarvester#599]
**Feature Request or Bug or Other**

Other

**Describe the feature request or bug or other**

https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository

> Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

**Comment by L1ghtn1ng** [comment]
It is licensed, please look in the readme directory
