### ISSUE TITLE
[Bug] Doesn't run out-of-the-box

### ISSUE THREAD

**Issue by fabaff** [laramies/theHarvester#606]
**Feature Request or Bug or Other**
Bug

**Describe the feature request or bug or other**
Doesn't run properly.

**To Reproduce**
Steps to reproduce the behaviour:

```bash
$ git clone https://github.com/laramies/theHarvester
$ cd theHarvester/
$ python -m venv .
$ source bin/activate
$ pip3 install -r requirements.txt or $ python setup.py develop
```
Should work acc. `setup.py`

```bash
$ theHarvester -d some-domain.tld
Traceback (most recent call last):
  File "/home/fab/Documents/repos/theHarvester/bin/theHarvester", line 7, in <module>
    from theHarvester import __main__
ModuleNotFoundError: No module named 'theHarvester'
```

```bash
$ ./theHarvester.py -d some-domain.tld
[...]
Traceback (most recent call last):
  File "/home/fab/Documents/repos/theHarvester/./theHarvester.py", line 28, in <module>
    asyncio.run(__main__.entry_point())
  File "/usr/lib64/python3.9/asyncio/runners.py", line 49, in run
    loop.run_until_complete(loop.shutdown_default_executor())
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/lib64/python3.9/asyncio/events.py", line 253, in shutdown_default_executor
    raise NotImplementedError
NotImplementedError
```

**Expected behaviour**
Run out-of-the-box.

**System Information (System that tool is running on):**

```bash
$ python
Python 3.9.0 (default, Oct  6 2020, 00:00:00) 
[GCC 10.2.1 20200826 (Red Hat 10.2.1-3)] on linux
```

**Additional context**

**Comment by x00-R0n1n** [comment]
Same issue. 
Followed install instructions to the letter, 

Platform:
Python 3.9.0
Mac OSX 10.15.7

**Comment by whoot** [comment]
Seems to be a known uvloop issue with python 3.9 - see [here](https://github.com/MagicStack/uvloop/issues/349)

**Comment by NotoriousRebel** [comment]
Thank you for bringing this up, we could add a check for python version to only install uvloop if python_version < '3.9' within requirements\base.txt this would also require a small check of Python version to make sure uvloop is not installed if using Python3.9+ right here: [https://github.com/laramies/theHarvester/blob/master/theHarvester.py#L22.](https://github.com/laramies/theHarvester/blob/master/theHarvester.py#L22)
