### ISSUE TITLE
getting 0 results after multiple sites.

### ISSUE THREAD

**Issue by vinnt2** [laramies/theHarvester#61]
After some email harvests on multiple sites.

theHarvester giving 0 results.

i think google Captcha detects it and whenever i use socks 5, http proxy, vpn same results. 
Anyway to resolve this issue?

Thanks.

**Comment by vinnt2** [comment]
I am waiting further replies any help would be much well.

**Comment by NotoriousRebel** [comment]
@vinnt2 sorry for replying so late! Google does limit requests after a certain amount, this is currently being worked on and will now notify you if your requests are being blocked!
Closing.

**Comment by wowficcion** [comment]
I have the same issue, testing with my own site, and 0 results

**Comment by NotoriousRebel** [comment]
@wowficcion you should open up a new issue rather than comment on one that is two years old.
