### ISSUE TITLE
[question

### ISSUE THREAD

**Issue by TanGe0** [laramies/theHarvester#611]
Segmentation fault
why ?

**Comment by L1ghtn1ng** [comment]
Can you please post a screenshot?

**Comment by TanGe0** [comment]
> 你能发布截图吗？

![175749](https://user-images.githubusercontent.com/59207686/101336736-c62ce880-38b5-11eb-98a8-f2ddf6f7fae1.png)

**Comment by L1ghtn1ng** [comment]
Unfortunately without more information like what OS, which parameters you are using, python version I cannot say and or look into it. Please try using the git version to see if that fixes your issue and use a python virtual environment

**Comment by L1ghtn1ng** [comment]
Timeout
