### ISSUE TITLE
Google is blocking your IP and the workaround, returning Searching X results

### ISSUE THREAD

**Issue by Individuum92** [laramies/theHarvester#616]
Hey guys,

I'am recieve the following error message 
`Google is blocking your IP and the workaround, returning Searching X results`

when I execute following command:
`theHarvester -d www.domain.com -b all`

How can I handle this issue? Is it possible to handle this issue without using a proxy?

**Comment by L1ghtn1ng** [comment]
Unfortunately not
________________________________

**Comment by Individuum92** [comment]
Thank you for your prompt reply.

Would there be a way to limit the requests to bypass the IP blocking?
So wouldn't google think that these are mass queries?

Or is the train of thought wrong?

**Comment by L1ghtn1ng** [comment]
We will be implementing socks proxy support but if I recall correctly it already does that but Google probably are using AI/ML to detect it
________________________________

**Comment by Individuum92** [comment]
Okay. Do you have any proxy switcher recommendations for the best results when using your harvester?
Maybe an API for a proxy switcher?

**Comment by L1ghtn1ng** [comment]
We do have proxy support currently but not socks support
________________________________
