### ISSUE TITLE
Not outputting html file

### ISSUE THREAD

**Issue by BustedSec** [laramies/theHarvester#62]
when using the syntax theHarvester -d domain.com -l 100 -b all -h myresults.html
no html file is generated

**Comment by cative0** [comment]
Actually, there is an error on example. the output file key word is "-f", not "-h", please retry by enter "theHarvester -d domain.com -l 100 -b all -f myresults.html"

**Comment by NotoriousRebel** [comment]
This has been fixed you can run with -f and the report html has been improved!
Closing.
