### ISSUE TITLE
Passive attack not working in .com domains.

### ISSUE THREAD

**Issue by Tikam02** [laramies/theHarvester#63]
if you try to run the passive plugins against a url like https://abc.com, then tools are launched wrong like:
```python /usr/bin/theharvester -d com -b all -v -f -h -l 1500```

instead of
```-d abc.com```

Please give me a fast fix this is very important.

**Comment by jzold** [comment]
hi Tikam02,

I'm not clear what the issue here is. When you run theHarvester it gives you a few examples on how to use it. The -d switch accepts domain names to target.

Unless your issue is still relevant I propose closing this ticket.

J./
