### ISSUE TITLE
"ModuleNotFoundError: No module named 'aiohttp'" when running "python3 setup.py build"

### ISSUE THREAD

**Issue by ph3rx** [laramies/theHarvester#649]
This error still persist while trying to run `sudo python3 setup.py build` for system installation after having run any of these:

```
pip3 install -r requirements/base.txt
pip3 install -r requirements/dev.txt
pip3 install -r requirements.txt
```

When running this command on my cloned folder:

```
$ sudo python3 setup.py build
```

I get same error as @BlackBatman1980 on his Windows machine:

```
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from theHarvester.lib.core import Core
  File "/home/ferx/Source/GitHub/laramies/theHarvester/theHarvester/lib/core.py", line 6, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
```

System information: `Linux mintbox 5.4.0-58-generic #64-Ubuntu`.

> This bug has been also reported under this closed ticket: https://github.com/laramies/theHarvester/issues/587

**Comment by L1ghtn1ng** [comment]
closing due to duplicate
