### ISSUE TITLE
ImportError: cannot import name rewriter_config_pb2

### ISSUE THREAD

**Issue by sai10** [laramies/theHarvester#65]
I am simply following the tutorials of tensorflow and while performing following cmd its giving above mentioned issue:
python ptb_word_lm.py  --data_path=/home/priyankit/data/validsrc2-hi --model=small

error is:

Traceback (most recent call last):
  File "ptb_word_lm.py", line 68, in <module>
    import util
  File "/home/priyankit/models-master/tutorials/rnn/ptb/util.py", line 23, in <module>
    from tensorflow.core.protobuf import rewriter_config_pb2
ImportError: cannot import name rewriter_config_pb2

**Comment by jafetmorales** [comment]
You need to do two things. First, upgrade tensorflow by doing:

    pip install --upgrade tensorflow

Second, if you are not using a GPU, then execute the script with 0 GPUs as follows:

    python ptb_word_lm.py --data_path=/home/priyankit/data/validsrc2-hi --model=small --num_gpus=0

**Comment by NotoriousRebel** [comment]
As this issue is not related to theHarvester, closing!
