### ISSUE TITLE
ModuleNotFoundError: No module named 'aiohttp' when running python3 setup.py build

### ISSUE THREAD

**Issue by ph3rx** [laramies/theHarvester#650]
This error still persist while trying to run `sudo python3 setup.py build` for system installation after having run any of these:

```
pip3 install -r requirements/base.txt
pip3 install -r requirements/dev.txt
pip3 install -r requirements.txt
```

When running this command on my cloned folder:

```
$ sudo python3 setup.py build
```

I get same error as @BlackBatman1980 on his Windows machine:

```
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from theHarvester.lib.core import Core
  File "/home/ferx/Source/GitHub/laramies/theHarvester/theHarvester/lib/core.py", line 6, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
```

System information: 
```
Linux mintbox 5.4.0-58-generic #64-Ubuntu
```

Python version:

```
Python 3.8.5
```

> This bug has been also reported under this closed ticket: https://github.com/laramies/theHarvester/issues/587

**Comment by L1ghtn1ng** [comment]
Does this still happen with the latest repo changes?

**Comment by ph3rx** [comment]
@L1ghtn1ng , I pulled [latest](https://github.com/laramies/theHarvester/commit/2f7fd1be0c44fec01e5f6f4b0a9a62fdc221576b), sadly, this error keeps on happening. 

```
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from theHarvester.lib.core import Core
  File "/home/ferx/Source/GitHub/laramies/theHarvester/theHarvester/lib/core.py", line 6, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
```

**Comment by L1ghtn1ng** [comment]
What OS version you running? Instead of build you should be able to run install and it should work but with the OS version I can have a look at see if I can replicate it

**Comment by ph3rx** [comment]
Running `Linux mintbox 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`.

**Comment by L1ghtn1ng** [comment]
Can you give me the output of lsb_release -a
________________________________

**Comment by L1ghtn1ng** [comment]
what happens if you do sudo apt install -y python3-aiohttp does that then work afterwards?

**Comment by L1ghtn1ng** [comment]
the above should fix it
