### ISSUE TITLE
An exception has occurred: Cannot connect to host www.google.com:443 ssl:<ssl.SSLContext object at 0

### ISSUE THREAD

**Issue by hackping** [laramies/theHarvester#667]
An exception has occurred: Cannot connect to host www.google.com:443 ssl:<ssl.SSLContext object at 0

**Comment by L1ghtn1ng** [comment]
Can you please give me the cli output you are running but I suspect this is due to google blocking you temporally

**Comment by L1ghtn1ng** [comment]
timeout
