### ISSUE TITLE
[ERROR] NotImplementedError [ERROR]

### ISSUE THREAD

**Issue by xmarshalldteachx** [laramies/theHarvester#683]
Hey guys, I'm having this error: 
![Screenshot_3](https://user-images.githubusercontent.com/79426018/108642001-8cbe4f00-749a-11eb-9f78-29a87c9fc883.png)

And I don't know how to fix it :( Can you help me? Thank you :)

**Comment by L1ghtn1ng** [comment]
Please update to the latest version which fixes this issue
________________________________
