### ISSUE TITLE
[BUG] docker failure

### ISSUE THREAD

**Issue by Sable-20** [laramies/theHarvester#709]
**Feature Request or Bug or Other**
Bug

**Describe the feature request or bug or other**
when running the docker image you receive the following error:
```
C:\Users\Sable\theHarvester>docker run theharvester
': No such file or directory
```

**To Reproduce**
Steps to reproduce the behaviour:
1. git clone on windows cmd
2. build the docker image with 
   `docker build -t theharvester .`
3. `docker run theharvester -h`

**Expected behaviour**
the tool to run

**System Information (System that tool is running on):**
 - OS: Windows 10

**Comment by L1ghtn1ng** [comment]
@NotoriousRebel Can you comment on this please

**Comment by 00frank** [comment]
any update? im stuck with the same problem too

**Comment by p-hp** [comment]
docker is either not installed or not in your PATH folder

**Comment by L1ghtn1ng** [comment]
Can you try with the new docker file please but also make sure you have docker in your path

**Comment by L1ghtn1ng** [comment]
Timeout
