### ISSUE TITLE
can't create report files (html / xml) after scan domain

### ISSUE THREAD

**Issue by bulpet** [laramies/theHarvester#71]
hi
most of time im use report files (xml/html) but i have problem with few domains. 
after scanning them, theharvester cannot create the report file

for example: **theharvester -d manobi.sn -b all -f manobi_sn**
please fix it

**Comment by Djent-** [comment]
While looking to see if there was an error message, I found that theHarvester does not produce the same results each time it is run. Compare the following pastes:

https://pastebin.com/VF6rCwH2
https://pastebin.com/a4vFXr87
https://pastebin.com/cqKDAzVv

I have also confirmed that the given command does not produce an output file as expected.

**Comment by jzold** [comment]
Hi,

I'll take a closer look. To clarify there are 2 issues as I understand from bulpet and Djent:

1. theHarvester with the "-f" switch produces only XML file as an output but not HTML
2. Inconsistent results as pointed out by Djent

I'll focus on issue 1. I'm able to reproduce the issue with the latest version of theHarvester (v3.0.0.0). I'll provide a fix shortly. I recommend tracking issue 2 as separate as that one might not be related to theHarvester and requires further investigation.

J./

**Comment by laramies** [comment]
Closing as the original issue is fixed by @jzold

**Comment by punisherprime** [comment]
Whelp. It is back. Produces json and xml but no HTML. :/

**Comment by L1ghtn1ng** [comment]
In the release notes html got removed
________________________________
