### ISSUE TITLE
[Feature Request] argument to output without formatting

### ISSUE THREAD

**Issue by FalcoGer** [laramies/theHarvester#714]
**Feature Request or Bug or Other**
Feature Request

**Describe the feature request or bug or other**
A command line option to disable colored output.
I wish to use theharvester inside other tools (such as ZAProxy). However the output it generates is full of color codes.

**To Reproduce**
Run the tool

**Expected behaviour**
The tool outputs the text without any formatting that will cause it to display colors, bold text, etc.

**Screenshots**
If possible please add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/16250196/113906790-ea9dc080-97d4-11eb-8edd-9779df5b704c.png)

**System Information (System that tool is running on):**
 - OS: Ubuntu Mate (5.4.0-70-generic, x86_64)
 - Version: 3.2.3

**Additional context**
None needed

**Comment by NotoriousRebel** [comment]
Thank you for raising the issue, perhaps down the road a --nocolor flag will be added, in the meantime, a possible workaround would be to use the json output and using tools such as [gron](https://github.com/tomnomnom/gron) or [jq](https://github.com/stedolan/jq) to do further post-processing.

**Comment by L1ghtn1ng** [comment]
In master all colour output has been removed
