### ISSUE TITLE
Create new modules that are missing from other tools

### ISSUE THREAD

**Issue by leebaird** [laramies/theHarvester#728]
Create new modules that are missing from other tools.

**From recon-ng (all require API keys):**
builtwith
facebook
flickr
fullcontact
hashes
instagram
ipinfodb  (time intensive for little results)
ipstack   (time intensive for little results)
jigsaw
linkedin
namechk  (time intensive for little results)
pwnedlist
virustotal
whoxy

**From Amass:**
C99
Chaos
CIRCL
Cloudflare
DNSDB
DNSTable
HackerOne
NetworksDB
PassiveTotal
Riddler
SiteDossier
Umbrella
WhoisXML
ZETAlytics

**Comment by L1ghtn1ng** [comment]
A lot of these we have already, granted they may not be the api versions but we do have them, matt has said also a lot of these do not make sense in adding them
