### ISSUE TITLE
Zero results in Mac OS High Sierra

### ISSUE THREAD

**Issue by furo1973** [laramies/theHarvester#73]
Hello, 
I'm running the harvester in Mac OS High Sierra, but I get zero results every time. 
It seems the the software runs when I make a search but I cannot get any result even looking for mayor companies or domains. 
Very newbie with theharvester and info gathering tools.
I don't know if I have to install additional libraries or Apis or there's something in Mac OS blocking theharvester. 
Please help

**Comment by mstampfli** [comment]
It's only the PGP plugin which is braking the code. If you exlcude it, everything runs smooth.

**Comment by laramies** [comment]
I consider this issue closed as per @mstampfli suggestion.
