### ISSUE TITLE
"Missing API key for Shodan" even if API Key is there

### ISSUE THREAD

**Issue by francesco1119** [laramies/theHarvester#747]
**Feature Request or Bug or Other**
Bug 

**Describe the feature request or bug or other**
Shodan search is returning:

```
[!] An error occurred with Shodan:
[!] Missing API key for Shodan.
```

even if the key is there

**To Reproduce**
Steps to reproduce the behaviour:
1. I type `nano ./theHarvester/discovery/shodansearch.py` and I add my API key at the line `self.key = Core.shodan_key`:

![image](https://user-images.githubusercontent.com/3397477/118413543-2a8f7780-b6a0-11eb-85d9-7e1e8ca8a254.png)

2. I then run the search `theHarvester -d virgilio.it -l 100 -b bing -s` but is returning 
```
[!] An error occurred with Shodan:
[!] Missing API key for Shodan.
```

![image](https://user-images.githubusercontent.com/3397477/118413576-590d5280-b6a0-11eb-8c2b-0719fc11c288.png)

**Expected behaviour**
Shodan search should work 

**System Information (System that tool is running on):**
 - OS: WSL2 Debian on Windows 10
 - Version 3.2.4

**Comment by L1ghtn1ng** [comment]
Having your key in that module will not work. You need to put your API keys in the api-keys.yaml file that is in the root directory of the project. If you choose to install it system wide it would end up in /etc/theHarvester/api-keys.yaml
________________________________
From: Francesco Mantovani ***@***.***>
Sent: Sunday, May 16, 2021 10:43:30 PM
To: laramies/theHarvester ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [laramies/theHarvester] [Bug|Feature Request|Other] Short Description of Issue (#747)


Feature Request or Bug or Other
Bug

Describe the feature request or bug or other
Shodan search is returning:

[!] An error occurred with Shodan:
[!] Missing API key for Shodan.


even if the key is there

To Reproduce
Steps to reproduce the behaviour:

  1.  I type nano ./theHarvester/discovery/shodansearch.py and I add my API key at the line self.key = Core.shodan_key:

[image]<https://user-images.githubusercontent.com/3397477/118413543-2a8f7780-b6a0-11eb-85d9-7e1e8ca8a254.png>

  1.  I then run the search theHarvester -d virgilio.it -l 100 -b bing -s but is returning ```
[!] An error occurred with Shodan:
[!] Missing API key for Shodan.

![image](https://user-images.githubusercontent.com/3397477/118413576-590d5280-b6a0-11eb-8c2b-0719fc11c288.png)

**Expected behaviour**
Shodan search should work

**System Information (System that tool is running on):**
 - OS: WSL2 Debian on Windows 10
 - Version 3.2.4

**Comment by francesco1119** [comment]
SOLVED!

I first added the Shodan API Key into `/etc/theHarvester/api-keys.yaml` but after I run a first search I ended up with the error:

```
[*] Searching Shodan.
        Searching for 13.224.228.3
[!] An error occurred with Shodan: string indices must be integers
```

The solution was to add a space after `key:` 

![image](https://user-images.githubusercontent.com/3397477/118551671-3c375480-b75e-11eb-95ed-2bad9e5fc265.png)

**Comment by pwnedDesal** [comment]
> SOLVED!
> 
> I first added the Shodan API Key into `/etc/theHarvester/api-keys.yaml` but after I run a first search I ended up with the error:
> 
> ```
> [*] Searching Shodan.
>         Searching for 13.224.228.3
> [!] An error occurred with Shodan: string indices must be integers
> ```
> 
> The solution was to add a space after `key:`
> 
> ![image](https://user-images.githubusercontent.com/3397477/118551671-3c375480-b75e-11eb-95ed-2bad9e5fc265.png)

![image](https://user-images.githubusercontent.com/6646675/211714776-1ca2ad45-9224-48b7-842d-8d4be9dbbb6d.png)
