### ISSUE TITLE
while recon the target it's give an error

### ISSUE THREAD

**Issue by akksoni** [laramies/theHarvester#751]
Hey,
I got an error while recon a target
(user㉿kali)-[~]
└─$ theHarvester -d twitter.com -b all 

[!] Missing API key for Spyse. 

[!] Missing API key for ProjectDiscovery. 

[!] Missing API key for Securitytrail. 

[!] Missing API key for Intelx. 
No module named 'censys'
sys:1: RuntimeWarning: coroutine 'start.<locals>.store' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

#2 using second method also give an error
(user㉿kali)-[~/theHarvester]
└─$ ./theHarvester.py -d twitter.com -b all

*******************************************************************
*  _   _                                            _             *          
* | |_| |__   ___    /\  /\__ _ _ ____   _____  ___| |_ ___ _ __  *          
* | __|  _ \ / _ \  / /_/ / _` | '__\ \ / / _ \/ __| __/ _ \ '__| *          
* | |_| | | |  __/ / __  / (_| | |   \ V /  __/\__ \ ||  __/ |    *          
*  \__|_| |_|\___| \/ /_/ \__,_|_|    \_/ \___||___/\__\___|_|    *          
*                                                                 *          
* theHarvester 3.2.4                                              *          
* Coded by Christian Martorella                                   *          
* Edge-Security Research                                          *          
* cmartorella@edge-security.com                                   *          
*                                                                 *          
*******************************************************************          
                                                                             
                                                                             
[*] Target: twitter.com 
                                                                             

[!] Missing API key for ProjectDiscovery. 

[!] Missing API key for Intelx. 

[!] Missing API key for Hunter. 

[!] Missing API key for Github. 

[!] Missing API key for PentestTools. 

[!] Missing API key for Securitytrail. 

[!] Missing API key for Spyse. 
No module named 'censys'
sys:1: RuntimeWarning: coroutine 'start.<locals>.store' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by L1ghtn1ng** [comment]
What version are you running?
________________________________
From: akksoni ***@***.***>
Sent: Sunday, May 23, 2021 6:25:44 AM
To: laramies/theHarvester ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [laramies/theHarvester] while recon the target it's give an error (#751)


Hey,
I got an error while recon a target
(user㉿kali)-[~]
└─$ theHarvester -d twitter.com -b all

[!] Missing API key for Spyse.

[!] Missing API key for ProjectDiscovery.

[!] Missing API key for Securitytrail.

[!] Missing API key for Intelx.
No module named 'censys'
sys:1: RuntimeWarning: coroutine 'start..store' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by thehappydinoa** [comment]
Fixed in https://github.com/laramies/theHarvester/pull/752

**Comment by L1ghtn1ng** [comment]
Ah @akksoni sorry did not see the information correctly that you posted from the email I received from GitHub. This will be fixed in the next release we are doing

**Comment by akksoni** [comment]
> Fixed in #752

give same error

**Comment by Py-GNU-Unix** [comment]
I got the same error too.

**Comment by thehappydinoa** [comment]
I believe it will be fixed in the next major release: https://github.com/laramies/theHarvester/pull/752#issuecomment-847333689

**Comment by L1ghtn1ng** [comment]
That is correct, we are in the final stages of this major release
________________________________

**Comment by L1ghtn1ng** [comment]
Have released the new version
