### ISSUE TITLE
An Exception has occured: [X509: NO_CERTIFICATE_OR_CRL_FOUND] 

### ISSUE THREAD

**Issue by rodrigoventura79** [laramies/theHarvester#762]
![image](https://user-images.githubusercontent.com/43246160/120797214-022ac880-c53c-11eb-9185-31146aa55afc.png)
I've been struggling with this, I don't know what to do here. 
Please help!

**Comment by rodrigoventura79** [comment]
> Put the tld extension and see if that works?
> […](#)

tld extension? do you mean at the -d commando or the -b one?
$ theHarvester -d Rockdrigov -l 200 -b linkedin

well I put -d Rockdrigov as an example, but it is not a domain, it is a name or username or whatever you could find related in linkedin, the -b is the source it doesn't work if you put linkedin.com or google.com, thanks for your suggestion.

**Comment by L1ghtn1ng** [comment]
I do not get your issue, as if I do ./theHarvester.py -d yale.edu  -b linkedin it works fine until Google blocks me. Would not be surprised if you hit that which with the current code for the google module we cannot get around until we re-work that module
