### ISSUE TITLE
[Bug] Error during installation 

### ISSUE THREAD

**Issue by gsabatini2016** [laramies/theHarvester#798]
Error during Installation.
I followed the steps like this page indicates: https://github.com/laramies/theHarvester/wiki/Installation

When i tried install through the "Option 2 - Docker" way, returns this error:
![image](https://user-images.githubusercontent.com/48037187/125369430-9b76a700-e352-11eb-80f5-5ebcffe1a88b.png)

When i tried install through the "Option 3 - From Source" way, returns this error:
![image](https://user-images.githubusercontent.com/48037187/125369722-3c656200-e353-11eb-90cd-9fd23c3e895b.png)
 
 - OS: Debian Buster

**Comment by NotoriousRebel** [comment]
@gsabatini2016 Please see this [issue](https://github.com/ijl/orjson/issues/136) in regards to orjson failng to install, try the solution there and see if that works. For the docker installation are you using the latest version of the tool with the ubuntu based image?

**Comment by gsabatini2016** [comment]
Thanks i'll try that

**Comment by gsabatini2016** [comment]
Well that seems dont work, i tried the solution proposed (python -m pip install --upgrade pip) and returns the same error.

![image](https://user-images.githubusercontent.com/48037187/125529636-f35faa68-8557-4ba5-b649-4f653f2d72fd.png)

For the Docker way, i build the image with the Dockerfile includes in the repository.
Docker version 18.09.1, build 4c52b90

**Comment by NotoriousRebel** [comment]
Can you try `python3 -m pip install --upgrade pip` and reinstalling orjson. With docker please see [this post](https://stackoverflow.com/questions/59139453/repository-is-not-signed-in-docker-build), verify you have enough room for docker container as it is around 20 GB with `df -h` and then as mentioned in post try `docker system prune --force` and `sudo apt clean`

**Comment by L1ghtn1ng** [comment]
Also make sure you have python3 Dev package installed as well
________________________________

**Comment by L1ghtn1ng** [comment]
Timeout
