### ISSUE TITLE
please tag a proper release

### ISSUE THREAD

**Issue by blshkv** [laramies/theHarvester#82]
version 2.7.2 is mentioned in few places, but the source code was not tagged properly and it is not available for the download.

Please consider making an official release.

**Comment by blshkv** [comment]
The latest release seems was tagged in August but only released recently (https://github.com/laramies/theHarvester/releases/tag/v3.0)

@laramies do you read bugs/pull requests? Feel free to close the issue.

**Comment by laramies** [comment]
Thanks @blshkv I will make sure to tag the code and releases going forward!
