### ISSUE TITLE
censys.certificates, 'start.<locals>.store' was never awaited, missing API

### ISSUE THREAD

**Issue by AbdulMalik0** [laramies/theHarvester#825]
please I need help with my kali machine. I've been trying to find a solution but to no avail. first of all, it says no module named censys but I rectify that using the command pip install censys and the next error it brought was >no module named censys.certificates. The second error is this message sys:1: RuntimeWarning: coroutine 'start..store' was never awaited RuntimeWarning: Enable tracemalloc to get the object allocation traceback

The last one was the Missing API key for Hunter, Github, and Securitytrial Please find the snapshot attached below. Thanks

![image](https://user-images.githubusercontent.com/36079349/128470461-cd6a89c0-7172-4832-ba56-b6c01cb361c7.png)

**Comment by Al3x1S4** [comment]
Hi ! Did you fix it ?
