### ISSUE TITLE
proxies are not working at all no connections is going through

### ISSUE THREAD

**Issue by Fr33d0m666** [laramies/theHarvester#831]
I started trying to use proxies as requests kept getting blocked but whenever i put http proxys in the .yml file i get the error of.... "An exception has occurred: http://ip:port"

**Comment by L1ghtn1ng** [comment]
Can you show me the output of the proxies file?

**Comment by Fr33d0m666** [comment]
https://gyazo.com/8ff346968b8d788ac3f50c598f9df8bc
sorry if it is something dumb couldnt find any answers on it

**Comment by L1ghtn1ng** [comment]
It is due to you using Https remove the s and it should work as long as the proxy supports http that is
________________________________

**Comment by Fr33d0m666** [comment]
im not sure where you seee https? in the file i have it as http

**Comment by L1ghtn1ng** [comment]
Ah sorry thought the URL you posted was to do with the link you have in the proxy file, sorry about that. From looking at your output you need to have it all on the same line in the file and have it treated as a URL 

http: http://1.1.1.1:80

For example

**Comment by Fr33d0m666** [comment]
https://gyazo.com/ccd02905a02df6f790546d0826d15c01
thanks for responding so quick still nothing included a ping of my proxy to prove proxy isnt dead

**Comment by L1ghtn1ng** [comment]
Are you also applying the proxy cli switch as part of your arguments?
________________________________

**Comment by Fr33d0m666** [comment]
no i applied the -p argument that was all i didnt see anything about another argument

**Comment by L1ghtn1ng** [comment]
if you do the -p switch with True parameter does it work?

**Comment by L1ghtn1ng** [comment]
timeout
