### ISSUE TITLE
Apki key Missing theHarvester Kali LInux

### ISSUE THREAD

**Issue by lazzyvigilante** [laramies/theHarvester#835]
Target: sgd.uol.edu.pk
Missing api key for ProjectDiscovery.
Missing Api key for Github.
Missing api key for securityTrail.
Missing api key for hunter.
Missing Api key for Spyse.
no modulename 'censys'

**Comment by L1ghtn1ng** [comment]
Please have a look at the following https://github.com/laramies/theHarvester/wiki/Installation
