### ISSUE TITLE
Harvester pip module error on requirements while installing on andriod 

### ISSUE THREAD

**Issue by Keerthivasan472** [laramies/theHarvester#836]
Just few days before I install termux and I follow the procedure to install termux I got errors while doing this

*) python - m pip install - r requirements/base.txt

**Comment by L1ghtn1ng** [comment]
You need to make sure you are running python3 to install it correctly
________________________________
From: Keerthivasan472 ***@***.***>
Sent: Friday, August 20, 2021 6:22:56 PM
To: laramies/theHarvester ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [laramies/theHarvester] Harvester pip module error on requirements (#836)


Just few days before I install termux and I follow the procedure to install termux I got errors while doing this

*) python - m pip install - r requirements/base.txt

**Comment by Keerthivasan472** [comment]
I am installing python3 and error is:
python3 -m pip install -r requirements/dev.txt
Collecting aiodns==3.0.0
  Using cached aiodns-3.0.0-py3-none-any.whl (5.0 kB)
Collecting aiofiles==0.7.0
  Using cached aiofiles-0.7.0-py3-none-any.whl (13 kB)
Collecting aiohttp==3.7.4.post0
  Using cached aiohttp-3.7.4.post0.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting aiomultiprocess==0.9.0
  Using cached aiomultiprocess-0.9.0-py3-none-any.whl (17 kB)
Collecting aiosqlite==0.17.0
  Using cached aiosqlite-0.17.0-py3-none-any.whl (15 kB)
Collecting beautifulsoup4==4.9.3
  Using cached beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
Collecting censys==2.0.5
  Using cached censys-2.0.5-py3-none-any.whl (45 kB)
Collecting certifi==2021.05.30
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting dnspython==2.1.0
  Using cached dnspython-2.1.0-py3-none-any.whl (241 kB)
Collecting fastapi==0.68.0
  Using cached fastapi-0.68.0-py3-none-any.whl (52 kB)
Collecting netaddr==0.8.0
  Using cached netaddr-0.8.0-py2.py3-none-any.whl (1.9 MB)
Collecting orjson==3.6.1
  Using cached orjson-3.6.1.tar.gz (746 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/tmp/pip-standalone-pip-7uickcue/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /data/data/com.termux/files/usr/tmp/pip-build-env-q2tuambi/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'maturin>=0.11.2,<0.12'
       cwd: None
  Complete output (57 lines):
  Collecting maturin<0.12,>=0.11.2
    Using cached maturin-0.11.2.tar.gz (109 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting toml~=0.10.0
    Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
  Building wheels for collected packages: maturin
    Building wheel for maturin (PEP 517): started
    Building wheel for maturin (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/tmp/tmposp4lkxy_in_process.py build_wheel /data/data/com.termux/files/usr/tmp/tmpmhozqpj1
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-65tvdypg/maturin_a898cf983c5d4f46a99026de49aa0630
    Complete output (36 lines):
    running bdist_wheel
    running build
    installing to build/bdist.linux-aarch64/wheel
    running install
    Traceback (most recent call last):
      File "/data/data/com.termux/files/usr/tmp/tmposp4lkxy_in_process.py", line 349, in <module>
        main()
      File "/data/data/com.termux/files/usr/tmp/tmposp4lkxy_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/data/data/com.termux/files/usr/tmp/tmposp4lkxy_in_process.py", line 248, in build_wheel
        return _build_backend().build_wheel(wheel_directory, config_settings,
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-s4ta1zbj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 216, in build_wheel
        return self._build_with_temp_dir(['bdist_wheel'], '.whl',
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-s4ta1zbj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
        self.run_setup()
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-s4ta1zbj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 106, in <module>
        setup(
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-s4ta1zbj/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/data/data/com.termux/files/usr/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/data/data/com.termux/files/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/data/data/com.termux/files/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/data/data/com.termux/files/usr/tmp/pip-build-env-s4ta1zbj/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 335, in run
        self.run_command('install')
      File "/data/data/com.termux/files/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/data/data/com.termux/files/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "setup.py", line 58, in run
        raise RuntimeError(
    RuntimeError: cargo not found in PATH. Please install rust (https://www.rust-lang.org/tools/install) and try again
    ----------------------------------------
    ERROR: Failed building wheel for maturin
  Failed to build maturin
  ERROR: Could not build wheels for maturin which use PEP 517 and cannot be installed directly
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/92/97/895dfe0c2e7820fd5453d0efab6a9036de7f97b4edfd157a6a414dd3b0ee/orjson-3.6.1.tar.gz#sha256=5ee598ce6e943afeb84d5706dc604bf90f74e67dc972af12d08af22249bd62d6 (from https://pypi.org/simple/orjson/) (requires-python:>=3.6). Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python3 /data/data/com.termux/files/usr/tmp/pip-standalone-pip-7uickcue/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /data/data/com.termux/files/usr/tmp/pip-build-env-q2tuambi/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'maturin>=0.11.2,<0.12' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement orjson==3.6.1 (from versions: 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.11, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.4.0, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.6.7, 2.6.8, 3.0.0, 3.0.1, 3.0.2, 3.1.0, 3.1.1, 3.1.2, 3.2.0, 3.2.1, 3.2.2, 3.3.0, 3.3.1, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.4.6, 3.4.7, 3.4.8, 3.5.0, 3.5.1, 3.5.2, 3.5.3, 3.5.4, 3.6.0, 3.6.1, 3.6.2, 3.6.3)
ERROR: No matching distribution found for orjson==3.6.1

**Comment by L1ghtn1ng** [comment]
Installing on a android device is not something we officially support and the issue seems to be building a couple of libraries that we use on it. Make sure you have python3.7+ installed and the best I can suggest unfortunately is have Google. As mentioned this is not something we support and or have knowledge in unfortunately
________________________________

**Comment by Keerthivasan472** [comment]
I founally found it require python pep 517 and rust lang to run properly I think python-dev may remove this 1, so that's why I can't execute it without error

**Comment by L1ghtn1ng** [comment]
okay, if you want to give me install guide for android I could add it to our install docs

**Comment by L1ghtn1ng** [comment]
timeout
