### ISSUE TITLE
The color of system cmdline become blue

### ISSUE THREAD

**Issue by yizhimanpadewoniu** [laramies/theHarvester#84]
## the color of system become blue

when I use it:

![blue.jpg](https://i.loli.net/2018/06/21/5b2b687113b76.jpg)

**Comment by laramies** [comment]
Sorry, it might be a particular case that doesnt finish correctly and it doesnt return to standard colours. will try to check for the error in next release.

**Comment by leebaird** [comment]
Fixed with my latest PR.

**Comment by NotoriousRebel** [comment]
As this has been fixed, closing!
