### ISSUE TITLE
[Bug] sys:1: RuntimeWarning: coroutine 'start.<locals>.store' was never awaited

### ISSUE THREAD

**Issue by soufianetahiri** [laramies/theHarvester#841]
**Feature Request or Bug or Other**
Bug 

**Describe the feature request or bug or other**

┌─[✗]─[soufiane@offsec]─[~/Tools/OSINT/theHarvester]
└──╼ $python3 theHarvester.py -d xxx.com  -b all -f ~/Desktop/xxx/out.html

[*] Target: cdiscount.com 
 

[!] Missing API key for ProjectDiscovery. 
string indices must be integers

[!] Missing API key for PentestTools. 

[!] Missing API key for Intelx. 

[!] Missing API key for binaryedge. 
string indices must be integers
sys:1: RuntimeWarning: coroutine 'start.<locals>.store' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tool like this: '...'
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/17729335/131102671-2e6597cf-547f-4b38-931b-7b3499b22c29.png)

**System Information (System that tool is running on):**
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by L1ghtn1ng** [comment]
I would recommend that you use a virtualenv and doing that will make sure you have up to date deps as I cannot replicate this issue and do a git pull before hand
