### ISSUE TITLE
sudden stop and no output file

### ISSUE THREAD

**Issue by hydrastarmaster** [laramies/theHarvester#86]
Kali 2018.02. TheHarvester 3.0.
Executed command:    theHarvester.py -d $target_domain -l 500 -b all -f ./report.htm

The most of the time it stops during the harvest. RC=0. No preconditions.

Fault points:
[-] Searching in PGP Key server..
            Searching PGP result..
                ---->{sudden stop}

or during Virtual Hosts scanning.

The most of the time output files are not written (no specific precondition).

Problems in the stash.sqlite file:
- mail items are registered but data are not complete (eg: it saves 'evilcorp.com' instead of 'admin@evilcorp.com').
- DNS scope not saved (... compare with Virtual Hosts output).

**Comment by kafkaesqu3** [comment]
I am also having this issue

**Comment by yaleman** [comment]
If you're using the current codebase it's because the PGP server that theHarvester makes requests to is not responding to requests. You can fix that by editing discovery/pgpsearch.py and uncommenting the MIT one. That can give inconsistent results too, however.

**Comment by laramies** [comment]
That's right, the PGP error is due to the server from Rediris being down, but in theory in the latest release the default one is the MIT, i just tried an it worked fine. If you have further ideas on how to improve PGP search please open a new issue.
