### ISSUE TITLE
Always ended with "killed"

### ISSUE THREAD

**Issue by y0sua** [laramies/theHarvester#863]
Hi
can you help me, why I am always ended with "killed" result
I tried it for several times for several domain

command:
python3 theHarvester.py -d site.com -b all

https://prnt.sc/1ttm9td

Thanks

**Comment by L1ghtn1ng** [comment]
What OS are you running this on?

**Comment by y0sua** [comment]
Hi @L1ghtn1ng ,
it is Ubuntu 18 on my VPS

```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by L1ghtn1ng** [comment]
you will want to use 20.04 and use a python virtual environment and you should be good after that

**Comment by y0sua** [comment]
got it , thanks 
so I will use ubuntu at least 20.04

I will try it

**Comment by L1ghtn1ng** [comment]
timeout
