### ISSUE TITLE
[Bug] censys module broken

### ISSUE THREAD

**Issue by leebaird** [laramies/theHarvester#865]
Bug

Describe the feature request or bug or other
The censys module no longer returns any results.
Tried both the Kali and GitHub versions.
No errors shown.

To Reproduce
Kali: theHarvester -d yale.edu -b censys
Added API key to /etc/theHarvester/api-keys.yaml

GitHub: ./theHarvester.py -d yale.edu -b censys
Added API key to api-keys.yaml

Expected Behavior
693 results

System Information
OS: Kali Linux
Version 2021.3

**Comment by NotoriousRebel** [comment]
Is this using the latest version of the tool?

**Comment by leebaird** [comment]
Yes
