### ISSUE TITLE
[Bug] dnsdumpster module broken

### ISSUE THREAD

**Issue by leebaird** [laramies/theHarvester#866]
Bug

Describe the feature request or bug or other
The dnsdumpster module no longer returns any results.
Tried both the Kali and GitHub versions.
No errors shown.

To Reproduce
Kali: theHarvester -d yale.edu -b dnsdumpster
GitHub: ./theHarvester.py -d yale.edu -b dnsdumpster

Expected Behavior
101 records

System Information
OS: Kali Linux
Version 2021.3

**Comment by NotoriousRebel** [comment]
This has been fixed in #872.

**Comment by leebaird** [comment]
Fixed by PR #872. Thanks Matt.
