### ISSUE TITLE
[Bug] hunter module broken

### ISSUE THREAD

**Issue by leebaird** [laramies/theHarvester#867]
Bug

Describe the feature request or bug or other
The hunter module no longer returns any results.
Tried both the Kali and GitHub versions.
No errors shown.

To Reproduce
Kali: theHarvester -d yale.edu -b hunter
Added API key to /etc/theHarvester/api-keys.yaml

GitHub: ./theHarvester.py -d yale.edu -b hunter
Added API key to api-keys.yaml

Expected Behavior
23,693 results

System Information
OS: Kali Linux
Version 2021.3

Additional Information
- Domains
https://api.hunter.io/v2/domain-search?domain=target.com&api_key=MY_API_KEY

- Emails
https://api.hunter.io/v2/email-finder?domain=target.com&first_name=Joe&last_name=Smith&api_key=MY_API_KEY

**Comment by NotoriousRebel** [comment]
This has been fixed in #872.

**Comment by leebaird** [comment]
Fixed by PR #872. Thanks Matt.
