### ISSUE TITLE
[Bug] netcraft module broken

### ISSUE THREAD

**Issue by leebaird** [laramies/theHarvester#868]
Feature Request or Bug or Other
Bug

Describe the feature request or bug or other
The netcraft module no longer returns any results.
Tried both the Kali and GitHub versions.
No errors shown.

To Reproduce
Kali: theHarvester -d yale.edu -b netcraft
GitHub: ./theHarvester.py -d yale.edu -b netcraft

Expected Behavior
unknown

System Information
OS: Kali Linux
Version 2021.3

**Comment by L1ghtn1ng** [comment]
This has been removed due to them having a block and only returning 20 results from the site and having to need to contact them to get more data
