### ISSUE TITLE
[Bug] omnisint module broken

### ISSUE THREAD

**Issue by leebaird** [laramies/theHarvester#869]
Feature Request or Bug or Other
Bug

Describe the feature request or bug or other
The omnisint module no longer returns any results.
Tried both the Kali and GitHub versions.
No errors shown.

To Reproduce
Kali: theHarvester -d yale.edu -b omnisint
GitHub: ./theHarvester.py -d yale.edu -b omnisint

Expected Behavior
34,074 results

System Information
OS: Kali Linux
Version 2021.3

**Comment by L1ghtn1ng** [comment]
This is fixed in my fork, will do a PR once other issues are fixed as well
