### ISSUE TITLE
theHarvester quits without any results

### ISSUE THREAD

**Issue by gligorvlad97** [laramies/theHarvester#87]
![image](https://user-images.githubusercontent.com/42137685/43708042-2a078e4a-9972-11e8-9bbb-dc5088bab8bc.png)

After entering the last command, the only output is the green title with version, nothing more.
I use kde neon, i installed the library request, also i am no pro user of linux, any ideas?

**Comment by vladwelt** [comment]
You should write just the domain:

`python theHarvester.py -d kali.org -b all -d output.xml`

I hope this helps you, greetings.

**Comment by laramies** [comment]
Correct @vladwelt comments is right, the format for the domain is without the HTTPS://
