### ISSUE TITLE
Cant provide a list of sources ??

### ISSUE THREAD

**Issue by whoot** [laramies/theHarvester#88]
Hey,

am I overlooking something or is it not possible to provide multiple sources?
I know I can specify sources with -b, but this allows only 1 parameter.
This means that if I want to check lets say _google, bing and twitter_ I cant do something like:

theharvester -d example.com -b google,bing,twitter

Instead I have to start the harvester 3 times ...

theharvester -d example.com -b google
theharvester -d example.com -b bing
theharvester -d example.com -b twitter

Otherwise theharvester will only use the first source (or throw an 'Invalid search engine' error)...

It would be very useful to be able to use more than just one (or all) sources.

**Comment by jzold** [comment]
hey whoot,

I'll take a look and provide a potential fix for this shortly.

**Comment by laramies** [comment]
Closing this one, as @jzold fix provides that functionality, I tried with  -b crtsh,virustotal and works fine. :)
