### ISSUE TITLE
<strong> in virtual host results

### ISSUE THREAD

**Issue by offroadaz** [laramies/theHarvester#9]
Not sure why, but < strong > is displaying in my results for virtual hosts

example
./theHarvester.py -d godaddy.com -b google -v

Virtual hosts:
23.43.189.116   < strong >www.godaddy.com<

any ideas?

**Comment by laramies** [comment]
Seems that the strong is not being scrubbed, I will review the parser. Thanks

**Comment by initbar** [comment]
@laramies : If you haven't already, can I try this? :)

**Comment by laramies** [comment]
Sorry for my late reply, if you want to work on it feel free, otherwise I will check the problem in the parser in the next update.

**Comment by NotoriousRebel** [comment]
As this has been resolved, closing!
