### ISSUE TITLE
python3 changes

### ISSUE THREAD

**Issue by yaleman** [laramies/theHarvester#91]
Is it worth my time submitting pull requests to support python 3? 

I have a load of changes that wouldn't break the python2 version which would get the codebase closer to being supported with python3.. which is important because v2's officially going away in the future.

**Comment by laramies** [comment]
Could be a good option to start with a few files, see how it goes, and then continue with the rest?  if there is not going to break Python2 should be good.

**Comment by laramies** [comment]
Python3 compatible now!
