### ISSUE TITLE
[Bug] Instant No result whatever domain/source used

### ISSUE THREAD

**Issue by soufianetahiri** [laramies/theHarvester#921]
I get instant no result whatever domain/source used :

[*] No IPs found.
[*] No emails found.
[*] No hosts found.

tested under : 
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"

**Comment by L1ghtn1ng** [comment]
How have you installed it?

**Comment by soufianetahiri** [comment]
$ ~ > git clone https://github.com/laramies/theHarvester 
    $ ~ > cd theHarvester
  $ ~ > python3 -m pip install -r requirements/base.txt

Everything went OK.

Gave it a first try with:
python3 theHarvester.py -d microsoft -l 200 -d linkedin
python3 theHarvester.py -d microsoft.com -l 200 -d all

Tried with virtualenv as well.
The same result instantly seems like he made no request (and did not a feature to make it pass trough a proxy just to see..)

**Comment by L1ghtn1ng** [comment]
You are using the wrong flag for sources as you are using -d for the sources which need to be a -b  the -d is for the domain only going by your output you have provided

Sent from my iPhone

On 18 Nov 2021, at 13:57, Soufiane Tahiri ***@***.***> wrote:

﻿

$ ~ > git clone https://github.com/laramies/theHarvester
$ ~ > cd theHarvester


$ ~ > python3 -m pip install -r requirements/base.txt

Everything went OK.

Gave it a first try with:
python3 theHarvester.py -d microsoft -l 200 -d linkedin
python3 theHarvester.py -d microsoft.com -l 200 -d all

Tried with virtualenv as well.
The same result instantly seems like he made no request (and did not a feature to make it pass trough a proxy just to see..)

**Comment by soufianetahiri** [comment]
Ok I feel stupid :)
