### ISSUE TITLE
[Error saving JSON file] [!] An error occurred while saving the JSON file: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by D3vil0per** [laramies/theHarvester#928]
**Issue**
[!] An error occurred while saving the JSON file: a bytes-like object is required, not 'str' output

**Description of bug**
When I try simply to execute:

`python3 theHarvester.py -d anydomain.com -b anysource -f ~/outputharvest`

At the end of the results I have the following messages:
    [*] Reporting started.
    [*] XML File saved.
    [!] An error occurred while saving the JSON file: a bytes-like object is required, not 'str' 

Looking online, in general this issue should be related to the opening the file JSON in binary mode. Does anyone have the same issue? Could you fix it please?

**System Information (System that tool is running on):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Version TheHarvester: 4.0.3

**Comment by NotoriousRebel** [comment]
This has been fixed with the latest commit, if the issue still persists after the latest commit please reopen this issue.

**Comment by Hideki047** [comment]
Hello, I have the same problem and I don't know how to solve it.

**Comment by seaona** [comment]
Same problem on Kali

**Comment by L1ghtn1ng** [comment]
Can you tell me your kali version and the version of theHarvester that you are using please?

On 24 Aug 2022, at 13:46, seaona ***@***.***> wrote:

﻿

Same problem on Kali

**Comment by NathanRodet** [comment]
On kali, just update like this : 
`sudo apt-get remove theharvester && sudo apt-get install theharvester`

**Comment by alanvaztick** [comment]
> En kali, solo actualice así : `sudo apt-get remove theharvester && sudo apt-get install theharvester`

It Works for me, Thanks a lot :D !!!!!
