### ISSUE TITLE
[Bug] [!] An error occurred while saving the XML/JSON file: [Errno 2] No such file or directory: 'filename.ext'

### ISSUE THREAD

**Issue by D3vil0per** [laramies/theHarvester#935]
**Issue**

     [!] An error occurred while saving the XML file: [Errno 2] No such file or directory: '~/filename.xml' 
     [!] An error occurred while saving the JSON file: [Errno 2] No such file or directory: '~/filename.json' 

**Description of bug**
When I try simply to execute:

`python3 theHarvester.py -d anydomain.com -b anysource -f "~/filename"`

At the end of the results I have the following messages:

    [*] Reporting started.
    [!] An error occurred while saving the XML file: [Errno 2] No such file or directory: '~/filename.xml' 
    [!] An error occurred while saving the JSON file: [Errno 2] No such file or directory: '~/filename.json' 

It happens because the open() function inside `theHarvester/__main__.py` at line 831 and 892 does not recognize the `~/` as user home folder, because `w+` in general can create a non-existent file but cannot create a non-existent directory, and for open() function the `~/` directory does not exist. It works only if the tilde is outside the "" otherwise it needs to be expanded.
Source: https://stackoverflow.com/questions/32024460/python3-4-opening-file-with-mode-w-still-gives-me-filenotfound-error?lq=1
https://askubuntu.com/questions/1192981/why-isnt-tilde-recognised-as-home-folder-in-this-case

I know it is only a small formality, is it possible to fix it allowing also the usage of `~/` path inside the ""?

**System Information (System that tool is running on):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Version TheHarvester: 4.0.3

**Comment by NotoriousRebel** [comment]
@L1ghtn1ng This actually wouldn't be too hard to add where we check if first two chars of string are equal to "~/" if so we can use `os.path.expanduser`

**Comment by L1ghtn1ng** [comment]
Nice, if you could add that?

On 2 Dec 2021, at 01:32, Matt ***@***.***> wrote:

﻿

@L1ghtn1ng<https://github.com/L1ghtn1ng> This actually wouldn't be too hard to add where we check if first two chars of string are equal to "~/" if so we can use os.path.expanduser

**Comment by NotoriousRebel** [comment]
@D3vil0per At [line 68](https://github.com/laramies/theHarvester/blob/master/theHarvester/__main__.py#L68) can you add the following code:  

```py
    import os
    if len(filename) > 2 and filename[:2] == "~/":
        filename = os.path.expanduser(filename)
```
Then rerun the cmdline you provided beforehand, please let me know if this fixes it.

**Comment by D3vil0per** [comment]
@NotoriousRebel applying that code, I confirm the tool works correctly now:

`theHarvester -d google.com -b baidu -f "~/outputbaidu"`

    [*] Target: google.com 
 
    [*] Searching Baidu. 

    [*] No IPs found.

    [*] No emails found.

    [*] Hosts found: 10
    ---------------------
    accounts.google.com:142.251.39.109
    adwords.google.com:142.250.27.113
    code.google.com:142.251.39.110
    hangouts.google.com:142.250.179.206
    images.google.com:142.250.179.206
    mail.google.com:172.217.168.229
    plus.google.com:216.58.214.14
    services.google.com:172.217.168.238
    translate.google.com:142.250.179.206
    www.google.com:216.58.214.4

    [*] Reporting started.
    [*] XML File saved.
    [*] JSON File saved.

Also the content of the output files is correct.

**Comment by D3vil0per** [comment]
Hello!
@NotoriousRebel I made a pull request on the mentioned file in order to close this issue when the change in the pull request will be merged. Thank you for your cooperation!
