### ISSUE TITLE
Bug - lost all connections with SSL certs and :443 ports

### ISSUE THREAD

**Issue by bdholde** [laramies/theHarvester#936]
**Bug | Other

**Describe the feature request or bug or other**

I ran an update and now all the programs are failing. I am getting multiple :443 certificate errors. I can ping outside my VM at 8.8.8.8. I also receive network unreachable for google.com

An example of the errors are below:

an exception has occurred: Cannot connect to host api.qwant.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '194.187.168.106'. (_ssl.c:1129)")]

an exception has occurred: Cannot connect to host api.duckduckgo.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '52.149.246.39'. (_ssl.c:1129)")] Exception occurred: Expecting value: line 1 column 1 (char 0)

An exception has occurred: Cannot connect to host www.google.com:443 ssl:<ssl.SSLContext object at 0x7fb8e05f3940> [Network is unreachable]

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tool like this: └─$ theHarvester -d kali.org -l 500 -b all   

**Expected behaviour**
Before the update, I was receiving proper data from the various programs. All I get in return now is some basic Linkedin results. 

**Screenshots**
If possible please add screenshots to help explain your problem.

**System Information (System that tool is running on):**
 - VM virutalbox manager
 - Kali VM from the OSINT project

**Additional context**

**Comment by L1ghtn1ng** [comment]
Can you please tell me the version of theHarvester you are running?

**Comment by bdholde** [comment]
yes sir... 4.0.1.  The error occurs in virtualbox but when I run it with the ISO in VMWARE workstation 15.5 PRO it is fine.

**Comment by L1ghtn1ng** [comment]
That is an old version of the tool, if you use the version from git do you get this issue?

**Comment by bdholde** [comment]
With using the updated version and a full update/reboot, the problem disappeared.  Thank you for all the help.
