### ISSUE TITLE
[Bug] Issue with helpers.py

### ISSUE THREAD

**Issue by Desperaxe** [laramies/theHarvester#954]
Hi there,
I actually can't run theHarvester whatever command is used, it can just be a "theHarvester" or a complete command to harvest, I always get this issue :

![image](https://user-images.githubusercontent.com/96437538/146803071-ebaee7c4-830c-4074-b112-a25ed47d2d47.png)

Note : I've never modified a py file in my environment, just installed theHarvester and every component. I already tried to uninstall to reinstall, no matter what, theHarvester won't work..

Many thanks in advance

**Comment by L1ghtn1ng** [comment]
What OS are you using and how did you install theHarvester?

On 20 Dec 2021, at 16:52, Desperaxe ***@***.***> wrote:

﻿

Hi there,
I actually can't run theHarvester whatever command is used, it can just be a "theHarvester" or a complete command to harvest, I always get this issue :

[image]<https://user-images.githubusercontent.com/96437538/146803071-ebaee7c4-830c-4074-b112-a25ed47d2d47.png>

Note : I've never modified a py file in my environment, just installed theHarvester and every component. I already tried to uninstall to reinstall, no matter what, theHarvester won't work..

Many thanks in advance

**Comment by Desperaxe** [comment]
Hi,

Sorry, I should explain this part too, I'm working on a Kali Linux, theHarvester was already inside when I started using it and I already ran theHarvester in this Kali

**Comment by 8linkz** [comment]
Hi,

have also had the problem Kali 04/2021 up to date. 

Here's how I solved it for myself:
git clone https://github.com/laramies/theHarvester 
cd theHarvester
python3 -m pip install -r requirements/base.txt

After the dependencies are installed:
cd .. 
theHarvester

└─$ theHarvester   

*******************************************************************
*  _   _                                            _             *
* | |_| |__   ___    /\  /\__ _ _ ____   _____  ___| |_ ___ _ __  *
* | __|  _ \ / _ \  / /_/ / _` | '__\ \ / / _ \/ __| __/ _ \ '__| *
* | |_| | | |  __/ / __  / (_| | |   \ V /  __/\__ \ ||  __/ |    *
*  \__|_| |_|\___| \/ /_/ \__,_|_|    \_/ \___||___/\__\___|_|    *
*                                                                 *
* theHarvester 4.0.3                                              *
* Coded by Christian Martorella                                   *
* Edge-Security Research                                          *
* cmartorella@edge-security.com                                   *
*                                                                 *
******************************************************************* 


usage: theHarvester [-h] -d DOMAIN [-l LIMIT] [-S START] [-g] [-p] [-s] [--screenshot SCREENSHOT] [-v] [-e DNS_SERVER] [-t DNS_TLD] [-r] [-n] [-c] [-f FILENAME] [-b SOURCE]
theHarvester: error: the following arguments are required: -d/--domain

For me as a layman, it looks like the dependencies are partially missing in Kali.

I hope I could help you a little further.

**Comment by L1ghtn1ng** [comment]
This is a kali bug so closing this out
