### ISSUE TITLE
shodan

### ISSUE THREAD

**Issue by Andrewblood** [laramies/theHarvester#96]
When the server have more adresses it searches to fast with shodan
That's the output:

[-] Shodan DB search (passive):
 Request rate limit reached (1 request/ second). Please wait a second before trying again and slow down your API calls.

On https://developer.shodan.io/api stands also Note: All API methods are rate-limited to 1 request/ second. please fix that or help me to fix that.

**Comment by jzold** [comment]
Hi Andrew,

There is a relatively quick fix for this, I'll take a look shortly

J./

**Comment by laramies** [comment]
Closing this issue as @jzold provided a workaround.
