### ISSUE TITLE
RuntimeWarning: Enable tracemalloc to get the object allocation traceback_

### ISSUE THREAD

**Issue by Al3x1S4** [laramies/theHarvester#964]
Hi guys :) 

I have an issue when running The Harvester with all

$ python3 theHarvester.py -d example.com -l 10 -b all

return -->

_[*] Target: example.com 
 
[!] Missing API key for ProjectDiscovery. 

[!] Missing API key for Spyse. 

[!] Missing API key for binaryedge. 

[!] Missing API key for zoomeye. 

[!] Missing API key for RocketReach. 
string indices must be integers
string indices must be integers
sys:1: RuntimeWarning: coroutine 'start.<locals>.store' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback_

If someone could help me with that it will be amazing :)

**Comment by L1ghtn1ng** [comment]
How have you installed it and on what OS and what version are you running of theHarvester?

On 23 Dec 2021, at 10:50, Al3x1S4 ***@***.***> wrote:

﻿

Hi guys :)

I have an issue when running The Harvester with all

$ python3 theHarvester.py -d example.com -l 10 -b all

return -->

_[*] Target: example.com

[!] Missing API key for ProjectDiscovery.

[!] Missing API key for Spyse.

[!] Missing API key for binaryedge.

[!] Missing API key for zoomeye.

[!] Missing API key for RocketReach.
string indices must be integers
string indices must be integers
sys:1: RuntimeWarning: coroutine 'start..store' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback_

If someone could help me with that it will be amazing :)

**Comment by Al3x1S4** [comment]
I'm on Mac OS Catalina

I have installed it with git clone...

I have install a venv to install dependencies and run the programm with python3.
