### ISSUE TITLE
[Bug] Not able to run the harvester app

### ISSUE THREAD

**Issue by anju-wal** [laramies/theHarvester#971]
## Note we do not support installing theHarvester on andriod

**Feature Request or Bug or Other**
Bug 

**Describe the feature request or bug or other**
While using the command 
` docker run the-harvester-image`
It gives the following error
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/app/restfulHarvest.py -H 0.0.0.0 -p 80": stat /app/restfulHarvest.py -H 0.0.0.0 -p 80: no such file or directory: unknown.
`
**To Reproduce**
Steps to reproduce the behaviour:
1. Using Cloud 9

**Expected behaviour**
able to see the welcome screen for The harvester

**Screenshots**
If possible please add screenshots to help explain your problem.

**System Information (System that tool is running on):**
AWS-Cloud 9, free tier

**Additional context**

**Comment by L1ghtn1ng** [comment]
This is not something we support, please install using one of the install methods in the wiki
