### ISSUE TITLE
I am trying to add the API key for hunter but when I type nano /usr/share/theharvester/discovery/huntersearch.py, It says that Directory '/usr/share/theharvester/discovery/' does not exist

### ISSUE THREAD

**Issue by loda26** [laramies/theHarvester#973]

**Comment by loda26** [comment]
![Capture](https://user-images.githubusercontent.com/96872940/147754017-1a3bf07e-d96c-4c8e-90b4-010a9825bffd.PNG)

**Comment by L1ghtn1ng** [comment]
It is in /etc/theHarvester

Thanks,
Jay

On 30 Dec 2021, at 12:58, loda26 ***@***.***> wrote:

﻿

[Capture]<https://user-images.githubusercontent.com/96872940/147754017-1a3bf07e-d96c-4c8e-90b4-010a9825bffd.PNG>
