### ISSUE TITLE
docker image run error 

### ISSUE THREAD

**Issue by adbhutmaharaj** [laramies/theHarvester#991]
## Note we do not support installing theHarvester on andriod

Bug or Error

**Describe the bug or other**
After creating a successful docker image, when I try to run it, it displays the below given error message, cannot find a way around it, can you guys help?

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tool like this: 'docker run theharvester -h'
2. See error "Docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/app/restfulHarvest.py -H 0.0.0.0 -p 80": stat /app/restfulHarvest.py -H 0.0.0.0 -p 80: no such file or directory: unknown.
ERRO[0001] error waiting for container: context canceled"

**Expected behaviour**
to see the help message.

**System Information (System that tool is running on):**
 - OS: Kali
 - Version: 2021.4 

**Additional context**

**Comment by NotoriousRebel** [comment]
Are you using the latest version of the tool? Just to double check as well, the container was successfully built right?

**Comment by adbhutmaharaj** [comment]
yes, the latest build and the container was build successfully!

**Comment by IvanStanul** [comment]
Also getting this problem. Cloned repo, built image, tried running - received the same error.

**Comment by L1ghtn1ng** [comment]
I pushed out an update for docker yesterday, you made sure you have an up to date version of the docker file?

**Comment by IvanStanul** [comment]
Yes. Dockerfile used:
``` 
FROM ubuntu:impish
LABEL maintainer="@jay_townsend1 & @NotoriousRebel1"
RUN mkdir /app
WORKDIR /app
COPY . /app
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt dist-upgrade -qy && apt install -qy git python3 python3-pip libffi-dev libxml2-dev libxslt1-dev && /usr/bin/python3 -m pip install --upgrade pip && apt autoremove -qy
RUN /usr/bin/python3 --version && pip3 install --no-cache-dir -r requirements.txt && chmod +x ./*.py
ENTRYPOINT ["/app/theHarvester.py"]
ENTRYPOINT ["/app/restfulHarvest.py -H 0.0.0.0 -p 80"]
EXPOSE 80
``` 

Error got:  
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/app/restfulHarvest.py -H 0.0.0.0 -p 80": stat /app/restfulHarvest.py -H 0.0.0.0 -p 80: no such file or directory: unknown.
ERRO[0000] error waiting for container: context canceled
```

**Comment by phplucas** [comment]
Hey guys,

The problem is at the entry point. Change to:

`ENTRYPOINT ["/app/restfulHarvest.py", "-H",  "0.0.0.0",  "-p",  "80"]`

**Comment by joaociocca** [comment]
curious. I had to remove this second entrypoint for `docker run theharvester -h` or else it'd always use that entrypoint when I tried to run `docker run theharvester` for anything else, and then `-d <domain> -s <sources>` would fail because they are not arguments for `restfulHarvest.py`
